### ISSUE TITLE
9.4.4 Upgrade from 9.1.1 CONTENT > PAGES There was an error retrieving your content. Please check your internet connection

### ISSUE THREAD

**Issue by Rob-Brun** [dnnsoftware/Dnn.Platform#3465] opened 2020-01-10 13:19 UTC
**Description of bug**

After upgrading from 9.1.1 I am unable to edit CONTENT > PAGES as there are no pages shown and Settings > Site Setting as there are no setting shown and I get the following error:
There was an error retrieving your content. Please check your internet connection

Steps to reproduce

    Upgrade from 9.1.1 to 9.4.4
    Click on persona bar and try to view pages and site settings
    There was an error retrieving your content. Please check your internet connection
    No pages displayed, unable to edit pages on website using persona bar. No site settings displayed.

Affected version

    9.4.4

Affected browser

Chrome
Firefox
Safari
Internet Explorer
Edge

Additional

I have removed all modules that were incompatible or throwing errors.

**Comment by valadas** [comment] 2020-01-12 16:40
Can you look if you have any logs in either the browser console, or in the Admin Logs menu or in the Portals/_default/logs, I have done multiple upgrades from 9.1.1 to 9.4.4 without issues. My guess is there is something specific to this installation (module, handler, bad uninstallation of a module, etc.) and those logs would help pinpoint it

**Comment by Rob-Brun** [comment] 2020-01-13 12:49
There is nothing in the Admin logs, but here is what I get in the server logs, note the 500 errors on the last 2 entries...

2020-01-13 12:38:52 XXX.XXX.XXX.XXX GET /API/personaBar/ServerSummary/GetServerInfo - 443 xxxxx@xxxxxx.xxx XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 95
2020-01-13 12:38:52 XXX.XXX.XXX.XXX GET /API/personabar/serversummary/GetUpdateLink - 443 xxxxx@xxxxxx.xxx XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 665
2020-01-13 12:38:58 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/css/open-sans.semibold.ttf - 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/css/main.css?cdv=1508 200 0 0 100
2020-01-13 12:39:02 XXX.XXX.XXX.XXX POST /API/personaBar/UserSettings/UpdateUserSettings - 443 xxxxx@xxxxxx.xxx XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 203
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/modules/Dnn.Pages/scripts/Pages.js cdv=1508 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 43
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/modules/Dnn.Pages/css/Pages.css - 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 304 0 0 46
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/scripts/contrib/text.js cdv=1508 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 52
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/scripts/contrib/jquery-ui.min.js cdv=1508 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 114
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/modules/Dnn.Pages/Pages.html cdv=1508 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 45
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /API/personaBar/MenuExtensions/GetExtensions menu=Dnn.Pages 443 xxxxx@xxxxxx.xxx XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 129
2020-01-13 12:39:02 XXX.XXX.XXX.XXX GET /DesktopModules/admin/Dnn.PersonaBar/modules/dnn.pages/scripts/bundles/pages-bundle.js cdv=1508 443 - XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 200 0 0 196
2020-01-13 12:39:03 XXX.XXX.XXX.XXX GET /API/PersonaBar/Pages/GetContentLocalizationEnabled - 443 xxxxx@xxxxxx.xxx XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 500 0 0 55
2020-01-13 12:39:03 XXX.XXX.XXX.XXX GET /API/PersonaBar/Pages/GetPageList searchKey= 443 xxxxx@xxxxxx.xxx XXX.XXX.XXX.XXX Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:72.0)+Gecko/20100101+Firefox/72.0 https://xxx.xxxxx.xxx/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=1508 500 0 0 71
2

**Comment by Rob-Brun** [comment] 2020-01-13 13:01
I get the same error when I try to access Site Settings, when I try to Clear Cache or Restart Application.

**Comment by Rob-Brun** [comment] 2020-01-13 13:31
I have also notices that Newtonsoft.Json is listed twice in the web.config.  Once as version 10 and once as version 8.  If I try to get rid of version 8, something puts it back.

**Comment by Rob-Brun** [comment] 2020-01-13 21:27
Here is some output from the Chrome debugger...
API/PersonaBar/Pages/GetContentLocalizationEnabled:1 Failed to load resource: the server responded with a status of 500 ()
API/PersonaBar/Pages/GetPageList?searchKey=:1 Failed to load resource: the server responded with a status of 500 ()

**Comment by valadas** [comment] 2020-01-15 05:49
> I have also notices that Newtonsoft.Json is listed twice in the web.config. Once as version 10 and once as version 8. If I try to get rid of version 8, something puts it back.

This might be the issue, which third party modules are used on the site. Modules that inject config changes should do so only during installation and not at runtime. And when done properly it would also have a comment above indicated which module modified the web.config...

I am closing this issue since it is not actionable on Dnn side of things, but we can continue discussing and troubleshooting even if the issue is closed.

**Closed by valadas** 2020-01-15 05:49 UTC
Labels: Status: Blocked
