### ISSUE TITLE
Creating New Pages as SSL Enabled (IsSecure) When Portal Settings Dictate

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#2402] opened 2018-10-16 21:37 UTC
## Description of Bug/Issue
If a Portal has been set to allow and enforce SSL by having the SSL Enabled and SSL Enforced settings made, then the actions to Create a new Page (Tab) should by default select the Secure Page Setting so that the IsSecure data value is set for the Tab settings in the database.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Portal Settings and confirm that the SSL options for Enable SSL and Enforce SSL are checked and that the site is properly loading host/admin pages as https
2. From the Admin/Pages screen, create a new page
3. Confirm the newly created Page's Settings show "Secure" (IsSecure) is not checked

## Current result
Currently, when you create a new page, you must make a second action to click the Secure checkbox wtihin Page Settings.

## Expected result
The Create Page action should evalute the Portal Settings for Enforce SSL to determine whether a newly created page should be set as SSL by default.

OR

The checkbox within the screens for creating a new page should at least have the Secure checkbox value already checked because of these Portal-level values.

## Additional context
The problem created is that administrators can miss the fact that this new page has been created non-ssl enforced, having assumed that they have set the correct Portal settings previously. This allows them to create new pages that are not following those Portal settings.

Obviously, this is merely a nuisance and can be corrected by modifying the Page Settings. In one client example, where there is an additional http to https rule within the web.config, this situation created the additional htts-redirect-loop situation where a newly created page could not load or rediret properly without redirecting back to https (and starting the loop again). The content administrator, not noticing that the page was not set as Secure, assumed that DNN was "broken"

## Affected version
This affects DNN 7, 8 and 9, I can check further if needed...
* [x ] 9.0
* [x ] 8.x
* [x ] 7.x

**Comment by moorecreative** [comment] 2019-05-20 14:33
Peter Donker has suggested a change to the way that the HTTPS settings in DNN might control the whole of page settings... this might help with this issue

https://github.com/dnnsoftware/Dnn.Platform/issues/2808

**Comment by valadas** [comment] 2019-07-28 03:14
As of Dnn 9.4.0 RC it looks like with those steps to reproduce, it does show the secured option ON by default, closing this, but #2808 is a nice one that might also improve this.

**Closed by valadas** 2019-07-28 03:14 UTC
Labels: help wanted
