### ISSUE TITLE
DNN 9.11.2 and 9.12.0, Enter password is required everytime to send a Test Email 

### ISSUE THREAD

**Issue by DimpeeTheCoder** [dnnsoftware/Dnn.Platform#5710] opened 2023-06-26 18:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Servers / SMTP server control panel, the SMTP Password field is empty on UI and required to fill every time to run a test email.

### Steps to reproduce?

List the precise steps to reproduce the bug:

1. Start at the Servers / SMTP server control panel
2. Fill in the correct information about the SMTP server (URL, port, etc.)
3. Select "Basic" authentication
4. Enter the SMTP username and password.
5. Click save and the "Test SMTP Settings" and everything works perfectly.
6. Log off or do some other stuff. Go back to the Servers / SMTP Server control panel.
7. Under the label, "SMTP Password", there will be a link "change" - **do not click on it.**
8. Click on "Test SMTP Settings" - now you get an error message (something about the SMTP configuration)
9. Now click on the "change" link and re-enter the password and then test again. Everything works perfectly.
10. If you go away to do some other stuff and return to "Test SMTP Settings", you get the same error message about the SMTP configuration.

### Current Behavior

If you check the database, you will see you have the password saved, but it won't reflect on the UI, which is still an issue while sending test emails.

### Expected Behavior

If the password is saved in the database, There should not be a problem sending the emails without every time entering the password in UI.

### Affected Versions

9.12.0 (latest release)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DimpeeTheCoder** [comment] 2023-06-26 18:59
This issue has come after UI changes #5152, UI issue has not been resolved yet.

**Comment by valadas** [comment] 2023-06-26 20:11
I cannot make this issue happen, can someone else test on 9.12.0...

**Comment by DimpeeTheCoder** [comment] 2023-07-20 12:10
> 

I have been testing Server settings> SMTP Server > SMTP Password > [ Change ] on two machines. on first machine, when user clicks [ change ], a textbox appear with no password in it. But on second machine, when user clicks [ change ], a textbox appear with password in it. This ambiguous behavior is creating confusion while testing. 
Searched a lot but not found the expected behavior. Kindly reply with the expected functionality and why facing such issue.

**Comment by valadas** [comment] 2023-07-20 14:33
Is it possible it is caused by some browser password manager plugin, can you try to see if it still happens in incognito mode?

**Comment by kennydeboe** [comment] 2023-11-10 13:23
We are having this issue too. After a few weeks/or even a month the SMTPserver doesn't work anymore.
If we reset the password (on admin/or host) then it works again.
I'm using DNN 9.11.1

I also found out that the password field on host never shows ***** (ObfuscateString), but on admin it does.
I debugged the files Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs and ServerSettingsSmtpHostController.cs and the password is in both cases filled in with the ObfuscateString  value.

**Comment by valadas** [comment] 2023-11-10 17:33
Now that 9.13.0 is out, can you give it a try on that version in case something may have fixed that

**Comment by cfr43regs** [comment] 2023-11-16 06:17
I have the same email issues where the mail fails on one portal and does not fail on nearly an identical portal on the same server. Upgraded from 9.12 to 9.13 and still having fits on the portal that fails to deliver mail until SMTP password is reset without using the test SMTP button. Mail flows through (including backed up mail) for a short period of time then quits delivering until the SMTP password is reset.

Setting the SMTP password, save, then test SMTP setting works. Come back in ten minutes and test SMTP setting fails without changing anything. Been on this for days and have not got a firm grip on the issue yet.

**Comment by cfr43regs** [comment] 2023-11-16 18:21
>>> Did you guys test incognito mode or without any password manager ?<<<

I'm a dumb*ss that does not know how to test DNN in incognito mode and do
not use password managers on my laptop. The sites I have are hosted by a
major DNN service provider that has replicated the issue and suggested
reporting the "undocumented feature" because it is not in their wheelhouse.

I had discovered that a v9.11 portal failed to relay emails since September
about 10 days ago and stumbled onto this thread while getting "learned up"
on what may be going on. As said with two identical sites (only difference
is one is a .net and the other a .com) the net site has the problem and the
other does not. The v9.13 upgrade did not correct the issue on the .net
site.

What is odd to me is the "Test SMTP Settings" in DNN does relay the mail
immediately but not traffic after the test. In a few tests, after resetting
the SMTP password sometimes mail may be delivered that is days old but then
all following mail fails to relay until the next SMTP password reset is
performed without clicking the "Test SMTP Setting" button. Just sharing my
test results here.

**Comment by valadas** [comment] 2023-11-16 19:10
Is there anything else cause I can't reproduce the issue. Can you make that issue happen on a brand new clean install of 9.13.0 ?

**Comment by cfr43regs** [comment] 2023-11-16 21:16
I'm porting code at the moment from the development .net site to the .com
site and plan to do a hosted wipe and fresh hosted install of 9.13 to get
to the bottom of this. I can't touch the SMTP on the .com sister site that
works for risk of losing its email traffic.

I have the test site where the issue occurs that you can access (I plan to
be on SFDNN today). Meanwhile I have a test in mind that will use a
different commercial module to test the SMTP failure issue to eliminate a
hunch I have. Believe me when I say that my DNN experience has been
sporadic since 2012, so I'm that guy running with scissors!

**Comment by cfr43regs** [comment] 2023-11-17 20:53
Although the SMTP Server test error message displays a problem:

[image: image.png]
I was able to send emails using a different commercial module even with the
DNN error displayed. I'm unsure why the previous commercial module quit
sending emails in this portal and continues to send emails from another
portal that is identical (except for .net and .com extension) on the same
hosted server. The upside for my application is that emails are going out
even with the SMTP Server error message being displayed.

Oddly the first offending commercial module would not send any emails, then
after manually resetting the SMTP password, send a few emails that were not
received by the recipient for hours or days...then quit transmitting emails
until the next SMTP password reset. All test emails that failed would
suddenly arrive at the destination at the same time.

I have not wiped the upgraded hosted DNN v9.13 (problem surfaced in v9.11)
to do a fresh install test yet.

**Comment by valadas** [comment] 2023-11-18 02:29
As this is not currently in a state where a developer can make it happen I will close this issue. If you find a way to make it happen from scratch feel free to add steps to make it happen and I'll be happy to re-open the issue.

**Closed by valadas** 2023-11-18 02:29 UTC
Labels: Status: New

**Comment by cfr43regs** [comment] 2023-11-18 02:47
Thank you, I will do that.
