### ISSUE TITLE
GetUserByVanityUrl being called multiple times

### ISSUE THREAD

**Issue by dtwilliams** [dnnsoftware/Dnn.Platform#2541] opened 2019-01-18 10:41 UTC
We are monitoring our SQL DNN db and have noticed the GetUserByVanityUrl is being called multiple times by random vanityUrls. We have amended the proc to log the amount of calls.

We are using DNN v9.02.01 (533)

Here is an example log
(https://github.com/dnnsoftware/Dnn.Platform/files/2772573/GetUserByVanityUrl.xlsx)

We seem to have around 55 users with these weird sequenced numbered vanityUrls in our UserPortals table.
Can we safely remove them? Anyone know what might have caused this?

**Comment by valadas** [comment] 2019-07-28 21:27
My best guess is that some automated scanning tool was scanning the vanity url with those values. Since nobody else replied to this issue, I am assuming it is not something widespread and is not easily reproducible so not an actionable issue and  closing this issue for those reasons.

@dtwilliams I would recommend backing up the database, then removing those wrong entries, that column supports nulls and I am not aware of this having side effects with other data, but if problems occur, you have that backup to revert to.

**Closed by valadas** 2019-07-28 21:27 UTC
