### ISSUE TITLE
Site and Global Assets do not use SSL when SSL enabled/enforced

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3207] opened 2019-10-26 23:25 UTC
## Description of bug
When SSL is enabled and enforced when you use Site assets and Global assets to manage files you are taken to an unsecured page

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a website SSL enabled with SSL enforced and set all your pages to SSL Enabled
![image](https://user-images.githubusercontent.com/13577556/67627233-dfd3b380-f80c-11e9-8ee0-184899f6eae2.png)

2. Navigate to  MANAGE > SITE ASSETS or MANAGE GLOBAL ASSETS
![image](https://user-images.githubusercontent.com/13577556/67627243-14e00600-f80d-11e9-8750-ffcbb861064d.png)

3. Page unsecured for both these pages
![image](https://user-images.githubusercontent.com/13577556/67627227-d5b1b500-f80c-11e9-99d4-89144558d60e.png)

**Comment by david-poindexter** [comment] 2019-10-27 00:03
@thabaum please make sure the File Management page's settings are set to a **Secure Connection**.  This should resolve your issue.

Thus, it is not a bug in the platform.  Since **Site Assets** and **Global Assets** simply point to a normal DNN "page", it will simply behave as the page is configured.  

That said, this is a bit confusing and is often overlooked because of it being the only admin functionality that surfaces as a normal "page" rather than as an extension in the Persona Bar experience.

I am going to go ahead and close this issue, but feel free to re-open if necessary.

**Closed** 2019-10-27 00:04 UTC
Labels: invalid

**Comment by thabaum** [comment] 2019-10-27 19:46
OK gotcha, thanks for the help I didnt realize it was a page i could edit properties for.  Suppose I just wish there was a way to set all pages to SSL.

Like when you select "SSL Enabled" website it should as would you like to make all pages on your site SSL Enabled.   Missed this one.

**Comment by thabaum** [comment] 2019-10-27 19:52
Is there a reason to have SEO "Allow Indexing" on for these pages?  They are host/admin pages. Are these pages that the indexing service should worry about for any reason?
