### ISSUE TITLE
9.2.2 Redirect After Login not Working

### ISSUE THREAD

**Issue by bwscheller** [dnnsoftware/Dnn.Platform#2413] opened 2018-10-18 18:58 UTC
## Description of bug
Redirect After Login not behaving as expected/difficulty in selecting desired page.  Only pages that have permissions set to All Users are selectable in the Redirect After Login dropdown in the Settings->Security->Login Settings.  Shouldn't permissions only be restricted to Registered Users?  Once a page has been selected in Settings->Security->Login Settings->Redirect After Login dropdown, a user is not redirected to the page after logging in.  Users are redirected to page set in the Settings->Security->Login Settings->Redirect After Logout upon logging out.

## Steps to reproduce
1. Add new page to fresh DNN 9.2.2 installation created with blank template
2. Set permissions on page to allow All Users and Registered Users to view page (This appears to be required in order to be able to select the page in the Redirect After Login pulldown, but I believe that only Registered Users should be required not All Users)
3. Go to Settings->Security->Login Settings->Redirect After Login and select the newly created page from Step 1
4. Go to Settings->Security->Login Settings->Redirect After Logout and select the Home page

## Current result
Logout as Administrator and log back in as a registered user.  The user is logged in, however, the home page is still displayed, not the newly created page from Step 1.

## Expected result
Logout as Administrator and log back in as a registered user.  The user is logged in and the newly created page from Step 1 is displayed.

## Affected version
* [x] 9.2.2

**Comment by sleupold** [comment] 2018-10-18 19:21
duplicate of #2267 and #2308.
please see PR #2275, which has already been merged for DNN 9.3.0

**Comment by chadwixk** [comment] 2019-03-06 18:08
Does this fix apply to Redirect after Registration as well or should I open a new issue for that?

**Comment by Zeakk** [comment] 2019-05-02 19:22
Any updates on when this may get fixed?

**Comment by idasbv** [comment] 2019-05-15 13:26
still an issue in DNN932....

**Comment by BrianBakewell** [comment] 2019-06-17 09:36
We are having an issue with having a URL that automatically logs you in with a generic account and someone tries to open any page on the site with a direct URL without going on to the site within the current session it will redirect them to the homepage and not go to the page requested. Is this related to this?

**Comment by valadas** [comment] 2019-07-28 04:07
I Think #2275 fixed this or something else fixed it as I am not able to reproduce in 9.4.0 RC, if you guys can still reproduce in 9.4.0 RC clean install, please open a new issue.

**Closed by valadas** 2019-07-28 04:07 UTC
