### ISSUE TITLE
Use Email Address as Username option doesn't handle super users

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3676] opened 2020-04-13 19:28 UTC
## Description of bug
When "Use Email Address as Username" option is enabled for a portal, super users can't log in.

## Steps to reproduce

1. Log in as a super user
2. Create a new portal. Don't set the super user as the admin of the new portal. Instead, create a new admin, for example Subsite Admin, subsiteadmin@change.me
3. Logout
4. Navigate to newly created portal and log in as subsiteadmin@change.me
5. Open SETTINGS > Security > Member Accounts > REGISTRATION SETTINGS and enable the "Use Email Address as Username" option.
6. Save the settings and log out.
7. Log back in using the super user's email address.

## Current behavior
"Login Failed. Please remember that passwords are case sensitive." error message is displayed

## Expected behavior
The super user should be able to login without issues.

## Affected version
* [X] 10.0.0 alpha build
* [X]  9.5.1 alpha build
* [X]  9.5.0 latest supported release
* [X]  9.4.4

**Comment by bdukes** [comment] 2020-04-13 21:13
Duplicate of #3658

**Closed by bdukes** 2020-04-13 21:13 UTC
Labels: Status: New
