### ISSUE TITLE
html editor cannot error on select image

### ISSUE THREAD

**Issue by mikecy** [dnnsoftware/Dnn.Platform#3321] opened 2019-11-20 17:19 UTC
## Description of bug
Open the HTML module and select image to open the browser control. when you select an image and you press ok it returns 
Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to HTML module 
2. Click on image
3. Select image
4. Press Ok

[MissingMethodException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.]
   DNNConnect.CKEditorProvider.Browser.Browser.CmdCloseClick(Object sender, EventArgs e) +0
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9797310
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +211
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

## Error log
DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.
   at DNNConnect.CKEditorProvider.Browser.Browser.CmdCloseClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.providers_htmleditorproviders_dnnconnect_cke_browser_browser_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [ ] 9.4.1 
* [X] 9.4.2 latest supported release

## Affected browser

* [X ] Chrome
* [ X] Firefox
* [ X] Edge

**Comment by mitchelsellers** [comment] 2019-11-20 19:13
This is going to be resolved in 9.4.3

**Comment by valadas** [comment] 2019-11-24 00:58
@mitchelsellers do you have a PR to reference this issue fix? Was it included in 9.4.3 ?

**Comment by mitchelsellers** [comment] 2019-11-24 01:53
Yes this is the same breaking change item.

**Comment by valadas** [comment] 2019-12-02 22:32
Oh, ok, so this is about the FriendlyUrl regression bug fixed by #3295 so it is fixed in 9.4.3 and I can close this issue. If I understood wrong, please reopen or comment...

**Closed by valadas** 2019-12-02 22:32 UTC
Labels: bug

**Comment by andyduo** [comment] 2019-12-03 00:50
Is there a workaround for this in 9.4.2 at all? In the middle of a build and can't use the image manger is  a bit of a show stopper.

**Comment by valadas** [comment] 2019-12-03 16:40
What do you mean by workaround, the issue is fixed in 9.4.3 right?

**Comment by andyduo** [comment] 2019-12-03 22:27
Yes I grabbed the update about 30 minutes after you released it and it's fixed. Thanks!
