### ISSUE TITLE
The site logo does not change

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3815] opened 2020-06-06 05:45 UTC
I try to change the site logo, but it doesn't work.

Error log:
`2020-06-06 09:57:39.859+03:30 [DESKTOP-U435NBL][D:2][T:6][ERROR] DotNetNuke.Web.InternalServices.FileUploadController - System.InvalidOperationException: Bad Request
   at DotNetNuke.Web.InternalServices.FileUploadController.UploadFile(Stream stream, Int32 portalId, UserInfo userInfo, String folder, String filter, String fileName, Boolean overwrite, Boolean isHostPortal, Boolean extract, String validationCode)`

## Affected version
*  09.06.01 latest supported release

**Comment by Scippy** [comment] 2020-06-06 07:51
Yes, with latest DNN 9.6.1 it is no more possible to uplod logo and icon on site setting.
Also entering URL link the logo link is saved.
The issue is on changing existing website and also creating new website.
In the latest DNN 9.6.0 it worked fine

**Comment by valadas** [comment] 2020-06-08 23:02
@donker Could this be something related to the files whitelist?

**Comment by Scippy** [comment] 2020-06-09 06:59
.png and .ico files are in files whitelist, and then I repeat myself, it worked fine on DNN 9.6.0

**Comment by gbulicanu** [comment] 2020-06-09 07:11
@david-poindexter, @valadas, @Scippy 
This will be fixed with  9.6.2 see PR #3769 this is duplicate of #3722 issue

**Comment by valadas** [comment] 2020-06-12 04:07
Oh, awesome, will close the issue then

**Closed by valadas** 2020-06-12 04:07 UTC
Labels: Area: AE > PersonaBar Ext > SiteSettings.Web, Effort: Medium, Priority: High, Status: Ready for Development, Type: Bug
