### ISSUE TITLE
ResourceManager in folder mode - default folder

### ISSUE THREAD

**Issue by FRMN-FRE** [dnnsoftware/Dnn.Platform#5467] opened 2023-01-05 17:12 UTC
## Description of bug
The default folder define in the module settings is not used as the root folder in the display page.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Open the settings of the module
2. Click on the tab "resourcemanager settings"
3. Choose Mode = Normal, Home folder = (any existing subfolder)
![image](https://user-images.githubusercontent.com/114243427/210839663-bb2ea045-33ab-4173-9e92-ad00328c52f1.png)

## Screenshots
Run the module.
The root folder is site root and not the selected subfolder is not selected
![image](https://user-images.githubusercontent.com/114243427/210840030-3ec9400e-4d7b-48d0-86e8-1fbee00e4781.png)

## Affected version
* [X ] 09.11.00 

## Affected browser
All browsers are affected

**Comment by mitchelsellers** [comment] 2023-01-05 17:18
@valadas This is a duplicate correct of what has already been fixed in 9.11.1

**Comment by FRMN-FRE** [comment] 2023-01-05 17:51
Perfect :-)
Hope 9.11.1 will be publish soon because we use a lot of the feature in our extranet

**Comment by valadas** [comment] 2023-01-05 19:37
> @valadas This is a duplicate correct of what has already been fixed in 9.11.1

I _think_ so, I'll flag this for 9.11.1 to make sure it gets tested before the release though, I'll close it once tested if already fixed.

**Comment by valadas** [comment] 2023-01-14 21:56
I can confirm this has been fixed in the current codebase, so would be fine in 9.11.1

Please keep an eye out for 9.11.1 RC to test it when it's published...

**Comment by FRMN-FRE** [comment] 2023-02-06 06:51
Hello, the folder list on the right pane is OK but the root folder in the treeview is still wrong.
It displays the root folder of the website and not the selected folder

**Comment by valadas** [comment] 2023-02-06 07:29
In 9.11.1-rc1 ?

**Comment by FRMN-FRE** [comment] 2023-02-06 07:37
yes

**Comment by david-poindexter** [comment] 2023-02-06 17:25
I am pretty sure RC1 is not possible to install at this point due to a reported bug.  I can confirm this has been resolved though in 9.11.1.  When the next RC is released, it should be possible to test it then to make sure.

**Comment by valadas** [comment] 2023-02-06 17:48
Correct, also I tried one of the "nightly build" and it appears to be fine...
![image](https://user-images.githubusercontent.com/6371568/217046441-9e93df91-0d18-44ef-bbc4-d05b21ff03d6.png)

We should get an RC2 out very soon, I'll re-close this issue but feel free to comment again if after that it is still a problem...

**Closed by valadas** 2023-02-06 17:48 UTC
Labels: Status: New

**Comment by valadas** [comment] 2023-02-06 18:49
@FRMN-FRE can you re-test this using RC2 from here https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.1-rc2
