### ISSUE TITLE
GoogleAnalytics Admin alert

### ISSUE THREAD

**Issue by AlwaysVbNet** [dnnsoftware/Dnn.Platform#2826] opened 2019-05-29 14:14 UTC
## Description of bug
After configured the GoogleAnalytics, I decided to remove/delete it. Since then, every time I reload a page I get many 'Admin Alerts' in the Admin logs.
Provide a clear and concise description of what the bug is.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Admin logs'
2. See error
3. Please note that the path below from the Admin log does not appear as it should:
FilePath:D:\home\site\wwwroot\Portals\0\\GoogleAnalytics.config
**`There are two forward slashes after Portals\0\\`**

Admin Alert
host 
 
```
Analytics.AnalyticsConfiguration GetConfig Failed FilePath D:\home\site\ww 
Analytics.AnalyticsConfiguration:GetConfig Failed

FilePath:D:\home\site\wwwroot\Portals\0\\GoogleAnalytics.config

ExceptionMessage:Object reference not set to an instance of an object.

Server Name: xyz
```

## Current result

Multiple admin alerts.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment] 2019-05-30 04:02
By delete you mean you have deleted the file?

If so, I would recommend restoring it and going to the Google Analytics connector and just remove the key and save. I know that without a key, the code is not injected but deleting the config file may not be supported.

**Comment by AlwaysVbNet** [comment] 2019-05-30 07:22
@valadas No, I meant delete the 'entry'. The .config file exists.

**Comment by valadas** [comment] 2019-05-30 23:47
Hmmm, I cannot reproduce on 9.3.2

**Comment by valadas** [comment] 2019-07-29 10:43
Can someone else reproduce this issue ?

**Comment by robheffo79** [comment] 2019-10-15 04:17
I am currently experiencing this issue in 9.4.0
The admin log is filling up with exactly the same error messages as described in the original report.

**Comment by marietteknap** [comment] 2019-10-20 06:24
I have this issue also in DNN 9.4.1

**Comment by tpperlman** [comment] 2019-11-05 21:53
Hi folks, I am experiencing this issue in v9.4.1 as well and it is filling up my event log and log4net. Is there any known work-around to temporarily fix this? I see DNN v9.4.2 RC1 is out, and if this is slated for a fix in v9.4.3 then that is quite a bit away. I haven't tried DNN v9.4.2 RC1 since it doesn't mention this issue as being addressed in it.

**Comment by valadas** [comment] 2019-11-08 03:34
@tpperlman the milestone is the minimum version where this could be fixed. Taking into account the number of open issues and the number of contributions, we cannot always get all issues resolved into the optimistic milestone where it could be fixed. When we have a decent amount of fixes, we publish a release and push the unresolved issues into the next milestone.

Now more specific to this issue, right now I cannot reproduce so there must be a little something missing to make it happen other than a clean install. If you have any details that can help reproduce the issue from a clean install until the problem surfaces, it would help making this issue actionable by a developer that picks it up.

**Comment by tpperlman** [comment] 2019-11-08 15:46
@valadas I totally understand and agree with how you folks handle releases. I was just wondering if anyone was aware of a "hack" or mitigation off hand to mitigate this since each page request results in a new event log  and log4net entry. This fills up FAST on busy sites. I don't want to have to disable logging for "Admin Alert" in the event log.

**Comment by tpperlman** [comment] 2019-11-08 15:49
As a fluke, I just re-connected the Google Analytics with a tracking code of "A", refreshed the page, then deleted the connection and now the errors seem to have gone away. I don't want to try this again to verify since I don't want to risk it coming back. Maybe this will help someone.

**Comment by valadas** [comment] 2019-11-09 22:57
So my guess is that something out of the ordinary happened and by re-enabling and re-disabling it, this is the workaround. I am closing the issue assuming this is the workaround to use, if there is anythin else actionable that can be done on the codebase, feel free to comment and I will re-open.

**Closed by valadas** 2019-11-09 22:57 UTC
Labels: bug

**Comment by moorecreative** [comment] 2020-06-18 01:52
My experience with this same issue was with an Evoq instance. This site was previously an 8x site that was updated to 9.3.0.

In this situation, there were two Google Analytics Connectors in the list of connectors (screenshot)
![image](https://user-images.githubusercontent.com/5497943/84967757-c0163600-b0e2-11ea-9d54-2a95ece0970d.png)

But looking at the Connectors within Extensions, they were two different ones and two different versions (screenshot)
![image](https://user-images.githubusercontent.com/5497943/84967780-d0c6ac00-b0e2-11ea-8542-a1147098e740.png)

Doing the steps mentioned above, about creating a connector with something like "A" as the Tracking ID and then deleting the connection did not work to address the problem (also, while the "A" value was present, both showed the same value, though only one allowed you to delete the connection). So, after deleting the connection, and still seeing the error log records, I decided to remove one of the connectors:

I removed the Evoq Google Analytics Connector because it was version 9.3.0 and the other was 9.3.1

After I removed the second one, I tried again the step of adding and removing the connector value of "A". After this second time, it worked as described and no new event log records were generated for it.
