### ISSUE TITLE
Persona bar shows for normal users with only "Pages" that shows enpty (9.4 specific)

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#3030] opened 2019-09-26 14:44 UTC
## Steps to reproduce
1. Login as a normal user

## Current result
Persona bar is showing for normal users, with only one option - Pages, and that shows empty with error on console.

## Expected result
Persona bar does not show

## Screenshots
![dnnissue](https://user-images.githubusercontent.com/26518879/65698467-711c0280-e074-11e9-83c6-491565f572b1.jpg)

## Error log
None on DNN logs.

## Affected version
* [ ] 9.4.0 latest supported release

## Affected browser
All.

**Comment by bdukes** [comment] 2019-09-26 14:59
Thanks for the report @eXistenZe.  I believe this is a duplicate of https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1163, which does have a fix in 9.4.1 (we should be publishing an RC build of 9.4.1 soon).  In the meantime, if you uninstall the old Persona Bar extensions (everything except Dnn.PersonaBar.Extensions, which will have the version 3.0.0), this should fix menu displaying incorrectly.  Hope it helps!

**Closed by bdukes** 2019-09-26 14:59 UTC

**Comment by eXistenZe** [comment] 2019-09-26 15:13
I deleted the extensions, but now I don't have the items in personna bar. Just extensions and assets.

**Comment by eXistenZe** [comment] 2019-09-27 09:50
Fixed in 9.4.1

**Comment by eXistenZe** [comment] 2019-10-18 13:33
I ask to reopen.
Upgraded from 9.3.2 to 9.4.1
Issue is not fixed, and deleting the 2.0.1 extensions causes the menus to disapear.

**Comment by eXistenZe** [comment] 2019-10-18 13:34
@bdukes

**Comment by valadas** [comment] 2019-10-18 17:24
@eXistenZe do you have errors in the /Portals/_default/logs insteller logs or normal logs at the date/time of the upgrade or shortly after ?

**Comment by eXistenZe** [comment] 2019-10-18 17:58
Not that I can see. The install has logs but.no.errors. Admin logs no
issues. Day.log.resources also nothing new.

But what's most important, how can I force install the persona bar items
after manually removing the old ones?

**Comment by valadas** [comment] 2019-10-18 19:04
You could extract each installer from the upgrade zip in /install/modules/ folder
Probably in this order:
Dnn.PersonaBar.UI_09.04.01_install.zip
Dnn.EditBar.UI_09.04.01_install.zip
Dnn.PersonaBar.Extensions.UI_09.04.01_install.zip

But then if the persona bar is not working, you cannot install them... Soo you could drop them in the install/module folder of the site and navigate to http://MYWEBSITE/install/install.aspx?mode=upgrade.

I think...

**Comment by eXistenZe** [comment] 2019-10-18 20:47
Removing the old ones and installing Extensions fixed it.
