### ISSUE TITLE
SEO display hidden pages default not working on Sitemap.aspx

### ISSUE THREAD

**Issue by euclid-mark** [dnnsoftware/Dnn.Platform#3959] opened 2020-08-05 18:14 UTC
## Description of bug
The SEO page has a default option to not include hidden pages in the SiteMap.aspx file. The default option of off is still including these hidden pages in the sitemap.aspx

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Fresh install of DNN
2. Go to SEO Site Map settings page to confirm that hidden pages should not be included
3. View the Sitemap.aspx page and review the XML file returned. Hidden pages like http://localhost/Activity-Feed are included in the sitemap.

## Expected behavior
If the default option to exclude hidden pages is checked, then these pages should not be shown in the Sitemap.aspx file.

## Screenshots
SEO page setting default
https://bfb30d4aa283201c8ae6-fa4f287ec88b082f34d8962c0b5f36f7.ssl.cf2.rackcdn.com/assets/SEO.png

Example Sitemap.aspx return
https://bfb30d4aa283201c8ae6-fa4f287ec88b082f34d8962c0b5f36f7.ssl.cf2.rackcdn.com/assets/sitemap.png

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x ] 09.07 RC
* [x ] 09.06.02

**Comment by jeremy-farrance** [comment] 2020-08-07 20:40
I have additional details on this that should help in debugging as well as provide a workaround. Since the workaround is easy, it is my very-humble opinion that this is minor and should not hold up the release of 9.07.00 (currently at RC2). These details/steps should make it fairly easy to devise a fix for this.
 
_I am editing this message Fri afternoon 3:30pm US Central Time, so expect revisions to this within the next hour or three..._

**In brief:** 

After an install, PortalSettings does not have the 5 records for SiteMap* settings. In this state, Clear Cache and the SiteMap generator do not do their job, you just get a default spew of the 6 or so initial pages.

The workaround is to go to Settings, SEO, Sitemap Settings tab, change any setting under GENERAL SITEMAP SETTINGS and Save (then change it back and hit Save again). This writes the 5 settings to the PortalSettings table and after that, you must go to Settings, Servers and Restart Application (and wait a few seconds). Then everything works as expected.  e.g. change a setting on a page (set Display in Menu to false), go to SiteMap Settings and Clear Cache, then reload SiteMap.aspx and you should see changes and all page (and SiteMap) settings respected in the output.

**Comment by euclid-mark** [comment] 2020-08-07 21:11
I have confirmed the work around solves the issue on my production and test installs.

**Comment by sjsports** [comment] 2020-11-20 23:55
This is still an issue.  Exists in 9.8.

**Comment by jeremy-farrance** [comment] 2020-11-26 17:44
This really should not be closed.

**Comment by valadas** [comment] 2020-11-26 18:03
I can confirm it's still an issue in 9.8.0

**Comment by mitchelsellers** [comment] 2020-11-27 15:47
I'll take this one, just wanting to confirm @jeremy-farrance that after doing the above of saving settings all is good, it is simply the missing values that are the issue?

**Closed** 2020-12-08 20:33 UTC
Labels: Status: New
