### ISSUE TITLE
SiteSettings and GetDefaultPagesSettings load infinitely if culturecode in PortalLocalization if en-us instead of en-US

### ISSUE THREAD

**Issue by ChrisHammond** [dnnsoftware/Dnn.Platform#3084] opened 2019-04-20 03:38 UTC
## Description of bug
Ran into a problem where my Site Settings and Site Behavior tab would load, and then repeatedly load over and over again, creating thousands of requests to ServicesFramework/GetPortalSettings and GetDefaultPagesSettings, if you left the browser open and persona bar on one of those tabs it will create thousands upon thousands of requests. In my case I have an install with 24 portal, 6 of them had this issue, the others did not. Issue is caused by en-us instead of en-US in the portallocalization table

## Steps to reproduce
List the steps to reproduce the behavior:
1. In PortalLocalization table, update the Culture code from en-US to en-us (why my portals are this way, unsure, but likely due to the site having been around for 10+ years)
2. Restart the app/clear the cache
3. Navigate to the Site Settings in persona bar for the portal in question
4. Open the network tab in dev tools and look at the continual requests.

## Current result
The site continually hits the web services to load site settings over and over again

## Expected result
Site settings should load only one time.

To prevent this, you can update the PortalLocalization table, but that requires updating database data that most people won't be familiar with.

I would think that something inside the platform should adjust for this instead.

Only have this issue on 9.3.1 at this time, but I'll keep an eye out on other sites/installs to see if that's the case in earlier versions.

**Comment by tpperlman** [comment] 2020-03-31 14:05
I just ran into this in an upgrade from DNN v7.x to DNN v9.4. Surprised that this wasn't included in one of the upgrade scripts in any of the releases in between.

**Comment by valadas** [comment] 2020-07-28 21:00
Looks like this was fixed somehow (made case insensitive) I cannot reproduce in 9.6.2 

closing this issue, if it will happens after upgrade, just comment and I will reopen

**Closed by valadas** 2020-07-28 21:00 UTC
Labels: Area: AE > PersonaBar Ext > SiteSettings.Web, Area: Localization, Effort: Low, Priority: Low, Status: Ready for Development, Type: Bug
