### ISSUE TITLE
cannot export modules 

### ISSUE THREAD

**Issue by erick1870** [dnnsoftware/Dnn.Platform#5894] opened 2023-12-22 23:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 cannot export html module to xml archive

### Steps to reproduce?

![soBAD](https://github.com/dnnsoftware/Dnn.Platform/assets/8868283/389e5239-64e5-4faa-ae3c-b639e58b3dfe)
1. in page setting go edit mode
2. in right corner of thml module press settings
3. click in export content
4. in new windows select folder where you will save the file
5. press in export bottom

### Current Behavior

An error occurred during the export.

### Expected Behavior

the file is saved in folder specify

### Relevant log output

```shell
An error occurred during the export.
```

### Anything else?

no

### Affected Versions

9.13.0 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichailBel** [comment] 2023-12-28 10:13
I have the same error. I cannot export any module. The error appeared after the last update (9.13.01)

**Comment by leedavi** [comment] 2024-01-04 02:22
I have the same issue.
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/5583141/a22be6c0-d055-4ae5-bbaa-5db7dcd58cba)

**Comment by erick1870** [comment] 2024-01-17 23:17
You still cannot export the modules

**Comment by jeremy-farrance** [comment] 2024-01-17 23:29
Possibly related to Issue #5879 ?

**Comment by david-poindexter** [comment] 2024-01-19 23:01
I too can confirm this issue.  I am not sure if this is related to #5929 or not, but it is probable considering the time this seems to have shown up.  CC @donker

**Comment by zyhfish** [comment] 2024-01-20 03:22
They are caused by the PermissionInfo.PermissionId property was marked as obsoleted in 9.13.1, which cause it's ignored in the xml serialized content.

**Closed** 2024-02-20 20:05 UTC
Labels: Status: New
