### ISSUE TITLE
9.4.1 RC adds "Beta version x" to pages' title

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#3038] opened 2019-09-28 10:55 UTC
## Description of bug
After updating to 9.4.1 my pages titles add "Beta version 9.4.1"

## Expected result
I know RC versions are not supposed to be used in live production, but it's still an undesired feature for me.

**Comment by thabaum** [comment] 2019-09-28 19:22
There was a switch that when using a beta version you could turn off the display beta message.  I would expect it to be here:
![image](https://user-images.githubusercontent.com/13577556/65821454-97fc4500-e1ea-11e9-95e3-2311aed8cc09.png)

**Comment by eXistenZe** [comment] 2019-09-29 14:46
Solved. Thanks.

**Comment by valadas** [comment] 2019-10-02 05:56
This is by design to prevent running beta versions in production so it would make no sense to have a UI for it or remove the behaviour and there is an easy way for a developer to override. Closing for those reasons.

**Closed by valadas** 2019-10-02 05:56 UTC

**Comment by eXistenZe** [comment] 2019-10-02 07:34
@valadas Sometimes there is actually a major need to upgrade to beta.
I have an almost serious website I upgraded to 9.4. Since it had a nasty issue showing the persona bar to normal users I was "forced" to upgrade to beta 9.4.1 (reverting to 9.3.2 would take quite a while for me).

While I understand DNN is mostly for serious web developers, sometimes normal people try their luck with this (and it's been an amazing exp).

So, if devs or non-devs install a beta version, they already know they did so. The reminder on the page title doesn't seem to add critical info.

**Comment by valadas** [comment] 2019-10-03 22:08
I believe the risks of running beta in production outweight the need for an easy way to do it in a UI. And we have a very active community to help less technical people do such things in those rare occasions, we are also now much better tooled to produce very quick releases like what happened between the 9.4.0 issues where known and 9.4.1 got released.
