### ISSUE TITLE
Incorrect instruction on adding multiple pages in 1 go

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#3718] opened 2020-05-01 13:54 UTC
## Description of bug
Encoding of instruction for ">" in title textbox add multiple pages

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Pages'...'
2. Click on 'Add multiple pages.'
3. See instruction

## Current behavior
(nl-NL): **Een pagina per regel, voorafgaand met "&gt;"om hierarchie te creeeren**

## Expected behavior
**Eén pagina per regel, voorafgaand met ">"om hiërarchie te creëren**

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/80810328-e3813200-8bc3-11ea-9093-5cbb12d01692.png)

## Error information
-

## Additional context
-
## Affected version

* [x] 9.6.0 

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by valadas** [comment] 2020-05-04 03:26
@EPTamminga I think this can be now a PR on the language pack itself and I will close this issue, if the issue is not with the language pack, feel free to comment with more details and I will reopen.

**Closed by valadas** 2020-05-04 03:26 UTC
Labels: Status: New

**Comment by EPTamminga** [comment] 2020-05-04 07:46
Can I move the issue to the LP repo?
