### ISSUE TITLE
Send An email to new user is not working

### ISSUE THREAD

**Issue by Icidis** [dnnsoftware/Dnn.Platform#2424] opened 2018-10-24 09:00 UTC
## Description of bug
When creating a new user account as a SuperUser/Admin and checking the "Send An Email To New User." checkbox, no email is sent to the email I specify.

Once the user is created, sending password reset links, etc. work fine. Emails are sent and received correctly so it appears the SMTP settings are correct.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Manage Users'
2. Click on 'Add User'
3. Fill in user details
4. Check the "Send An Email To New User" checkbox
5. Click "Save"

## Current result
The user is created successfully but no email is send to the user.

## Expected result
User gets created and registration email is sent to the users' email address.

## Additional context
SMTP is configured to use SendGrid smtp but password reset etc do work without any issues.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment] 2018-10-24 09:19
Which registration type ate you using - public, verified or private?

**Comment by Icidis** [comment] 2018-10-24 09:41
Hi Sebastian (@sleupold),

The "User Registration" setting is set to "None"

**Comment by Tychodewaard** [comment] 2018-10-24 10:11
I have a customer who has 'verified' as user registration with the same issue.

**Comment by sleupold** [comment] 2018-10-24 10:39
AFAIR there has been already a PR merged in this area, I am not sure, whether it fixes this issue as well. It would be great if anyone could test it in a nightly build.

**Comment by Icidis** [comment] 2018-10-24 11:51
I've upgraded the site from version 9.2.2 to the Nightly Build [9.3.0-alpha.31](https://dotnet.visualstudio.com/DNN/_build/results?buildId=6055&view=results) and the same issue persists.

**Comment by jacques-hoventer** [comment] 2018-11-19 12:11
Is there any known workaround for this?

**Comment by mikebigun** [comment] 2018-11-26 16:37
Dear community, 

Email notification is not handled for the User Registration `None` type. Initially, if `None` is set, we shouldn't allow anyone to create users. 
Nevertheless, I found property `IgnoreRegistrationMode` which overwrites above logic and makes us ALWAYS possible to create new users. See below:

https://github.com/dnnsoftware/Dnn.AdminExperience/blob/95513df2b8440bc0d37316545d6dd327a3f30506/Extensions/Manage/Dnn.PersonaBar.Users/Components/Contracts/RegisterationDetails.cs#L41

This property was introduced within https://dnntracker.atlassian.net/browse/SOCIAL-3158 Unfortunately, do not have access to check what is it about.

The default value of this property is hardcoded and is `true`. It is not cumming from UI so it is not configurable. With this property, it is senseless to use `None` registration mode.

https://github.com/dnnsoftware/Dnn.AdminExperience/blob/95513df2b8440bc0d37316545d6dd327a3f30506/Extensions/Manage/Dnn.PersonaBar.Users/Services/UsersController.cs#L81

To fix this issue we should either disallow user registration when mode is `None` (so the issue will gone) or add missing functionality to send welcome email for the newly created user.

Please, share your thoughts.

**Comment by sleupold** [comment] 2018-11-26 16:54
Mike,
registration type "None" does not mean, no-one can create a user account, but there is no "register" option for self registration on the site. Superusers and Site Admins are always allowed to manage site accounts. This is DNN behavior since DNN 1 and should not be changed IMO. 
I have no clue, what DNN Social is overriding, maybe an integration with another event like buying a product, which offers to create (or auto-creates) a user account for the product social site (just a guess)

**Comment by mikebigun** [comment] 2018-11-26 17:14
@sleupold thanks for explanation. 
Just confused a bit. When admin is creating new user, `UserController -> CreateUser->RegisterController.Instance.Register` is invoked.
Inside `Register` there is list of registration types for which email is going to be sent.

https://github.com/dnnsoftware/Dnn.AdminExperience/blob/95513df2b8440bc0d37316545d6dd327a3f30506/Extensions/Manage/Dnn.PersonaBar.Users/Components/RegisterController.cs#L272

So` Private/Public/Verified` types are handled. `None` is not there, so email sending is ignored.

**Comment by sleupold** [comment] 2018-11-26 17:50
@mikebigun ,
I'd like to describe, what should happen:
- if a user clicks register and registration is set to "public", he is granted access immediately and gets an email sent with site name, URL and login for reference. The site admin(s) might get a notification about the new user.
- if a user clicks register and registration is set to "verified", the user gets limited access (unverified user) and an email with a confirmation link, he needs to click to gain full access. the site admin(s) gets a notification about the new user.
- if a user clicks register and registration is set to "private", the user gets an email confirming his registration and the info, the admin has been notified. The site admin(s) gets a notification about the user awaiting registration
- if an admin creates a user account (any registration mode), the user gets an email about his new account with site name, site URL, user name and an option to obtain his password.

**Comment by sleupold** [comment] 2018-11-26 22:17
@mikebigun 
I don't know the reason, maybe the code for PB has been inspired by wrong source code part of DNN 8 - just a guess.

**Comment by jacques-hoventer** [comment] 2018-11-27 06:49
I agree with @sleupold fourth point which is not happening at the moment. One thing I would add though is that when an administrator creates a user it should be a choice whether or not to send the user an email, but the default should be to send the user an email.

**Comment by jacques-hoventer** [comment] 2018-11-27 08:30
@Icidis apologies, I reread your post and realized that's what it was about.

**Comment by Icidis** [comment] 2018-11-27 10:30
After reviewing the flow of the user creation from user admin. I found the following.

There is an event "**UserCreated**" which could be updated to include the below code

`Mail.SendMail(args.User, MessageType.UserRegistrationPublic, PortalSettings.Current);`

but of course you don't know which template/message type to use when sending the email.

[https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Entities/Users/UserEventHandlers.cs#L39](https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Entities/Users/UserEventHandlers.cs#L39)

**Better solution:**
I would say the code change should be done here:

[https://github.com/dnnsoftware/Dnn.AdminExperience/blob/95513df2b8440bc0d37316545d6dd327a3f30506/Extensions/Manage/Dnn.PersonaBar.Users/Components/RegisterController.cs#L272](https://github.com/dnnsoftware/Dnn.AdminExperience/blob/95513df2b8440bc0d37316545d6dd327a3f30506/Extensions/Manage/Dnn.PersonaBar.Users/Components/RegisterController.cs#L272)

as described by @mikebigun .

I'll create an issue and pull request on that repo for review.

**Comment by sleupold** [comment] 2018-11-27 10:41
IMO we should fix it in the API, not in the UI, which is not accessed by 3rd party extensions.
We may need to extend the method with additional parameters, if necessary.

**Comment by Icidis** [comment] 2018-11-27 10:57
Changing it in the API would be the best solution. But I would imagine that would take some time to discuss with all the relevant parties including the changes to the API 

I would be happy with the change in the UI now as the email notifications sit there already and then later change to a more appropriate solution.

**Comment by mikebigun** [comment] 2018-11-27 11:32
I would appreciate it if there is a chance to fix it in the current implementation. The issue reported exactly for the persona bar and considered as a bug. It is expected to be fixed asap.
Moving to API changes will require long discussion involving all API consumers. I agree, this is certainly right direction for the further improvements, still we need to make correction for the existing part.

**Closed** 2018-12-19 14:17 UTC

**Comment by Icidis** [comment] 2019-01-23 14:08
Can we re-open this issue? 

Just tested using the 9.3.0 9018 build as per below.

[https://dotnet.visualstudio.com/DNN/_build/results?buildId=9018](https://dotnet.visualstudio.com/DNN/_build/results?buildId=9018)

The code changed still relies on the PersonaBar to pass in the sendEmailNotification.

**Here seems to be the flow:**

**PersonaBar (Dnn.AdminExperience)**

1. [Some Javascript calls this function but I don't see anything about notifying a user](https://github.com/dnnsoftware/Dnn.AdminExperience/blob/54726ab2a931c65f5e0169bb64d29e0260522e6d/Extensions/Manage/Dnn.PersonaBar.Users/Services/UsersController.cs#L83)
2. [RegisterController.Register](https://github.com/dnnsoftware/Dnn.AdminExperience/blob/54726ab2a931c65f5e0169bb64d29e0260522e6d/Extensions/Manage/Dnn.PersonaBar.Users/Components/RegisterController.cs#L243) Shouldn't this line be `var createStatus = UserController.CreateUser(ref newUser, registerationDetails.Notify);`

**DNN.Platform**

3. [UserController.CreateUser](https://github.com/dnnsoftware/Dnn.Platform/blob/8321bdab6d9854a4417321f07532e8c414e8b7a3/DNN%20Platform/Library/Entities/Users/UserController.cs#L966) - sendEmailNotification parameter is false
4. [UserController.CreateUser](https://github.com/dnnsoftware/Dnn.Platform/blob/8321bdab6d9854a4417321f07532e8c414e8b7a3/DNN%20Platform/Library/Entities/Users/UserController.cs#L993) - EventManager.Instance.OnUserCreated is called.
5.  [UserEventHandlers.UserCreated](https://github.com/dnnsoftware/Dnn.Platform/blob/8321bdab6d9854a4417321f07532e8c414e8b7a3/DNN%20Platform/Library/Entities/Users/UserEventHandlers.cs#L41) Gets called and the UserEventArgs.SendNotification = false

After all this, the new UserRegistrationEmailNotifier.NotifyUser is never called. Am I missing something, can anyone reproduce this?

Also why is the PersonaBar (Dnn.AdminExperience) still doing the SendMail when we have this new service to handle all of this?

**Comment by Icidis** [comment] 2019-01-23 14:16
@sleupold @bdukes  @mikebigun  Do I need to open a new issue or by adding a new comment re-opens this issue?

**Comment by sleupold** [comment] 2019-01-23 14:51
@bdukes 
IMO it should be re-opened

**Comment by valadas** [comment] 2019-01-25 05:05
Ok, so my review was correct, the UI was just not updated to reflect the changes on #2492 

As per https://www.dnnsoftware.com/wiki/registration-types/page the behaviour of none is correct, users cannot register themselves but admins can, and they should be able to notify the user if they so want. So I opened https://github.com/dnnsoftware/Dnn.AdminExperience/issues/363 to handle that second part of the fix. Will be submitting a PR for that shortly.

**Comment by markandcurry** [comment] 2019-07-09 17:26
Hi has this issue been fixed?

**Comment by valadas** [comment] 2019-07-10 20:27
As far as I can tell, this should be resolved in 9.3.1, if you can still reproduce after 9.3.1 @markandcurry please create a new issue with the version number affected. Thanks.
