### ISSUE TITLE
[Bug]: Resource manager is not showing "Copy Url" option

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#5725] opened 2023-07-07 18:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I just installed a new site with version 9.11.02 but "Copy Url" option is not available in this version. i have tried to update to 9.12 version but still is not available that option.

### Steps to reproduce?

Go to Local Resources to show Resources Manager module.
Just pick some file (image or document), and in tool bar "copy url" option is not available
If you right click in some file option is not available in context menu either.

### Current Behavior

Resource Manager don´t allow to "Copy Url" for any file

### Affected Versions

9.12.0 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremy-farrance** [comment] 2023-07-07 23:10
I just tried this on v9.12.00 and it works as expected. Below is the screenshot immediately after right-clicking on the file.

Are you logged in a Super or Admin or using some other combination of Roles + module permissions?

What browser? I used Chrome (latest).

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/653301/9f848825-2d19-4bb5-b9a2-0e3ac35d64fa)

**Comment by valadas** [comment] 2023-07-09 00:58
@ufoloko it works on a clean and upgraded instance for me too.
Now the clipboard API only works with https, is it possible the site is not using https in you case...

I will close the issue assuming that is the case but happy to reopen if you find out it is still an issue with https....

**Closed by valadas** 2023-07-09 00:58 UTC
Labels: Status: New

**Comment by ufoloko** [comment] 2023-07-10 14:23
Thanks Valadas, Effectivelly is needed https to show "Copy Url", i have enabled for the site and now is enabled.

Thanks for the response

**Comment by jeremy-farrance** [comment] 2023-07-10 16:12
Sorry, but having a feature that doesn't work when not HTTPS only because of a dependency... needs some thought. Its a can of worms, no?

Is that fact that the "Clipboard API only works with HTTPS" a bug or by design? If it is by design, then - if DNN should be allowed to run in non-HTTPS situations - this is a problem that needs a solution. 
 
Am I missing stuff or out of context?

**Comment by bdukes** [comment] 2023-07-10 16:19
This limitation is by design. As you can see in [the MDN docs for the Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API), it requires a "Secure Context". I think the best approach would be to show an error or remove that button if we determine that it's not available.

**Comment by valadas** [comment] 2023-07-10 17:38
The button is only shown when over https, so I'd say everything is by design as it stands...

**Comment by mitchelsellers** [comment] 2023-07-10 17:38
@jeremy-farrance there has been serious discussions in the past that ALL DNN at all time should be HTTPS only, so I don't believe it is really a limitation.  You SHOULD NOT be running DNN on a non-HTTP location

**Comment by jeremy-farrance** [comment] 2023-07-10 20:50
Agreed, I don't and no one should. I definitely want to see DNN be HTTPS-only. I hope that is closer than I realize to being a reality! Cheers!!
