### ISSUE TITLE
HTML Editor Manager error 404 resource not found

### ISSUE THREAD

**Issue by Scippy** [dnnsoftware/Dnn.Platform#3816] opened 2020-06-06 11:30 UTC
On latest DNN 9.6.1 is no more possible to open HTML Editor Manager
1. Go to Site Settings
2. Site Behavior
2. More
3. Open HTML Editor Manager

Then I receive an 404 resource not found

![Screenshot_4](https://user-images.githubusercontent.com/16607338/83943132-cd394800-a7f9-11ea-8cef-7adade46b50f.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/16607338/83943133-d0cccf00-a7f9-11ea-8feb-795036d39a25.jpg)

**Comment by sleupold** [comment] 2020-06-06 11:46
I can't confirm on a new install of DNN 961.
- Is your site a new or upgraded install? 
- did you install in root of the IIS website?
- are you running http or https?

**Comment by Scippy** [comment] 2020-06-06 12:30
- It’s upgrade from DDN 960 install
- It’s on the root of appPool of that dnn installation
- http

**Comment by valadas** [comment] 2020-06-09 00:30
Can you look if you have any errors in the site log or in the log files at /Portals/_default/logs maybe there would be some clues in there.

**Comment by valadas** [comment] 2020-07-29 01:20
Closing this issue as we cannot reproduce and there was no news for more than a month. If you have any other details please comment again and I will be glad to reopen.

**Closed by valadas** 2020-07-29 01:20 UTC
Labels: Status: New

**Comment by Scippy** [comment] 2020-08-06 07:44
Sorry for delay, but the issue is still there. I've also upgraded to latest 9.6.2
I've monitored the ethernet request and I can see that the request is made with portalid=undefined
![Screenshot_2](https://user-images.githubusercontent.com/16607338/89504913-13defa80-d7c9-11ea-8103-d55c2008ca95.jpg)
I always personalize portal directory (Portals/[PortalID]) with (Portals/myportalname) could this be the problem?

**Comment by Scippy** [comment] 2020-08-06 15:19
I understand where the problem comes from. I use in my DNN installation [Open Url Rewriter module](https://github.com/sachatrauwaen/OpenUrlRewriter) and with latest DNN release it generates this problem but everything else seems to be working fine.
It would be a big problem for me if i could not use this module anymore, but i don't think it is a problem that DNN has to solve

**Comment by suvarnaashoka** [comment] 2024-01-04 12:21
@Scippy Can we know about the solution that works for you?
