### ISSUE TITLE
Unable to Select "Home" page under Page settings 9.4 RC1

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2965] opened 2019-09-01 21:58 UTC
![image](https://user-images.githubusercontent.com/13577556/64082728-8d708d80-ccc8-11e9-86bf-9d50430f6b75.png)

## Description of bug
Unable to select Home page for page settings

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to edit pencil, click on page settings
![image](https://user-images.githubusercontent.com/13577556/64082739-bd1f9580-ccc8-11e9-851f-6605968a3bac.png)

2. Click on 'Home'
3. Unable to select to modify or view page settings for Home

## Current result
Unable to select to modify or view page settings for Home

## Expected result
Ability to edit and view home page settings

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x ] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

## Affected browser

* [ ] Chrome
* [x ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment] 2019-09-10 18:40
I was not able to reproduce, can anyone else reproduce this?

@thabaum was this a clean install or an upgrade and if so from which version?

**Comment by thabaum** [comment] 2019-09-18 16:02
9.4rc1 upgrade from previous 9.3.2 version that is a fresh install from a 9.2 or 9.3 version

**Comment by thabaum** [comment] 2019-09-18 16:20
and this screenshot shows what I mean about how they appear in random places on the screen... looks buggy.

**Comment by brewadmin** [comment] 2019-09-19 08:32
I can confirm that I also had this problem. 
Upgraded from DNN9.2.2 to 9.4 and was unable to edit current page settings.
Have to navigate to another page and then edit the page I want to edit within page manager.

**Comment by david-poindexter** [comment] 2019-10-27 00:07
I am pretty sure this issue was pre 09.04.01.  I have been unable to reproduce in 9.4.1 on a clean install or an upgraded instance.  However, I did experience this on 9.4.0.  @thabaum and @brewadmin can you confirm this issue does not exist on 9.4.1?  Thanks!

**Comment by brewadmin** [comment] 2019-10-27 06:08
Hi David

 

I can confirm that I have tested this in 9.4.1 and the issue is now resolved in the upgrade.

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za/> www.itm.co.za

**Comment by david-poindexter** [comment] 2019-10-27 12:41
Excellent @brewadmin - we’ll go ahead and close this issue.  Thanks!

**Closed by david-poindexter** 2019-10-27 12:41 UTC
Labels: Pending Verification
