### ISSUE TITLE
File suffix with Resource Manager in 9.8.0

### ISSUE THREAD

**Issue by simont1952** [dnnsoftware/Dnn.Platform#4338] opened 2020-11-27 11:16 UTC
I am populating a brand new install of 9.8.0 with the Telerik components removed.

I needed to upload a number of images from my client of various sorts (png and jpg). THe filenames had extensions mostly in lower case but 3 images were labelled with .JPG. The Resource Manager refused to upload these.

I went to the allowed file types and added JPG as one of these and retried - again the file were rejected.

Finally I change the filenames extensions to lowercase jpg and the files were accepted and uploaded with no problem.

I am attaching two versions of one of these files in both variants to see if others have this issue.
![SettingOut3](https://user-images.githubusercontent.com/56356029/100443581-df59bc00-30a1-11eb-8fa6-3c32b7408949.jpg)
![SettingOut3](https://user-images.githubusercontent.com/56356029/100443620-f26c8c00-30a1-11eb-85f5-c3c06516659e.JPG)

**Comment by jeremy-farrance** [comment] 2020-11-27 16:05
Upper case file name extensions are so very, very, very wrong. Can we call this a feature?

**Comment by simont1952** [comment] 2020-11-27 16:11
I do agree with the sentiment. It is just what came from the client.

If most people agree it should stay as it is then I am good with that. Perhaps this should be more widely known. Maybe it is expect for me.

Regards

Simon Thompson

**Comment by jeremy-farrance** [comment] 2020-11-27 16:14
Yeah, sorry, I was being glib. In the real world my mild OCD doesn't matter, technically extensions can be upper case. An option in the file manager to auto-lower-case them on upload would be nice, but again, my mild OCD. 
 
IMHO, by default, the resource manager should allow upper case extensions.

**Comment by simont1952** [comment] 2020-11-27 16:23
Jeremy, I would agree with your suggestion as a fellow mild “CDO” sufferer.

Simon Thompson

**Comment by david-poindexter** [comment] 2020-11-27 16:40
Thanks for reporting this.  Hopefully, it's a simple fix.  I'll take a look into this as soon as I have some available time to do so.

**Comment by jeremy-farrance** [comment] 2020-11-27 17:58
@simont1952, thank you for putting the letters in order. Much appreciated!!

**Comment by david-poindexter** [comment] 2022-05-01 18:20
@simont1952 I finally got a chance to look into this further and it appears the issue is not in the Resource Manager module, but rather in the DNN internal service that it uses.  I was not able to pinpoint the exact issue before running out of time.

That said, there is a serious effort going on to replace this solution altogether with a new file manager.  So, I really don't want to spend too much time on tracking this one down when it is going to be replaced soon anyway.

**Comment by mitchelsellers** [comment] 2022-05-01 19:19
@david-poindexter This issue is WITH the new file manager, so we need to make sure that we validate that this goes away with the work-in-progress updates

**Comment by valadas** [comment] 2022-05-02 16:39
I took note to remind if of that in the new one.

**Comment by david-poindexter** [comment] 2022-08-29 04:26
@simont1952 @jeremy-farrance @mitchelsellers - @valadas and I have verified this is working correctly in the new Resource Manager (to be included in the 9.11.0 release of DNN).  We'll go ahead and close this issue, but we recommend testing this in the forthcoming release candidate.  If you still experience issues, please respond to this issue and we'll happily reopen it.  Thanks!

**Comment by valadas** [comment] 2023-01-24 19:30
Apparently this is still an issue in 9.11.0

**Closed** 2023-01-29 04:37 UTC
Labels: Type: Bug, Effort: Low, Priority: Medium, Status: Ready for Development
