### ISSUE TITLE
Resource manager absent in new sites

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4645] opened 2021-05-03 08:13 UTC
## Description of bug
If you add a new site to a DNN, the resource manager is not present on the page site assets

## Steps to reproduce
- replace the Digital asset manager for Resource manager acccording to steps as explained on Github
- create a new site
- go to site assets in Persona bar.

**Comment by valadas** [comment] 2021-05-03 11:57
Yeah, never thought about this case. Don't quote me on this, but I think it may be something to fix in the site templates...

That being said, it opens up a bit of a can of worms and I am not 100% sure we can fix this before DNN 10. The thing is we cannot know from a template if the site was or was not de-teleriked ...

I have triaged the issue except for the milestone part... I am not sure if until DNN10 we just document this as part of the Telerik removal instructions maybe ?

**Comment by david-poindexter** [comment] 2021-05-03 13:53
I think this is the expected behavior at this point since Telerik removal is still optional.

**Comment by valadas** [comment] 2021-05-03 14:14
We must not forget for DNN10 though, I will assign this to `10.0.0` instead of the usual `major` milestone for that reason...

**Comment by bdukes** [comment] 2021-05-03 14:16
Can we update the built-in site templates to reference both the old and new module, and whichever is installed will be used?

**Comment by david-poindexter** [comment] 2021-05-03 14:16
Agreed - thanks @valadas

**Comment by valadas** [comment] 2021-05-03 14:41
> Can we update the built-in site templates to reference both the old and new module, and whichever is installed will be used?

I guess so assuming it does not fail on a module that is not installed...

**Comment by valadas** [comment] 2022-10-23 02:45
Fixed in #5194 and released in v9.11.0

**Closed by valadas** 2022-10-23 02:45 UTC
Labels: Type: Bug, Area: Platform > Modules, Effort: Low, Priority: High, Status: Ready for Development
