### ISSUE TITLE
Post DNN Upgrade Admin pages Not visible in Persona Bar

### ISSUE THREAD

**Issue by iMercerTalentTeam** [dnnsoftware/Dnn.Platform#2091] opened 2018-06-04 09:08 UTC
Hi,

Post DNN Upgrade Admin pages are not visible.  Pre Upgrade users with Administrator rights were able to view and use pages like Users, Roles, Event Viewer.

Now Admin Users are not able to view any page. Attached is an example of an Admin Users Persona Bar menu.

Please can you let us know if we are missing any setting.

![admin_menus](https://user-images.githubusercontent.com/39306544/40908611-e70ca7e0-6804-11e8-8604-9b4b3a380793.jpg)

**Comment by bdukes** [comment] 2018-06-04 13:42
Can you clarify the version of DNN that you upgraded from and to?

I would start by looking at the `PersonaBarMenuPermission` table, and see if there are permissions missing in the site for the Administrators role.

**Comment by thenotandy** [comment] 2018-06-07 13:12
I had the same issue and ended up copying and modifying rows from another DNN install. It was a painfully manual process. I think it had to do with the upgraded site having a custom entry on the persona bar.

**Comment by sleupold** [comment] 2018-06-12 09:16
IMO the module installer needs to be enhanced to include the new admin or host page in PersonaBar automatically.

**Comment by valadas** [comment] 2019-07-27 06:13
I am closing this issue since it is a year old and cannot be reproduced in current Dnn version. @iMercerTalentTeam if this is still an issue for your specific installation I would recommend using the forums at https://dnncommunity.org/forums for a possible workaround this issue.

**Closed by valadas** 2019-07-27 06:13 UTC
Labels: bug
