### ISSUE TITLE
Resource Manager Scroll Bug

### ISSUE THREAD

**Issue by HeileneMartin** [dnnsoftware/Dnn.Platform#4718] opened 2021-06-23 02:45 UTC
## Description of the bug
Unable to scroll to the bottom of the Site Assets page with the Resource Manager module when the page first opens. 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Manage > Site Assets'
2. Start scrolling

## Current behavior
When a user opens the Site Assets page with the Resource Manager and starts scrolling, the page keeps jumping to the top of the resource items if there are more than 4 rows of items. After all the items are loaded, you can then scroll up and down the page. 

## Expected behavior
When a user opens the Site Assets page with the Resource Manager module, they are able to scroll up and down the entire page. 

## Screenshots

https://user-images.githubusercontent.com/71242249/123026753-cdba7600-d430-11eb-96f1-4fd162d62079.mp4

## Additional context
It could be that not all the resource items are loaded into the page when the page first opens, so when you hit the scroll bar it loading the additional rows and jumps to the top of the list. The scrolling starts working as soon as all the items are loaded. 

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.09.00 latest supported release
* [X] 09.08.01

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by HeileneMartin** [comment] 2021-06-23 02:54
https://github.com/dnnsoftware/Dnn.Platform/issues/4611
https://github.com/dnnsoftware/Dnn.Platform/issues/4612
https://github.com/dnnsoftware/Dnn.Platform/issues/4613

**Comment by david-poindexter** [comment] 2021-07-20 22:40
@HeileneMartin thank you for reporting this.  I am unable to reproduce and my suspicion is this is caused by the theme being used on the site.  Can you try switching to Xcillion on the Site Assets page and confirm the issue does (or does not exist).  I have seen many commercial and custom themes leverage scroll-jacking scripts that can sometimes not play well with other components on the page.  😉

**Comment by HeileneMartin** [comment] 2021-07-20 22:53
@david-poindexter I've tested it with the Xcillion theme and I can't replicate the issue anymore. I can confirm it's related to the theme and will follow up with the theme provider. Thanks for looking at this :)

**Comment by david-poindexter** [comment] 2021-07-21 00:06
Thanks @HeileneMartin - we'll go ahead and close this issue.

**Closed by david-poindexter** 2021-07-21 00:06 UTC
Labels: Status: New
