### ISSUE TITLE
Chrome Mobile / ERR_TOO_MANY_REDIRECTS / Wrong Portal Alias Requested

### ISSUE THREAD

**Issue by tpperlman** [dnnsoftware/Dnn.Platform#4148] opened 2020-10-05 17:09 UTC
## Description of bug
I am having a problem with the error "X-Redirect-Reason: Wrong Portal Alias Requested" happening only in Chrome when the browser type is mobile on one installation.

The primary domain is set to the same in the PortalSettings and PortalAlias table with the mapping mode set to Canonical. Each alias has a browser type of Normal. I have tried some suggestions in other issues by re-ordering the aliases in the PortalAlias table and that has had no affect. It appears that when the browser is mobile then DNN isn't pulling up the proper alias and returns the error "X-Redirect-Reason: Wrong Portal Alias Requested".

I am not sure if it makes any difference, but the DNN installation was originally built on 09.01.00 and over time has been upgraded to 09.06.02.

## Current behavior
When the browser type is mobile, then the primary domain alias isn't loading properly and results in an endless loop of 301 redirects.

## Expected behavior
The mobile browser should load the primary domain alias.

## Screenshots

![PortalAlias](https://user-images.githubusercontent.com/1871915/95110806-983bf400-070c-11eb-9ca5-2a7eaa97bfea.jpg)

![PortalAlias2](https://user-images.githubusercontent.com/1871915/95110982-d6d1ae80-070c-11eb-97d8-1a276d7f6674.jpg)

## Affected version
* [X] 09.06.02 production release

## Affected browser
* [X] Chrome (mobile browser agent)
* [X] Microsoft Edge Chromium (mobile browser agent)

**Comment by valadas** [comment] 2020-10-06 17:13
@tpperlman unfortunatelly this is not something easy to reproduce accurately as reported, I will be closing this issue in favor of the ongoing discussion here https://github.com/dnnsoftware/Dnn.Platform/discussions/4137 Please try the suggestion there if it applies to your situation and well until we have something clear a developer can make happen, let's keep it as a discussion instead of an issue because this is not something we can fix until we can make it happen. Thanks.

**Closed by valadas** 2020-10-06 17:13 UTC
Labels: Status: New
