### ISSUE TITLE
Links always have the default language in url. 

### ISSUE THREAD

**Issue by mhessmann** [dnnsoftware/Dnn.Platform#2778] opened 2019-05-13 09:03 UTC
## Description of bug
After Updating to Evoq 3.1.0 all links has the default language in the url.
In our environment we have Deutsch(de-de) and English (en-gb) as languages configured.

Site Default: English (en-gb)
Enable Language Parameter in URLs: On
Enable Browser Language Detection: Off
Users May Choose Interface Language: Off
Allow Content Localization: Off

Example: Am I on a german page an whant to edit an OpenContent Module,
but the link to the editMode includes the en-GB parameter.
So I have no chance to edit german (de-DE) content.

I found the following commit in the last release, and I think this could be the reason.
https://github.com/dnnsoftware/Dnn.Platform/pull/2607/commits

## Affected version
* [x] 9.3.1

**Comment by sleupold** [comment] 2019-05-13 09:10
How do your website aliases look like?
There should be a primary alias without a language specified **and** one primary alias per language.

**Comment by mhessmann** [comment] 2019-05-13 09:16
> 
> 
> How do your website aliases look like?
> There should be a primary alias without a language specified **and** one primary alias per language.

Hi Sebastian, can you give me an example for an alias. I am not sure what you mean.

**Comment by mhessmann** [comment] 2019-05-13 09:20
![language_issue](https://user-images.githubusercontent.com/50398956/57610392-06f53c00-7571-11e9-8d94-2d5e8039d6f4.JPG)

**Comment by sleupold** [comment] 2019-05-13 09:27
Marc, please check PersonaBar > Website-Einstellungen > Website-Aliase

**Comment by mhessmann** [comment] 2019-05-13 09:31
![grafik](https://user-images.githubusercontent.com/50398956/57611216-9f3ff080-7572-11e9-82bf-e0b2b8af22af.png)

**Comment by sleupold** [comment] 2019-05-13 09:51
Marc,
please make sure, there is only ONE Primary Site Alias per language and one without language!

**Comment by mhessmann** [comment] 2019-05-13 09:56
I tried that, without success.

**Comment by sleupold** [comment] 2019-05-13 10:07
the problem is the language param in the URL. is the wrong language already in the URL before you try to edit the content?

**Comment by mhessmann** [comment] 2019-05-13 10:13
please have a look at my first screenshot.
This probelm starts aftert updating to 9.3.0.
And I think this commit is the reason for our problem.
https://github.com/dnnsoftware/Dnn.Platform/pull/2607/commits

**Comment by mhessmann** [comment] 2019-05-13 10:21
For building the URL`S this function is used:
https://github.com/dnnsoftware/Dnn.Platform/blob/74e86eaf61179895cc298a324ce6a4fe3dc24cba/DNN%20Platform/Library/Common/Globals.cs#L2915

which is using the changed function:
https://github.com/dnnsoftware/Dnn.Platform/pull/2607/commits/c0c1300b7556f326b8b9ee4828db7e83b325b981#diff-f8c2cca1f9fcc26f9a7274ab02f96e4dL802

**Comment by sleupold** [comment] 2019-05-13 10:27
th problem is  the wrong language being passed, but as far as I can see, #2607 tries to avoid this in a different scenario though. The question would be in NavigateURL: is linkTab Null or Linktab.CultureCode? If this method is called for the javascript, this is missing a language and CultureCode should be used from thread.

**Comment by zyhfish** [comment] 2019-05-13 11:16
Hi @mhessmann , this looks like has no relation to #2607, is it possible that let me take a look at your site and try to find out the root cause? thx

**Comment by mhessmann** [comment] 2019-05-20 14:39
Hi @zyhfish , the problem can be reproduced with a newly installed version DNN_Platform_9.3.2.24. Add a second language after the installation and check the links.
![dnn_language_bug](https://user-images.githubusercontent.com/50398956/58029906-dc315780-7b1d-11e9-82aa-fd2545ea67ae.gif)

**Comment by daguiler** [comment] 2019-05-20 21:02
This happens when you have not yet localized any pages. Try disabling `Enable Language Parameter in URLs`. Turning this switch off fixed it for me.

**Comment by donker** [comment] 2019-05-21 14:59
I can confirm the observed behaviour. And having traced through the code there is something pretty strange that happens.

Globals line 3017: in NavigateURL in the absence of a required locale, the method looks up the locale that is set on the tab. 

Then in Globals line 810 in GetCultureCode an attempt is made to find the tab and get its locale. If, like for "User Profile" tab for instance, there is no locale the portal default is returned. PR2607 didn't change this BTW.

I would concur with Jan that this is a bug. Here are my conclusions:

1. It is weird that if no locale is present on a tab then the portal default should be the target.
2. It is lazy that calling code does not specify a locale. In this case: in the code that generates the links to the various pages, why can't the thread locale be passed in?
3. You can leave the locale blank in the NavigateURL method and you'll get a url that has no language parameter set. Rather than assuming the portal default locale should be chosen if the tab doesn't have one, it is entirely possible to leave it blank.

Given that these methods are at the heart of DNN's localisation logic we should be thoughtful about how we resolve this!

**Comment by donker** [comment] 2019-05-21 15:08
Found it. This is the commit that changed the behaviour

https://github.com/dnnsoftware/Dnn.Platform/commit/9ab2276753266ea477bcc8a804e0e8ad328190ce

**Comment by leedavi** [comment] 2019-05-22 00:20
I found this yesterday.  I think I can get around this with our clients site by using en-US instead of en-GB.  But this is a show stopper for nearly all European clients, can we get a emergency release out soon?

**Comment by valadas** [comment] 2019-05-22 02:42
The changes that caused this have been reverted now and pushed to Dnn10 so we can take a better look. This should make it so this current issue is no longer present in 9.4.0. Keep a eye out for 9.4.0 RC and any testing specially for those in this situation is very welcome.

**Comment by leedavi** [comment] 2019-05-22 07:30
v9.4??  That's a major problem for anyone building multiple language websites.  This is unusable. The only fix I can think (using en-US) is not liked by anyone, because we get a en-us url reference website in Europe.

Maybe the Americans don't appreciate the seriousness of this, it's killing DNN to make people wait for a usable version.  Our designers already talked about rebuilding the site in question, using another CMS.

Surly a "serious bug fix" version is required.  What do people think about that?  I know Peter Donker has a fix for this, I think this problem merits a v9.3.3 release??

**Closed** 2019-05-22 11:51 UTC
