### ISSUE TITLE
Display module on all pages is still broken

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#2426] opened 2018-10-25 09:42 UTC
It seems like with previous versions of DNN, in order to make the "Display module on all pages" to work, or rather the ability to mark it as such, you need to temporarily remove the "clientIDMode="AutoID" from web.config. 

Please note that this is an upgraded site from DNN8 so there could be that a fresh one contains different settings. This is running 09.02.00.

**Comment by Tychodewaard** [comment] 2019-07-17 14:12
WIthout adjusting the web.config, I tried to replicate the issue in 9.3.2 and it works as expected. I added an HTML module, flagged it as 'Show on all pages' and it does so. Can you confirm that?

**Comment by sleupold** [comment] 2019-07-17 16:11
AFAIK there was an issue, if content localization was enabled. 
I am not sure, whether it has been fixed yet.

**Comment by valadas** [comment] 2019-07-17 18:22
I have also had multiple odd issues with content localization enabled with that feature, I try to avoid that feature for this reason so do not currently have a good test bed to try on latest release...

**Comment by valadas** [comment] 2019-07-28 04:22
Since it was not reproducible on 9.3.2 and we do not have steps to reproduce accurately, I am closing this issue. If you guys find exact steps to make it happen on current releases, please open a new issue about it.

**Closed by valadas** 2019-07-28 04:22 UTC
