### ISSUE TITLE
Personabar no users menu

### ISSUE THREAD

**Issue by meffj00** [dnnsoftware/Dnn.Platform#2582] opened 2019-02-08 19:43 UTC
I installed the latest DNN Platform RC but in the personabar there is no menu Users.

**Comment by DinKumar** [comment] 2019-02-08 21:05
Hello @meffj00, I could see Users menu in latest DNN Platform RC. 

![latest-platform-users](https://user-images.githubusercontent.com/40901826/52506042-45e2c100-2c13-11e9-82f2-fc68282503fb.png)

**Comment by meffj00** [comment] 2019-02-08 21:42
Thanks. Fortunately, I will reinstall this release and hope to see the menu users!

**Comment by Tychodewaard** [comment] 2019-07-17 13:03
@meffj00 Hope things worked out for you. Did reinstallling / upgrading do the trick? If so, we'll close this issue

**Comment by valadas** [comment] 2019-07-17 14:59
I am closing this issue since it dates back from February and could not reproduce. @meffj00 If this is still an issue please open a new one with the version number too. Thanks.

**Closed by valadas** 2019-07-17 14:59 UTC
