### ISSUE TITLE
SiteGroup bug:  deleting a SiteGroup

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#4642] opened 2021-05-01 22:11 UTC
## Description of bug
If a SiteGroup is deleted, the SiteGroupID is not reset in the Portals table.

A portal that is a member of a SiteGroup, as denoted by PortalGroupID for the portal in the Portals table, cannot be deleted. (The delete Trashcan icon for that portal does not appear in the Sites listing.)

So, if you want to delete a SiteGroup and then delete portals that were members, you can't.  Note that I did not check what happens if portals are removed from the SiteGroup before deleting the SiteGroup.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to SiteGroup
2. Delete a SiteGroup
3. Go to Sites
4. There is no trashcan icon to delete any portal that was a member of the SiteGroup deleted in Step 2.

## Current behavior
See above

## Expected behavior
Should be able to delete portals of the deleted SiteGroup

## Error information
To achieve the desired behavior, set SiteGroupID=-1 for the appropriate portals in the Portals table.
Restart the Application

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.09.01 latest supported release

## Affected browser
Is not dependent on the browser.

**Comment by valadas** [comment] 2021-05-01 22:26
This is basically a duplicate of #4574

**Closed by valadas** 2021-05-01 22:26 UTC
Labels: Status: New
