### ISSUE TITLE
SLL redirect is broken

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#5447] opened 2022-12-19 02:07 UTC
## Description of bug
redirect from http to https doesn't work any more

## Steps to reproduce
1. create a website were http and https protocol for a (sub)domain address are assigned in IIS website management (using an SSL cert for https)
2. make sure, SSL mixed mode is enabled
3. set home page (or any other page) to "secure"

## Current behavior
when calling http://mypageurl, no recirect happens to https

## Expected behavior
redirecting to https as in previous versions

## Affected version

* [ ] 10.00.00 alpha build
* [x ] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment] 2022-12-19 02:16
adding portalsetting "sslEnabled" = "True" might fix the problem

**Comment by valadas** [comment] 2023-01-18 23:30
I cannot reproduce with the current codebase, so this should be fixed by 9.11.1

@sleupold if you find otherwise, let me know and I'll reopen it...

**Closed by valadas** 2023-01-18 23:30 UTC
Labels: Status: New
