### ISSUE TITLE
Content Personalization: Anti-Forgery Token Error

### ISSUE THREAD

**Issue by anishmishra978** [dnnsoftware/Dnn.Platform#2524] opened 2018-12-29 08:41 UTC
## Description of bug
Below error is getting logged  during the login/logout process :
**The provided anti-forgery token was meant for user "host", but the current user is "".** 
Please note that these issues are only logged during the login/logout process and any other requests after that work as intended.

## Steps to reproduce
1. Login as superuser. 
2. Visit any page and go into edit mode. 
3. Go to View Personalized Pages in the edit bar. 
4. Add a new personalized version for page. Select the condition to be Page Visited, and select any from the drop-down. 
5. Modify some of the content on the personalized version and save it/close. 
(Optional to make sure the Personalized page works) 
5.1 Visit the page selected on the dropdown. 
5.2 Go to Settings > Scheduler and run the task called Content Personalization Data Migration - this task will move the tracked evoq page view to content personalization. 
5.3 Visit the personalized page (it should now show the version since the condition was met) 
5.4 if it didn't work repeat the steps once again as it might have not logged the pageview. 
6. Logout 
7. Login

## Current result
1. Login as superuser. 
2. Visit any page and go into edit mode. 
3. Go to View Personalized Pages in the edit bar. 
4. Add a new personalized version for page. Select the condition to be Page Visited, and select any from the drop-down. 
5. Modify some of the content on the personalized version and save it/close. 
(Optional to make sure the Personalized page works) 
5.1 Visit the page selected on the dropdown. 
5.2 Go to Settings > Scheduler and run the task called Content Personalization Data Migration - this task will move the tracked evoq page view to content personalization. 
5.3 Visit the personalized page (it should now show the version since the condition was met) 
5.4 if it didn't work repeat the steps once again as it might have not logged the pageview. 
6. Logout 
7. Login

## Expected result
While this is a minor error, there should be some better error handling, or simply remove the error from being logged if this behavior is intended.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by daguiler** [comment] 2018-12-29 20:16
Current result section is wrong @anishmishra978

**Comment by valadas** [comment] 2019-07-28 07:25
The steps to reproduce are Evoq specific and we cannot reproduce this problem using Platform, for this reason I am closing this issue, if the problem lies in the Platform code and you can provide some steps to reproduce in Platform on current releases, please open a new issue.

**Closed by valadas** 2019-07-28 07:25 UTC
