### ISSUE TITLE
Exception from image handler

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2624] opened 2019-03-11 17:54 UTC
## Description of bug
I'm seeing this exception regularly in my logs, presumably from the avatar display in the theme.  I have not yet done any digging deeper to determine a root cause (I _think_ it's related to a specific user), but thought it was worthwhile to log.

## Error log
**InnerMessage**
>Could not find file 'C:\inetpub\wwwroot\example.com\App_Data\\_imagecache\BC7594FEF4EA67D7D5189557E5412AFB6ED1645A.tmp'.

**InnerStackTrace**
>at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 
>at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 
>at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) 
>at System.Web.HttpResponse.TransmitFile(String filename, Int64 offset, Int64 length) 
>at System.Web.HttpResponseWrapper.TransmitFile(String filename) 
>at DotNetNuke.Services.GeneratedImage.DiskImageStore.TryTransmitIfContains(String id, HttpResponseBase response) 
>at DotNetNuke.Services.GeneratedImage.ImageHandlerInternal.HandleImageRequest(HttpContextBase context, Func`2 imageGenCallback, String uniqueIdStringSeed) 
>at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) 
>at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

## Affected version

* [x] 9.2.2

**Comment by valadas** [comment] 2019-07-29 05:10
In the spirit of cleaning the backlog I an closing this issue since we do not have any accurate way to reproduce. @bdukes if you find some way to make it happen accurately, please submit a new issue. I know this happens to me also but very rarely, so unless we find the reason why, this issue will just take space with no actionable outcome.

**Closed by valadas** 2019-07-29 05:10 UTC
