### ISSUE TITLE
html editor cannot show imagefiles with file-extensions as uppercase

### ISSUE THREAD

**Issue by dnnsmuggler** [dnnsoftware/Dnn.Platform#3311] opened 2019-11-18 18:42 UTC
## Description of bug
The html editor cannot show imagefiles with file-extensions being uppercase.

## Steps to reproduce

1. Make sure to use dnn v 9.4.1 or 9.4.2 and DNN Connect CKEditor Provider version 1.0.7 and DNN Connect CKEditor as default html-editor.

2. Log in and click on "Site Assets" under "Manage".

3. Make sure you have a few image-files in a directory. Make sure you have both imagefiles with lowercase extensions (like *.jpg) and imagefiles with uppercase extensions (like *.JPG).

4. Navigate to a page in the site, and activate editmode (click on pencil). Then make sure you have the html modul in a pane. Open the html editor and click the image icon in order to insert an image.

5. Click "Browse on server". 

## Current result
Find the directory where the image files are located. Now you will only see the imagefiles which have the extension as lowercase.

## Expected result
We have obviously expected to see also the imagefiles with extensions as uppercase

## Error log
No errorlogs shown

## Additional context
We have tested on another site using DNN 9.3.2 and DNN Connect CKEditor Provider version 1.0.5. On this site no problems as above occur.

## Affected version

* [X ] 9.4.1 latest supported release
* [X ] 9.4.2 latest supported release

## Affected browser
Chrome and Safari are not tested. Browsers below all react as described.
* [X ] Firefox
* [X ] Internet Explorer
* [X ] Edge

## Environment on server
OS Version:
Microsoft Windows NT 6.2.9200.0

Web Server Version:
Microsoft-IIS/8.0

.NET Framework Version:
4.0.30319.42000

**Comment by bdukes** [comment] 2019-11-18 18:54
Great bug report, thanks!  It looks like this was introduced by [commit 41686aacb9edd63def63b12efa705626b034d26c](https://github.com/DNN-Connect/CKEditorProvider/commit/41686aacb9edd63def63b12efa705626b034d26c#diff-5f2ffd52fa6c685b62431f70128a1c00L297-R300) in the [CKEditor project](https://github.com/DNN-Connect/CKEditorProvider), which was included in version 1.0.7 of the editor provider.  Would you mind opening this issue in that repo, so we can keep track of it better?

**Comment by dnnsmuggler** [comment] 2019-11-18 19:27
Hi Brian,
 
I am ”brand new” to this. I did not understand what you want me to do.
Can you please explain what you want me to do?
Tanks!
Peter
 
Från: Brian Dukes [mailto:notifications@github.com] 
Skickat: den 18 november 2019 19:55
Till: dnnsoftware/Dnn.Platform <Dnn.Platform@noreply.github.com>
Kopia: dnnsmuggler <info@idea.se>; Author <author@noreply.github.com>
Ämne: Re: [dnnsoftware/Dnn.Platform] html editor cannot show imagefiles with file-extensions as uppercase (#3311)
 
Great bug report, thanks! It looks like this was introduced by commit 41686aacb9edd63def63b12efa705626b034d26c <https://github.com/DNN-Connect/CKEditorProvider/commit/41686aacb9edd63def63b12efa705626b034d26c#diff-5f2ffd52fa6c685b62431f70128a1c00L297-R300>  in the CKEditor project <https://github.com/DNN-Connect/CKEditorProvider> , which was included in version 1.0.7 of the editor provider. Would you mind opening this issue in that repo, so we can keep track of it better?

**Comment by bdukes** [comment] 2019-11-18 19:33
Please [open a new issue in DNN-Connect/CKEditorProvider](https://github.com/DNN-Connect/CKEditorProvider/issues/new).  You can just copy the contents of this issue.

Happy to provide any further guidance I can, just let me know!

**Comment by valadas** [comment] 2019-11-19 03:21
PR submitted at https://github.com/dnnsoftware/Dnn.Platform/issues/3311

**Comment by valadas** [comment] 2019-12-10 08:17
Hmm, I linked to here... Was there actually a PR submitted for this?

**Comment by bdukes** [comment] 2019-12-10 14:39
The PR for this issue was DNN-Connect/CKEditorProvider#133, but we haven't merged DNN-Connect/CKEditorProvider#134 to bump the version, so that change is only effective on new DNN installs, not upgrades.

**Comment by valadas** [comment] 2019-12-10 20:59
Oh, this makes sense...

**Comment by dnnsmuggler** [comment] 2019-12-11 08:08
Hi!
I could not understand the process. 

Will the upgraded DNNConnect/CKEditorProvider with version 1.08 not be included in a future version of DNN new install or upgrade? 

How will users be able to use the version 1.08 of DNNConnect/CKEditorProvider?

Can you Daniel or Brian please try to explain what will be done or has been done?

All the best!
/Peter

**Comment by bdukes** [comment] 2019-12-11 15:42
We've merged the change to bump the version of the CKEditor HTML Editor Provider, so the next release of DNN (9.5.0) will correctly upgrade to include that fix.

**Comment by dnnsmuggler** [comment] 2020-01-16 09:50
Hi, I did look at 9.5.0 "milestones", and there this bug is labled as "open". I thoght this was fixed and would be in the DNN version 9.5.0. I do not understand. I am most grateful if some of you guys can explain. Thanks in advance /Peter

**Comment by mitchelsellers** [comment] 2020-01-16 14:45
@dnnsmuggler this one is a bit confusing since that project is managed outside of the DNN Platform repository.  But yes, this issue WILL be resolved in 9.5.0.  I'll close this now.

**Comment by dnnsmuggler** [comment] 2020-04-15 10:55
Hi!
I did just upgrade a site from 9.4.1 to 9.5.0. Unfortunately the problem i still there. When I check the CKEditor HTML Editor Provider it was still version 1.0.7.
Am I doing anything wrong?
Thanks a lot in advance for helping me out here!
/Peter

**Comment by valadas** [comment] 2020-04-16 05:09
I can confirm that 9.5.0 came out with 1.0.7

9.6.0 on a clean install comes with 1.0.8

So either:
a: we have a versioning issue that made 9.5.0 not pickup the right source.
b: we have an upgrade issue when the new version only installs on clean instances.

My guess is our case is a but will ask the testing team to look into this...
Reopening until we can confirm either way. @dnnsmuggler if you have some time you can give a test at 9.6.0 RC1 on a non production environment, testing is always welcome both for new installs or upgrades.

**Comment by dnnsmuggler** [comment] 2020-04-21 13:27
Hi!
I have not been able to test to upgrade a site to 9.6.0 RC1, but to 9.5.0. I am not sure I understood things correctly but I understood updateing to  9.6.0 RC1 will keep the CKEditor HTML Editor Provider in version 1.0.7, and if so I did not really see the point running that update.

I could not see any errors when updateing to 9.5.0.

I did not understand what you ment by "-My guess is our case .... ".  

Would it be possible to have the upgrade to 9.6.0 to also upgrade the CKEditor HTML Editor Provider in version 1.0.8?

I also looked for a possability to update CKEditor HTML Editor Provider but could not find version 1.0.8.

**Comment by dnnsmuggler** [comment] 2020-04-22 06:58
Sorry Valadas, I now see what you ment.

**Comment by dnnsmuggler** [comment] 2020-04-28 11:23
I have now made e new install of DNN 9.6.0 rc3 and I can confirm that the DNN Connect CKEditor Provider is version 1.0.8 and it can handle images with extensions as uppercase, just like you wrote @valadas!
If it is possible to achieve this also in an update it would be grate!

I am still new to this, What does it mean to:  "-added this to Awaiting Triage in Issue Triage"?

**Comment by dnnsmuggler** [comment] 2020-04-28 19:16
I have now tried dnn 9.6.0 rc3 with different themes/skins Xcillion (supplyed in dnn 9.6.0 rc3) and also the HammerHead skin made by Chris Hammond. 
I am not able to have the "mobile" navigation working. I do not understand what the reason can be. The dnn install is the same as I mentioned above, a new install of 9.6.0 rc3.

**Comment by valadas** [comment] 2020-04-29 04:38
@dnnsmuggler yes, that should apply to upgrades too. I am just about to release the official 9.6.0 so I am closing this issue that really should have been only in the other repository. 

As for the other issue, please open a new issue with clear details maybe screenshots, etc. I am not sure I understand and it will prevent cross-talk on unrelated issues.

Thanks.

**Closed by valadas** 2020-04-29 04:38 UTC
Labels: Type: Bug
