### ISSUE TITLE
Admin Logs - Log Settings - Drop Downs are obscured and unselectable

### ISSUE THREAD

**Issue by noahbast** [dnnsoftware/Dnn.Platform#3473] opened 2020-01-13 15:50 UTC
## Description of bug
When editing Admin Logs - Log Settings, Drop Downs are too long to fit in the containing div and some values are unselectable.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Admin Logs
2. Click on Log Settings Tab
3. Click on the pencil to edit any Log Setting
4. Click on 'Keep Most Recent' drop down.
5. It is not possible to select values over 100 in the drop down.

## Current behavior
The containing div has overflow: hidden set in CSS, so even after scrolling the list, the items at the end never come into view.

## Expected behavior
All items in the drop down should be viewable and selectable.

## Screenshots
![Truncated List](https://user-images.githubusercontent.com/26256474/72269829-3bcefc80-35f2-11ea-9049-24258171e1f7.PNG)

![Log Setting div with overflow:hidden](https://user-images.githubusercontent.com/26256474/72269864-4a1d1880-35f2-11ea-9d85-ba2a7d2dae8f.PNG)

![Log Setting div with overflow:hidden disabled](https://user-images.githubusercontent.com/26256474/72269880-5012f980-35f2-11ea-9f1c-4e1c9780bda9.PNG)

## Error information
The error is with usablility, no server or browser error is generated.

## Additional context
overflow: hidden on content area of Log Setting box should be removed.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [X ] 9.4.4 latest supported release

## Affected browser

* [X ] Chrome
* [X ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment] 2020-01-15 05:36
I was able to reproduced and triaged

**Comment by Mostafa-Moafi** [comment] 2022-09-09 20:11
This issue was fixed it. 

Why is it open?

**Comment by valadas** [comment] 2022-09-09 20:33
Simply because nobody indicated it was tested working :)
Closing this issue now. 
By the way testing issues to mark them fixed or add reproduction details is also very very appreciated! Thanks for the help.

**Closed by valadas** 2022-09-09 20:33 UTC
Labels: Type: Bug, Area: AE > PersonaBar Ext > AdminLogs.Web, Effort: Low, Priority: Medium, Status: Ready for Development, help wanted
