### ISSUE TITLE
non-www to www redirects when https is in use are "spotty"

### ISSUE THREAD

**Issue by RockSolidSW** [dnnsoftware/Dnn.Platform#2187] opened 2018-07-28 15:31 UTC
## Description 

Hi, we are running Platform version 9.2.0 on Windows 2012 (R2) and have recently moved all of our customers in our main Platform instance over to https.  All of our http calls to the sites redirect to their proper site aliases, but only some redirect if we call those same sites with https but no www.  I just wanted to see if this is a known issue in DNN before digging in.  Thanks!

## Steps to reproduce

Set appropriate site aliases, enabled SSL for the sites, access the sites via both non-www and www, where some sites will redirect properly with either http or https, but some will not.

## Current result

Sites do not auto redirect to their specified site aliases with www included when attempting to get to them via https vs. http

## Expected result

All sites should redirect from non-www to www regardless of it they are accessed via http or https

## Affected version

* [x] 9.2
* [] 9.1.1 (possibly)
* [ ] 9.1 (possibly)
* [ ] 9.0 (possibly)

## Affected browser

* [x] Chrome
* [ ] Firefox (possibly)
* [x] Safari
* [x] Internet Explorer
* [ ] Edge (possibly)

**Comment by mitchelsellers** [comment] 2018-07-29 21:14
This should be possible and working in the current version.

However, for this to work you need to have aliases added for both www and non-www of the site.  Then set the WWW one as the primary alias, and select "Redirect" as your mode for URL's.  This will force the primary URL to be used in all cases.

**Comment by RockSolidSW** [comment] 2018-07-29 22:46
Awesome, thanks Mitchel!  I had that thought, but figured we were already doing so.  Good catch, thanks man!

**Comment by RockSolidSW** [comment] 2018-07-31 10:31
Looks like someone had posted re: this a few year back: http://www.dnnsoftware.com/answers/site-alias-mapping-mode-does-not-work-for-ssl-enforced-pages

**Comment by RockSolidSW** [comment] 2018-08-25 04:09
Hi Everyone, we just wanted to check in on this one.  Is this something we can look into to address?  Currently we're having to add additional SANs to our SAN SSL certificate for each of our customer's www and non-www domain formats, as the portal alias forwarding does not appear to be working "if" the sites are set for https/SSL, even if we have both portal aliases set with the www format being primary.  Thanks!  Todd

**Comment by valadas** [comment] 2019-07-27 07:54
I am closing this issue because it has some age, I was not able to reproduce on latest release and I have about 20 sites using https without that issue. @RockSolidSW if you still experience this issue using latest release please open a new issue with step by step setup to reproduce this issue from a clean install to the full setup you are using.

**Closed by valadas** 2019-07-27 07:54 UTC
Labels: Community
