### ISSUE TITLE
RFC: GDPR Data Processing Consent

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2425] opened 2018-10-24 14:32 UTC
# Request For Comments
Please review the problem and suggested solution and provide your comments to help drive this feature implementation into a future platform release.

## Description of problem
To comply with European GDPR regulation a website must get approval from the users it stores data from for this data storage by asking them to agree to the terms & conditions and the privacy statement (further referred to as tac/p). The checkbox must be unchecked at first requiring the user to tick the box to sign. When the tac/p changes the user must be prompted again in the same way to agree to the modified versions.

## Description of solution
1. Allow the website to specify pages for tac/p much like we do for login/registration pages. This will allow the administrator to use an HTML module which keeps versions of texts plus a log of when something changed. This will help downstream in determining which agreement the user has agreed to.
2. Add "HasAgreedToTerms" (bool) and "HasAgreedToTermsOn" (datetime) to the UserPortal record.
3. In the privacy tab of the site settings a new section should be added for this with
 - a switch to switch on the functionality for the site
 - a button allowing the administrator to rerequest agreement after a tac/p change. This effectively resets all "HasAgreedToTerms" to false.
 - settings to determine what happens if a user does not agree to the conditions.
4. If a user after login needs to agree to tac/p then they will be redirected much like they do now to the profile page. Either this or a popup should show to the same effect. Let us know what you think.
5. When a user registers the profile page should already show the tac/p agreement checkbox.

## To be determined
To date I've found little on the scenario that doesn't follow the default one. What happens if the user does not agree? Should an account be deactivated? Marked as deleted even?

**Comment by trouble2** [comment] 2018-10-29 10:01
I thinks there should be a checkbox in the site / user account settings, just like 'require valid profile'.
So something linke 'require consent'. Whenever someone did not check the 'consent box' there is no way to continue

**Comment by mikesmeltzer** [comment] 2018-10-29 13:47
A few questions:

Would sites be affected for public users that do not have login? If so, are we suggesting on creating users for everyone that comes to the website that submits a contact form for?

Is data storage considered even the IIS logs that can record IP addresses, what page / URI they have requested, etc.?

What if the user added a different module to the page and not the HTML module?  Would the page support this?

Are we looking at building this as something extension developers 'could' tap into but would have to update their modules for support or more of a generic system that could be toggled on for overall site privacy?

Would child portals have a separate implementation or would they be governed by their parent portal?

**Comment by mikesmeltzer** [comment] 2018-10-29 14:37
The IP address can be logged into the Event Viewer for general exceptions, etc.  So I think we would want to make sure this is taken into account - are there other areas too? I'd suggest treating an IP and as IP and not discussing if it is a shared one, public or private. Make a hard rule that we cannot store IP's.

In regards to IIS logs, we can't control that through DNN (we technically can in the web.config but probably shouldn't) so probably would want some best practices for suggesting to users how to configure IIS to become completely compliant?

**Comment by donker** [comment] 2018-10-29 14:57
Indeed our technical responsibility ends with what we can do. The plan is to have comprehensive GDPR documentation as well (not part of this RFC) which could include the part about IIS.

**Comment by mitchelsellers** [comment] 2018-10-29 14:58
Based on the information in the regulations and the legal review that I've done, logging IP Addresses for exception tracking or other security stuff is ok, and I would NOT want us to roll something into this that would restrict it.  For malicious situations that information is imperative to have recorded.

Also, for a user that doesn't agree to the terms I believe they would need to be logged-off.

**Comment by donker** [comment] 2018-10-29 15:10
> Based on the information in the regulations and the legal review that I've done, logging IP Addresses for exception tracking or other security stuff is ok, and I would NOT want us to roll something into this that would restrict it. For malicious situations that information is imperative to have recorded.

From what I read it's not that simple. What we could do is (1) have a switch for logging, (2) hash the IP addresses (i.e. only allow analysis on how many times you were accessed from location X, but not being able to identify it) and (3) ensure that the log is rolling and not accumulating forever. Possibly all with switches.

The fact is that the system is designed to help us when under attack. But for this we log all the time. My reading of GDPR is that the approach should be by default not doing this and only when needed log.

**Comment by mitchelsellers** [comment] 2018-10-29 15:22
> 
> From what I read it's not that simple. What we could do is (1) have a switch for logging, (2) hash the IP addresses (i.e. only allow analysis on how many times you were accessed from location X, but not being able to identify it) and (3) ensure that the log is rolling and not accumulating forever. Possibly all with switches.
> 
> The fact is that the system is designed to help us when under attack. But for this we log all the time. My reading of GDPR is that the approach should be by default not doing this and only when needed log.

This is one area that is really hard to document.  As under the guidelines of privacy security is compromised.  Given this is a unknown area, I would NOT want to include this into the mix, at this time, especially since this is still possible/probable on all sites due to IIS.

**Comment by donker** [comment] 2018-10-29 15:34
Call me naive but is it not more "removing a forensic tool" rather than "compromising security"? And if it is mandated by GDPR does it not behoove us to at least provide a switch so users can comply?

But I agree it could be its own RFC rather than fall under this one. So do you want me to create another RFC for this?

**Comment by mitchelsellers** [comment] 2018-10-29 16:20
@donker The concern here is that if it is a "switch" if it is turned off, and a compromise happens, it is too late.  There are key areas that we have to log IP's for, financial transactions, etc.  

I'd prefer to move this to an RFC, as it would get really grey if we give a switch to disable it, but at IIS and otherwise it is still logged and confusing.

**Comment by donker** [comment] 2018-10-29 16:42
New issue here: https://github.com/dnnsoftware/Dnn.Platform/issues/2435

**Comment by mitchelsellers** [comment] 2018-10-29 23:49
@sleupold THANK YOU!  Your verbiage was what I was looking for earlier today and I couldn’t think of it.  It was the justification for Privacy Statement for this stuff.  Google Analytics etc requires consent, but internal doesn’t;.

**Comment by BravoSierra** [comment] 2018-10-30 09:14
Article 13 is about the information we must provide when collecting date. Shoud we have these 4 fields in the site settings? (and display them in the login page):

**Information to be provided where personal data are collected from the data subject**
_Where personal data relating to a data subject are collected from the data subject, the controller shall, at the time when personal data are obtained, provide the data subject with all of the following information:_

(a) | the identity and the contact details of the controller and, where applicable, of the controller's representative;

(b) | the contact details of the data protection officer, where applicable;

(c) | the purposes of the processing for which the personal data are intended as well as the legal basis for the processing;

(e) | the recipients or categories of recipients of the personal data, if any;

**Comment by BravoSierra** [comment] 2018-10-30 09:47
About logs: I agree with all the comments above. The fact is, logs can be considered compulsory, under Article 32 **Security of processing**. (- attached the NIST document, chapter 5.1.2 and 5.1.3 that is still a reference for logging best practice)

_1.   Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including inter alia as appropriate:_
[nistspecialpublication800-92.pdf](https://github.com/dnnsoftware/Dnn.Platform/files/2528969/nistspecialpublication800-92.pdf)

.../...

**(d) | a process for regularly testing,  assessing and evaluating the effectiveness of technical and  organisational measures for ensuring the security of the processing.**

**Comment by BravoSierra** [comment] 2018-10-30 09:54
For information, the 4 points under **Article 32 Security of processing:** ( (d) beeing the more relevant to logs justification because how could you evaluate the safety of the website if you didn't have logs)

(a) | the pseudonymisation and encryption of personal data;

(b) | the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services;

(c) | the ability to restore the availability  and access to personal data in a timely manner in the event of a  physical or technical incident;

(d) | a process for regularly testing,  assessing and evaluating the effectiveness of technical and  organisational measures for ensuring the security of the processing.

**Comment by sleupold** [comment] 2018-11-03 00:32
@donker 
Is it really a big deal to handle an extra table, after we are using PetaPoco? We only need to Create Table UserPortalPrivacyConsent (UserID, PortalID, Version, CreatedAtDate) with PK (UserID, PortalID Version) and FKs to users and portals table, as well as stored procedures AddPortalPrivacyConsent(UserID, PortalID, Version) and SelectPortalPrivacyConsents(UserId, PortalID).
This would also result in a better schema, as reference table UserPortals is not used for log purposes and it is clear that UserPortals.LastUpdated does not refer to this information.
You may even limit the records to one per userportal in platform but would make it easy to extend by 3rd party modules. I volunteer to provide necessary SQL code, if it helps.

**Comment by mikesmeltzer** [comment] 2018-11-05 01:39
Could you use the existing Content Item API and store it in there? Versioning and workflow can be added with minimal effort too. Best part it already exists 👍

**Comment by sleupold** [comment] 2018-11-05 01:59
>           Could you use the existing Content Item API and store it in there? Versioning and workflow can be added with minimal effort too. Best part it already exists 👍
I would not consider a single binary value to be a typical content item - I see limited use of including it into search index, for example.

**Comment by mikesmeltzer** [comment] 2018-11-05 02:05
A content type and an associated item is just a model of data. That data could have 1 property or many. It may not be an appropriate option for what you have in mind but something to consider.

**Comment by mikesmeltzer** [comment] 2018-11-05 02:41
I was giving an example. In this case, the data would be what you just described. My thought was because of the history and workflow capabillties built in it already that it's not a bad generic area to store things, very underutilized area in my opinion. Though, as Peter mentioned above, there are other places like the event log that could be utilized for parts of the solution and with the HTML module, etc.

I would weigh the pros and cons of the different approaches and try to get the best solution that could be achieved in minimal time with minimal risk in the short term. Using solutions that already exist, whether that's an HTML module or something else that could be implemented with some documentation might be a good approach to get a win on the initiative. Longer term solutions could potentially be implemented 'better' if they are planned for in any API rebuilds in the future.

**Comment by donker** [comment] 2018-11-21 13:04
As to the above post: I'm trying to match these demands to the *technical environment* we're in. As a framework we are not at the "form level". Forms are in general part of modules. And the data processed in those modules is also part of what a third party delivers in the module. It is hard to see how the above has a bearing on our current effort.

It is not inconceivable that DNN would provide "mechanisms" within the DNN API to help module developers provide common functions. Think of the various interfaces (e.g. search) or providers (e.g. HTML editor). But these extension points take a lot of time to discuss and prepare. It is a much more invasive proposition than to focus on the framework first (as is proposed above).

**Comment by edisfera** [comment] 2018-11-21 14:34
Hi **donker**, you are right that you cannot provide support to module development for being compliant to the GDPR (DNN is a fremework not a turnkey solution). But the fact that DNN provides a registration process (forms, tables to store user data and profiles) in its framework, not mentioning the privacy and terms of use statements (that, as far as I understand, in 9.3 should become configurable pages like the home or the registration page, etc.), implies that still some effert need to be done if DNN wants to be a CMS used by UE Companies to develop web centerd solutions or by overseas Companies willing to deal with people based in UE. 
Have I lost the point of your initial question or are you talking about accounts of registered users?

**Comment by donker** [comment] 2018-11-21 19:45
I'm referring to accounts of registered users, and yes this means there is a form of the profile that users fill in. But what you describe above to me seems overkill given the requirements I've read. If it really means all of what you've said I think it's safe to say that will never happen because I can't see (a) a team of people that are willing to create such an elaborate solution and (b) getting the Americans to agree that so much new code will be added to the system to comply with a EU law. You need to keep in mind that whatever we decide needs to be doable in our current configuration of open source. I.e. by volunteers. And these volunteers need to be highly skilled so as to make the code blend well with the current framework and even then it is never guaranteed the code gets accepted. In that environment it's very hard to get people to work on it.

**Comment by edisfera** [comment] 2018-11-22 08:15
I am sorry I caused so much distress answering your request. Of course the decision to make DNN compliant with GDPR it's not up to me, I was just trying to give my contribution on this matter so that if things should be done, let's have it done the right way from the very begining. Just one last aspect I'd like to draw to your attention: GDPR is not only a EU law. Of course technically it is, but the scope and impact also affects anyone willing to do business within the EU territory. So the real question is: how much strategic is EU to DNN? If it is, then the effort should be done to comply with GDPR (incidentally, don't think US is free of privacy laws that are quite similar to the GDPR or the culture of privacy is missing, just have a look at the IAPP website to understand what I mean) beacuse when a company (or a person) needs to take a decision on what platform to use to base its venture in or directed to the EU territory, he/she for sure will have to consider, among the others, the privacy readiness of the solution.
If I can assist you in any way, please don't hesitate to do so.

**Comment by donker** [comment] 2018-11-22 09:07
Point taken. And it's not that I was upset or anything. I'm just trying to wade through the various bits of regulation that are thrown about and making sense of it and then seeing what is realistic.

I love the approach "if we do X then let's do it right". I totally agree. But what may have gone unnoticed to many is that there was a push for GDPR a while ago which was abandoned. In part because it ballooned into something no one was willing to take on. As a result we missed the deadline to get something into DNN in time for GDPR regulation to kick in. I've been a strong advocate of doing *something* and doing it for 9.3. I am volunteering to spend a week or so coding something for this, but if it turns into man-years of coding I will also be forced to throw the towel into the ring.

Also I should mention that I feel strongly that the platform shouldn't try to do everything. I.e. it is fine if the platform covers only the 95% use case as with our extensibility model we can always have others jump into the remaining 5% and make some money off that.

Your remarks stay here in this thread for reference and maybe they get swept up in what we'll do. I don't know right now. Regardless I thank you for your contribution.

**Comment by BravoSierra** [comment] 2018-11-22 15:30
GDPR is pragmatic. Consider sentences like below. So let's make it simple and a 'proportionate effort' to our purposes. That's GDPR state of mind and what we should do. It is not our responsability to "make DNN compliant". It's the controller's responsability in the context of the website to decide what is important or not. Our role is just to give them simple tools to help them be compliant. And turning this effort into a marketing tool saying "yes we care"

article 14 : Paragraphs 1 to 4 shall not apply where and insofar as .../... the provision of such information proves impossible or would involve a disproportionate effort, etc

article 32, __Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons ... etc__

**Comment by edisfera** [comment] 2018-11-22 16:04
Hi BravoSierra, that is right the controller or the processor are responsible for being compliant. I also agree that DNN should provied means to make website or web solution based on its framework compliant (privacy by design). Again, considering the initial statement (where the question was not about making DNN as a whole compliant but about the handling of consent when collecting personal data and how to behave if the privacy notice should change).
Instead, I am lost when you cite article 14 (that is about information to be provided where personal data have not been obtained from the data subject) and 32 (that is about security of processing)... I don't see how they fit on the topic of consent for data collected from the data subject.

**Comment by BravoSierra** [comment] 2018-11-22 16:52
You are correct, I was not quoting the articles for themselves, just to illustrate the fact that in many parts of the text, the GRPR is pragmatic and requires to be contextual, to keep common sense, and act on a best effort basis. This is very surprising and disturbing for lawyers, who are used to answer with booleans when their customers ask if this or that is permitted or not. With GDPR oftentimes the answer is "it depends". This is why I think we can do it both "right" and "partially", without trying to consider all use cases. If we can deliver little tools incrementally, possibly version after version,  then its ok. Let's not scratch our heads about hard deleting everything in the database when a user un-registers and difficult challenges like that. Yes theorically we should, but not if it is beyond a reasonable effort and cost. Let's consider GDPR as a state of mind or a process rather than a strict law that should be blindly enforced. Just what I tried to illustrate with these quotes.

**Comment by valadas** [comment] 2018-11-23 09:54
In my opinion, the framework needs to provide 3 things to modules.
1. A way for the module to know if Enhanced privacy (gdpr) is enabled or not, this could be a simple host setting boolean.
2. A way to notify a module that a specific user wants to export his data (this could be very similar or an extention to the existing IPortable interface, we just need to add the UserId.
3. A way to notify a module that a user wants his data deleted.

The rest of how any module handles those events would be up to the module developer.

**Comment by mitchelsellers** [comment] 2019-04-20 03:26
Changes in support of GDPR are currently in place, closing this item as it is no longer relevant to the functionality that we have in place.

**Closed by mitchelsellers** 2019-04-20 03:26 UTC
Labels: Request For Comments
