### ISSUE TITLE
Text Colour not changing in editor

### ISSUE THREAD

**Issue by gnosisnet** [dnnsoftware/Dnn.Platform#3876] opened 2020-06-30 08:10 UTC
## Description of bug
When editing any form of text, if you choose to change the colour of the text it will sometimes not display the text in the newly selected colour in the editing box. But will change the the HTML code and will display correctly once published. This happens at random. This will sometimes occur when selecting to edit existing text were it will not display the correct colour of the text. 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to any content 
2. Click on Edit Content
3. Change the colour of a sentence or word 

## Current behavior
Text does not change colour when viewing it through the Rich text editor but does seem changed when looking at the HTML editor. 

## Expected behavior
Text will change colour depending on the colour selected in the Rich Edit box.

## Additional context
We have disabled any additional add-ons / plugins on the browsers just in case it was any plug-in causing the issue but the bug still persists

## Affected version
* [X] 09.06.0 latest supported release

## Affected browser
* [X] Chrome  83.0.4103.116
* [X] Firefox 77.0.1
* [X] Internet Explorer 11
* [X] Microsoft Edge Chromium 83.0478.56

**Comment by sleupold** [comment] 2020-06-30 08:16
Did you test using DNN default skin and container, because a skin might override local text color by CSS.

**Comment by valadas** [comment] 2020-07-29 01:34
I am not able to reproduce this issue. I am closing this issue but if you find out any details and clear steps to reproduce, please do comment and I will be glad to reopen.

**Closed by valadas** 2020-07-29 01:34 UTC
Labels: Status: New
