### ISSUE TITLE
Setting a trigger for SSL bug that set EnablePopUps=false automatically.

### ISSUE THREAD

**Issue by Mohtshum** [dnnsoftware/Dnn.Platform#2316] opened 2018-09-14 15:01 UTC
## Description of bug
DNN bug with SSL sites and POP UPs.

Since it seems like you have to deactivate POP UPs for SSL Signed pages in DNN, This customer needs a trigger that actually set EnablePopUps=false automatically.

The fact is that it has to work only with the SSL pages that the customer sets up. For the other pages, which are not signed with SSL, the POP UPs should work as usual. 

## Steps to reproduce
Sign with SSL a web page
- Try to do any action that triggers a pop up. i.e. Click on login or registration on top right

## Current result
Mixed content error to load unsecure http resource

## Expected result
It should load popup without mixed content error

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment] 2018-10-07 09:58
imo the correct fix would be supporting popups on SSL pages.

**Comment by valadas** [comment] 2019-07-28 01:08
Hmm, any insight on that popup bug with ssl enabled, I have a clean 9.4.0 RC with ssl and popups work without warnings, I also have some other older sites with ssl and the login does not show in a popup. Sooo was this fixed but the PR not linked to this or is there more to reproduce this issue on recent versions. @Mohtshum can you reproduce this behaviour on a clean 9.4.0 RC install ?

**Comment by david-poindexter** [comment] 2020-06-07 16:15
Closing this issue due to a lack of verification.  If someone sees this is still a valid issue, please reply and we'll re-open.

**Closed by david-poindexter** 2020-06-07 16:15 UTC
Labels: Status: Blocked
