### ISSUE TITLE
Could not load file or assembly 'IKVM.OpenJDK.SwingAWT, DNN 9.9.0 after Upgrade from 9.8.1

### ISSUE THREAD

**Issue by rthoeni** [dnnsoftware/Dnn.Platform#4523] opened 2021-02-24 17:48 UTC
## Description of bug
2021-02-24 18:24:44.689+01:00 [xyz][D:3][T:1][ERROR] DotNetNuke.Web.Extensions.StartupExtensions - Unable to configure services for bcmail-jdk15-1.44, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null, see exception for details 
- LoaderException: Could not load file or assembly 'IKVM.OpenJDK.Core, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DotNetNuke.DependencyInjection.Extensions.TypeExtensions.SafeGetTypes(Assembly assembly, ILog logger)

021-02-24 18:24:46.714+01:00 [xyz][D:3][T:1][ERROR] DotNetNuke.Web.Extensions.StartupExtensions - Unable to configure services for **pdfbox-1.8.9**, Version=1.8.9.0, Culture=neutral, PublicKeyToken=null, see exception for details 
- LoaderException: Could not load file or assembly 'IKVM.OpenJDK.Core, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
- LoaderException: Could not load file or assembly 'IKVM.OpenJDK.SwingAWT, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
- LoaderException: Could not load file or assembly 'junit, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
- LoaderException: Could not load file or assembly '**fontbox-1.8.9**, Version=1.8.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DotNetNuke.DependencyInjection.Extensions.TypeExtensions.SafeGetTypes(Assembly assembly, ILog logger)

## Steps to reproduce
List the precise steps to reproduce the bug:
**Upgrade from 9.8.1 to 9.9.0 (Telerik removed Version)**

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [x ] 09.09.00  latest supported release (not RC Version)
* [ ] 09.08.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [x ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment] 2021-02-24 17:57
I don't think this is anything included with Dnn. Not saying it's not a Dnn issue, but it's probably not reproducible on a plain installation. My guess is that this is from a 3rd-party module and that module would need to be identified in order to even start knowing where to look for the issue. 

Can you try a clean install and start installing modules used on the real site until the issue happens.

Alternativelly, maybe you can run

```sql
select * from {databaseOwner}{objectQualifier}Assemblies
```

in sql console and note the Package ID from the row that shows that assembly name. Then run

```sql
select * from {databaseOwner}{objectQualifier}Packages
WHERE PackageID = xxx
```

replacing xxx by the actual package id. This will let you know which module uses it as a starting point...

**Comment by rthoeni** [comment] 2021-02-24 18:14
i have only Feedback, Survey, 2sic and 40Fingers SeoRedirect installed..
I * quickly * do a test installation and try to find out. 
I don't see anything so quickly right now, please excuse me

**Comment by valadas** [comment] 2021-02-24 21:03
I would suspect either 2sic or SeoRedirect for that dependency because I know it's not in the other ones you mention.

**Comment by rthoeni** [comment] 2021-02-25 10:11
Please excuse my question. Can it be that this error does not necessarily come from a module

2021-02-25 10:52:23.759+01:00 [xyz][D:5][T:158][ERROR] DotNetNuke.Web.Extensions.StartupExtensions - Unable to configure services for DotNetNuke.Web.Deprecated, Version=9.8.0.0, Culture=neutral, PublicKeyToken=null, see exception for details 
- LoaderException: Could not load file or assembly 'Telerik.Web.UI, Version=2013.2.717.40, Culture=neutral, PublicKeyToken=121fae78165ba3d4' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DotNetNuke.DependencyInjection.Extensions.TypeExtensions.SafeGetTypes(Assembly assembly, ILog logger)

**Comment by mitchelsellers** [comment] 2021-02-25 14:56
The error with the identifier most likely makes since as it was not texted against native assemblies, so I'm assuming it has an error.  

THe assembly/errors that are above are very interesting and indicative of a third-party dependency chain issue, the Telerik one seems to be secondary to some of the other stuff as well

**Comment by rthoeni** [comment] 2021-03-11 08:44
I have now installed all modules individually and updated the DNN 9,9,0. I do not find the fault. 
That took a moment, please excuse me.

What I have seen, however, is when an old module was created with Telerik and it is uninstalled in the extensions, but the uninstallation is not carried out properly and files and entries remain.

Now the question is what that depends. Is it the DNN or the module. Because when I get the message that the uninstallation was successful, I can assume that it is okay.
The idea would not be that everyone have to delete the remaining extensions using FTP or on the server, I guess.

I thank you all for the great work always here.

**Comment by valadas** [comment] 2021-03-11 18:05
Well, DNN runs uninstall code but if modules don't have proper manifests, then there might be leftovers... I am closing this issues assuming it is resolved.

**Closed by valadas** 2021-03-11 18:05 UTC
Labels: Status: New
