### ISSUE TITLE
Page redirect always returns 301 (permanent) regardless of setting

### ISSUE THREAD

**Issue by adam-j-mclellan** [dnnsoftware/Dnn.Platform#3466] opened 2020-01-10 13:50 UTC
## Description of bug
Page redirect always returns 301 (permanent) regardless of setting.

## Steps to reproduce
1. Create a new page
2. Redirect to an existing page (i.e. Home), DO NOT check "Permanent Redirect"
2. Load the page
3. Observe that the page is redirected using a 301 (permanent) redirect

## Current behavior
The permanent redirect setting is not observed.

## Expected behavior
The permanent redirect setting should be observed; in this case, the page should be redirected using a temporary redirect (302 or 307).

## Screenshots
![image](https://user-images.githubusercontent.com/59735018/72157032-4fc5f480-338d-11ea-8ccd-6cbec39da0c9.png)

![image](https://user-images.githubusercontent.com/59735018/72157072-679d7880-338d-11ea-8e5c-d0166a37145f.png)

## Additional context
I suspect this may be related to Advanced URL Management. Changing `DNNFriendlyUrl` to `urlFormat="humanfriendly"` (and accessing PageName.aspx) returns a 302 or 307 redirect as expected.

My primary dev system is Windows 10 running IIS 10, FYI.

## Affected version

* [X] 9.4.4
* [X] 8.0.4
* [X] 7.4.2

## Affected browser

* [X] Chrome
* [X] Firefox

**Comment by adam-j-mclellan** [comment] 2020-04-14 17:05
This is not stale

**Comment by adam-j-mclellan** [comment] 2020-08-04 18:07
This is very much not stale and should not have been closed. Is it possible to reopen or do I need to log it again?

**Comment by adam-j-mclellan** [comment] 2020-09-14 14:01
Just confirmed that this is still an issue as of 9.7.1

**Comment by mikesmeltzer** [comment] 2020-11-27 02:18
I've confirmed this is still an issue in v9.8.

Can someone (@bdukes, @valadas, @mitchelsellers, @david-poindexter) assign this to me and I'll triage/fix it. 

Thanks

**Comment by mitchelsellers** [comment] 2020-11-27 16:32
@mikesmeltzer THanks for the dedication!

**Comment by mikesmeltzer** [comment] 2020-12-30 15:54
I've tracked down this bug. For some reason, the code does not evaluate the user specified page redirect setting (Permanent or Temporary) to determine the appropriate response code but instead always forces both External and Internal page redirects to be 301 Permanent redirects based upon a static setting (ForwardExternalUrlsType).

I will submit a PR shortly that changes the logic so that the response code is based upon the page setting (Permanent or Temporary) instead of the static setting.

Additionally, since ForwardExternalUrlsType is statically defined, not driven by the database as other Friendly Url Settings are and is only used in this area in the platform; I recommend we deprecate the setting. I will submit a separate issue and PR for this.

**Closed** 2021-01-08 15:39 UTC
Labels: Effort: Medium, Priority: Medium, Status: Development, Type: Bug
