### ISSUE TITLE
9.4 Upgrade from 9.3.2  CONTENT > PAGES There was an error retrieving your content. Please check your internet connection

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2902] opened 2019-07-19 22:28 UTC
## Description of bug
After upgrading from 9.3.2 I am unable to edit CONTENT > PAGES as there are no pages shown and I get the following error:
 There was an error retrieving your content. Please check your internet connection

## Steps to reproduce

1. Upgrade from 9.3.2 to 9..4
2. Click on persona bar and try to view pages
3.  There was an error retrieving your content. Please check your internet connection
4. No pages displayed, unable to edit pages on website using persona bar.

## Affected version

* [x] 9.4

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment] 2019-07-20 00:49
Did you have any errors in the logs when doing the upgrade?  can you post any entries in the Admin Log, or in the logs from /portals/_default/logs

**Comment by thabaum** [comment] 2019-07-20 04:09
I looked but I did not see any errors

**Comment by thabaum** [comment] 2019-07-20 04:11
![image](https://user-images.githubusercontent.com/13577556/61573827-c41c7c80-aa69-11e9-8478-b7de8103649c.png)

**Comment by thabaum** [comment] 2019-07-20 04:13
![image](https://user-images.githubusercontent.com/13577556/61573838-fe861980-aa69-11e9-8e10-564d3d1aaed5.png)

**Comment by thabaum** [comment] 2019-07-20 04:14
another issue when trying to add a page to the site, this is just a test site no worries not doing anything production if you need a look.

**Comment by thabaum** [comment] 2019-07-20 04:14
I notice it says HTTP when it is actually HTTPS website could that be related to the issue possibly?

**Comment by valadas** [comment] 2019-07-23 18:56
I was able to reproduce upgrading a clean 9.3.2 to 9.4.0, assigned the 9.4.0 milestone

**Comment by valadas** [comment] 2019-07-23 18:57
May very well be caused by https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1027

**Comment by valadas** [comment] 2019-07-23 19:13
Tested and it appears to be the issue. As a temporary workaround if you want to continue testing the rest, you could delete in the bin folder the file Dnn.PersonaBar.Pages.dll this was probably forgotten in the cleanup scripts and will be fixed for next RC @thabaum

**Closed** 2019-07-29 19:18 UTC
Labels: bug, pull request submitted

**Comment by mnouraei** [comment] 2020-01-07 13:28
This error has happened to me too.
When I wanted to update from version 9.3.1 to dnn9.4.4.
How do I solve this problem?

**Comment by mnouraei** [comment] 2020-01-08 18:03
> This error has happened to me too.
> When I wanted to update from version 9.3.1 to dnn9.4.4.
> How do I solve this problem?

Please help me.

**Comment by valadas** [comment] 2020-01-08 22:49
@mnouraei can you open a new issue with details on how to reproduce and any interesting logs in Portal/_default/logs as far as I know this is resolved so would need more information if there is a new issue about that upgrade path. Of cource first make sure the folder permissions are ok and let us know what persona bar dlls you have in the bin folder after the upgrade.

**Comment by Rob-Brun** [comment] 2020-01-09 14:43
I am having the same problem...  The PersonaBar DLLs I have in the bin directory are
Dnn.PersonaBar.Extensions
Dnn.PersonaBar.Library
Dnn.PersonaBar.UI

This was an upgrade from 9.4.1 to 9.4.4

**Comment by valadas** [comment] 2020-01-10 07:04
The new issue that was opened is here https://github.com/dnnsoftware/Dnn.Platform/issues/3458 and it boiled down to incompatible DnnSharp modules. Please check if this is the same situation for you and if not, please open a new issue with more details like logs
