### ISSUE TITLE
User registration fails when Displayname field is not present in the custom register form

### ISSUE THREAD

**Issue by tauqeer-haider** [dnnsoftware/Dnn.Platform#3971] opened 2020-08-11 10:42 UTC
## Description of bug
User registration fails when Displayname field is not present in the custom register form

## Steps to reproduce
Precondition: Evoq Engage

1. Login as host.
2. Goto Settings> Security Page > Member Accounts > Registration Fields.
3. Set User Registration = Public
4. Set Registration Form Type = "Custom"
5. Add Registration Fields
- username
- Email
- password
- Passwordconfirm
- FirstName
- LastName
6. Click on Save.
7. Logout as host
8. Goto 'Register' Page
9. Enter all items in the fields
10. Click on Submit/Register

## Current behavior
Getting error "The Display Name is invalid."

## Expected behavior
No errors occur.
User is registered and logged in.

## Screenshots
![image](https://user-images.githubusercontent.com/22594255/89888129-e2ab6380-dbe8-11ea-8065-12b74e1adecb.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.06.02 release candidate
* [x] 09.06.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by Navilois** [comment] 2020-08-17 07:37
How did that bug reappear? It was fixed with this pull request in feb -> https://github.com/dnnsoftware/Dnn.Platform/pull/3550

**Comment by mitchelsellers** [comment] 2020-08-17 17:49
Can you please confirm the version of DNN that this was experienced in?

**Comment by tauqeer-haider** [comment] 2020-08-18 07:25
> Can you please confirm the version of DNN that this was experienced in?

9.6.1

**Comment by tauqeer-haider** [comment] 2020-08-18 07:41
For completeness purpose, the configuration for custom registration form should look like this (DisplayNameFormat is not set):
![image](https://user-images.githubusercontent.com/22594255/90484736-06722a80-e150-11ea-94ce-f94cb8960f10.png)

**Comment by Navilois** [comment] 2020-08-18 09:09
Fascinating - I'm on 9.6.1 as well, same registration fields setup but verified registration. Works as intended for me.

Had this issue as well prior to 9.6.0, but aforementioned PR fixed it.

**Comment by sleupold** [comment] 2020-08-18 09:43
Displayname is a required field, you need either include it in the registration form or provide a DisplayName format.

**Closed** 2020-08-28 23:07 UTC
Labels: Status: New
