### ISSUE TITLE
Changes to Superuser's user name are not saved (Personabar)

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2139] opened 2018-06-27 11:18 UTC
## Description 

In the DNN 9.2.0 PersonaBar, the Users admin screens appear to let you change a SuperUsers' username. However, the change is not saved.

## Steps to reproduce

1. Log into DNN as a super user
2. In the PersonaBar, browse to Manage, then Users
3. Change the Show dropdown to Superusers
4. Click on the cog (Account settings) icon for one of the Superuser accounts
5. Edit the User Name box
6. Click Save.

## Current result

The change to the Superuser's user name is not saved.

## Expected result

When showing the Account Settings for a Super User, either:

1. Allow the user name to be changed *or*
2. Change the UI so the User Name box cannot be edited (either make it read only, or replace with a plain text label).

## Affected version

* [x] 9.2 

(I have not tested other versions)

## Affected browser

n/a.

**Comment by OllyHodgson** [comment] 2018-06-27 11:21
Additionally, is this the right repo to report issues with the Personabar? If not, let me know where is best :)

**Comment by tpluscode** [comment] 2018-06-27 12:58
Thank for your report @OllyHodgson. 

> is this the right repo to report issues with the Personabar? 

I think it's fine to report in DNN Platform. We can always move.

Persona Bar has two specific repositories dnnsoftware/Dnn.AdminExperience.Library and dnnsoftware/Dnn.AdminExperience.Extensions. I'm guessing that the problem would have to be fixed in the latter one. But without some insight it's not always clear if that's the case.

**Comment by trouble2** [comment] 2019-06-21 10:18
Still an issue in 9.3.2
Just checked when I tried to change the default host (host - dnnhost)
Cannot change the host username, kind of imporant I think....

- Create new DNN installation
- Log in with default host account
- Try to change username to something else and click save
- Does not work

Just checked the tables to see if it might actually be saving something but it isn't
Kind of strange that:
- it looks like something which is not to difficult to solve (changing a username)
- it looks like something pretty imporant
- almost a year later it is still not solved
I mean I would understand if it was a minor thing, but changing the username of a host account should have some priority I would think....

**Comment by valadas** [comment] 2019-07-23 21:06
I can still reproduce in 9.4.0 but nothing gets logged anywhere, not sure if PB related or API related, but assigning 9.4.1 milestone for now

**Comment by valadas** [comment] 2020-07-28 15:51
Can still reproduce in 9.6.2 also, it is a frontend issue, the POST does not send the newly entered username when it's a host user for some reason. And tried another host it is not because it is the currently logged in host user, so I guess it's when it's any host user.

**Comment by valadas** [comment] 2021-04-09 02:50
Have to look into more details about the implications of fixing this, but I took a quick look and GetUserDetail call says the user isHost = true but isAdmin = false.

Traditionnally in the backend code hosts are considered to always be admins everywhere. Something to dig into a bit further... But then the frontend code has a canEditSettings method and that method looks at if the user is an admin and does not check the isHost value.

**Comment by valadas** [comment] 2021-08-04 04:59
We discussed this a bit and consider this by design. Users can't change their own username, admins can but in the context of a host, it could completely block other hosts out of a site by a malicious host.

**Closed by valadas** 2021-08-04 04:59 UTC
Labels: Area: AE > PersonaBar Ext > Users.Web, Effort: Medium, Priority: Medium, Status: Ready for Development, Type: Bug, help wanted

**Comment by hismightiness** [comment] 2021-08-04 17:19
The super user was never meant to have a profile, specifically for some of the reasons noted in this issue (and others).  Superusers should not be allowed to change these values since there isn't a profile to save to when the user account is `IsSuperUser`.

**Comment by Timo-Breumelhof** [comment] 2024-09-19 14:30
I just ran into this too. 
I'm not sure I agree with the reasoning to close this as a malicious host can also execute SQL to change other Hosts Usernames.
Anyway, IMO if this is By Design the input should be made read only for hosts as now it seems like a bug.

**Comment by Timo-Breumelhof** [comment] 2024-09-26 13:10
> We discussed this a bit and consider this by design. Users can't change their own username, admins can but in the context of a host, it could completely block other hosts out of a site by a malicious host.

When you change the Email address and password and or delete another Host user, you can lock them out too.

**Comment by BondForWebSolutions** [comment] 2024-09-26 13:40
Well, wouldn't it be an idea to at least be able to change your own account.

**Comment by Timo-Breumelhof** [comment] 2024-09-26 14:13
@BondForWebSolutions Agreed
