### ISSUE TITLE
Redirect after login not working when "Login page" is set

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#5044] opened 2022-03-09 10:43 UTC
After upgrading from 9.6.2. to 9.10.2 we have an issue with the redirect after login not working anymore...

The Redirect after login doesn't work when you have a custom login page (inloggen) set in "Site Settings" - 'Site Behavior" - "Login Page" is set to page from dropdown (Inloggen).

When the "Login page"is not set the redirect after login does work.

Is there a fix or workaround for this problem.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Site Settings';
2. Click on 'Site Behavior' tab;
3. Scroll to 'Login page' and select the custom page with the account login module on it;
4. Go to 'Redirect After login;
5. Select the page to redirect to.

## Current behavior
Does not redirect to selected page but redirects to the home page.

## Expected behavior
Should redirect to the page selected at Redirect After login;

## Error information
no errors in log or console

## Affected version
* [ ] 09.10.x release candidate
* [ ] 09.10.2 latest supported release

## Affected browser
all browsers

**Comment by dhleblanc** [comment] 2022-03-16 19:50
We recently experienced a similar issue after upgrading our site from DNN version 07.00.02 to 09.10.1

Only our default "Login" page would "Redirect After Login" to the appropriate page set on Site Settings/Site Behavior after the upgrade. Our other two custom login pages would not redirect after someone signed in. These pages were assign the login layout and used also used the Account Login module.

Instead of redirecting, the login page would refresh after clicking "Login". If your user was in the "Administrator" role, the login form would still be visible and the Persona bar would show. If you weren't an "Administrator" the login form would be hidden.

We were able to resolve the redirect issue with our other login pages by going to Site Settings -> Site Behavior, locating the "Login Page" drop down, then selecting the default "Login" page, then saved. It looks like after the upgrade the "Login Page" drop down was no longer assigned to any page, it showed "<None Specified> as selected.

**Comment by JP-npd** [comment] 2022-08-15 23:40
We're running v. 09.10.01 and all redirects set in the Site Behaviour > Default Pages take us to the home page, so this is still an ongoing issue!

**Comment by wbonekamp** [comment] 2022-08-16 07:00
is it a multilanguage website or default en-us?

**Comment by JP-npd** [comment] 2022-08-16 10:58
Default en-us

**Comment by wbonekamp** [comment] 2022-08-16 11:55
Look like it's an issue/bug with initial loading or saving the login page at Site Settings -> Site Behavior

**Comment by wbonekamp** [comment] 2022-08-16 11:56
Is it an upgraded DNN instance or a clean install?
Any third party modules installed?

**Comment by JP-npd** [comment] 2022-08-16 12:03
It's an upgrade, not sure if v. 09.10.02 would fix it.

We've got a few third party modules: DNNGo template, EasyDNNAccessibilityModule, GDPR Cookie Consent, WSC Slider Revolution Importer.

**Comment by wbonekamp** [comment] 2022-08-16 12:06
I don't think the upgrade to DNN 9.10.2 will fix the issue... but you can try.

**Comment by wbonekamp** [comment] 2022-08-16 12:07
does EasyDNNAccessibilityModule use a url provider module?

**Comment by JP-npd** [comment] 2022-08-16 12:17
It doesn't look like it, I deleted the module from all pages and the issue is still there.

**Comment by valadas** [comment] 2023-01-18 01:14
I could not reproduce this issue, if there are any more details that could help make it happen, please comment and I'll reopen it.

**Closed by valadas** 2023-01-18 01:14 UTC
Labels: Status: New

**Comment by dgingold** [comment] 2023-05-07 22:54
I'm seeing the problem on 9.11.1 - I'm about to upgrade to 9.11.2 and I'll check again.

the logout button links to <currentpage>/ctl/logout but the login button links to <desired-login-page>?return=<currentpage> and seems to ignore the page set for <redirectafterlogin>. If I don't click the login button, but instead go to site.com/<desired-login-page> and login, it redirects after login to the <redirectafterlogin>page correctly.

**Comment by dgingold** [comment] 2023-05-08 02:27
upgraded to 9.11.2. still see the problem.

**Comment by mitchelsellers** [comment] 2023-05-08 13:43
Are you using any third party login modules?

**Comment by dgingold** [comment] 2023-05-08 14:06
No.

**Comment by wbonekamp** [comment] 2023-06-15 07:48
Did some testing today in 9.11.2 and the issue still exist. So dgingold is right.

It's a multilanguage issue

**Comment by valadas** [comment] 2023-06-15 15:45
@wbonekamp Can you write clear steps to make this issue happen. I:
- Installed 9.6.2
- Enabled localization with (fr-fr)
- Made all pages localizable and published them
- Created a custom login page
- Set the redirect after login and saved in each language

It worked for me. So the only way to make this issue move forward would be to figure out how to actually get into that situation which I was not able to.

**Comment by reeyon** [comment] 2023-08-20 01:52
The issue is still happening on version 9.12. Fresh install.

The Redirect after login is still not working, it is always goes back to Home Page.

**Comment by Timo-Breumelhof** [comment] 2024-08-29 10:14
@valadas we ran into this too today . In our case the issue occurs with neutral pages. I'll try to reproduce on a clean install
