### ISSUE TITLE
Incorrect urls generation for navbar pages and languages and redirect to a wrong alias.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [dnnsoftware/Dnn.Platform#5348] opened 2022-10-20 11:59 UTC
## Description of bug
When multiple aliases and languages are setup on a website desktop works perfectly, but mobile redirects to a different alias (not by language but totally different alias) or generates incorrect links in a navbar (to pages and language switch). These two different behaviours occur at different urls.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Setup your website locally with any url you want (for instance website.com.ua)
2. Add another alias local.website.com.ua
3. Theoratically should be optional, but it's done on my local: I've deleted website.com.ua url from my local iis and it's used for production so that I can access production and local websites at the same time from different urls. Instead locally local.website.com.ua is set up in IIS
4. Go to PersonaBar => Settings => Languages
5. Add Ukrainian language and set it as default language
6. Go to PersonaBar => Settings => Site Settings => Site Aliases
7. Edit your aliases in such way that you have these settings:
- website.com.ua:
  - language: Ukrainian
  - browser: normal
  - theme: none
  - is primary
- website.com.ua/en:
  - language: English-US
  - browser: normal
  - theme: none
  - is primary
- local.website.com.ua:
  - language: Ukrainian
  - browser: normal
  - theme: none
- local.website.com.ua/en:
  - language: English-US
  - browser: normal
  - theme: none
9. Edit your page code in such way that you have language switch added:
`<dnn:LANGUAGE runat="server" ID="LANGUAGE1" ShowMenu="False" ShowLinks="True"
                                            SelectedItemTemplate='<span class="Language selected selected-language"> <img src="[I][FLAGSRC]" class="language-flag" alt="[CULTURE:NATIVENAME]"/></span>'
                                            AlternateTemplate=' <a href="[URL]" class="language"> <span class="Language">  <img src="[I][FLAGSRC]" class="language-flag" alt="[CULTURE:NATIVENAME]"/></span></a>'
                                            ItemTemplate=' <a href="[URL]" class="language"> <span class="Language"> <img src="[I][FLAGSRC]" class="language-flag" alt="[CULTURE:NATIVENAME]"/></span></a>' />`
11. Go to local.website.com.ua in browser - should open it and language url is local.website.com.ua/en
12. Go to local.website.com.ua/en in browser - should open it and language url is local.website.com.ua
13. Open dev tools and switch to mobile view (any should work, but you can choose Iphone SE)
14. Go to local.website.com.ua/en in browser while still in a mobile view
15. See error: language url at flags and pages urls in a navbar lead to the website.com.ua alias, which leads to production instead of localhost
16. Go to local.website.com.ua in browser while still in a mobile view
17. See 301 redirect to website.com.ua

## Current behavior
Mobile view redirects to a different alias for some reason and generates incorrect url for language.

## Expected behavior
local.website.com.ua should always lead to local.website.com.ua and all the urls both in navbar and for all languages should be generated for the same alias. Same applies for website.com.ua.

## Screenshots
Let me know if you need screenshots. It seems to me that the description should be enough as it's not a design issue.

## Error information
I suspect that it has to do with those settings for browser type in aliases. We don't have separate urls for mobile browser as our website has responsive interface. But it seems that DNN looks that it's a mobile browser, doesn't find any alias for mobile browser and redirects to a primary alias. However it doesn't explain why does it open local.website.com.ua/en and doesn't redirect that one and generates primary alias url for language change only.

## Additional context
Site Alias Mapping Mode was left Canonical (default one). I've tried to switch it to none. Didn't change current behaviour. I've found one discussion at DNN forum that setting it to redirect could cause unwanted redirect between aliases. But it's not the case right here.

The only solution I've found here is to set url as primary separately for each server (local, test and production). Meaning on local local.website.com.ua and local.website.com.ua/en would be primary urls and then it works as expected. But it's very inconvenient thing to do regularly on deploy and I'd expect it to work in a correct way without these settings.

## Affected version

* [ ] 9.10.02 latest supported release

## Affected browser

* [ ] Chrome Version 106.0.5249.119 (Official Build) (64-bit)
* [ ] Windows 10 Enterprise LTSC (x64)

**Comment by Constantine-Ketskalo** [comment] 2022-10-20 12:03
There is also a similar discussion at the DNN forum as well [here](https://www.dnnsoftware.com/forums/threadid/497059/scope/posts/multi-language-and-multi-alias-site-not-working-as-expected).
And desktop works as expected, but mobile has not logical behaviour from a user perspective.

**Comment by valadas** [comment] 2023-01-18 04:52
I cannot make this happen as described on the current codebase. Which means either:
- It was somehow fixed since this was reported.
- Or there is something else third party or environmental to make this happen

I am closing this issue but if you have any other insights to make it reproducible, just comment and I'll reopen this.

**Closed by valadas** 2023-01-18 04:52 UTC
Labels: Status: New
