### ISSUE TITLE
User.ascx and Login.ascx produce empty html for pages set as "404 error page"

### ISSUE THREAD

**Issue by Edric0** [dnnsoftware/Dnn.Platform#2216] opened 2018-08-08 16:51 UTC
## Description
If a page is set as the "404 error page" in Settings>Site settings>Site Behavior>Default Pages, then using the Login.ascx and/or User.ascx controls do not work on the page, even when there is no 404 error. This was working in DNN 7.x, but upgrade to DNN 9.2.0 made the links from these controls disappear, with no change to Skin or Site Settings.

## Steps to reproduce
1) Navigate to Settings>Site settings>Site Behavior>Default Pages
2) Set 'Home Page' and '404 Error Page' to the same page which has a skin using the controls "/Admin/Skins/User.ascx" and/or "/Admin/Skins/Login.ascx"
3) Navigate Home. The login/user links will not display. Inspecting the page shows that the included controls produced no HTML.
4) Update the '404 Error Page' setting from above to a different page other than 'Home Page' setting
5) Navigate Home and the login/user controls show links as expected

## Current result
Links do not display from these controls 

## Expected result
Links should display

## Affected version
9.2
I have not tried other versions other than 7.x where it was working and 9.2 where broken

## Affected browser
Chrome
Edge
I did not test others, but does not seem to be browser-related issue

**Comment by colincameron** [comment] 2019-02-19 16:39
I'm also seeing this issue, with 09.02.00 and later. I've tested incremental upgrades to every release from 09.00.02 upwards and discovered the bug is introduced with 09.02.00.

As @Edric0 mentions, changing the 404 error page from 'Home' causes the links to reappear.

**Comment by colincameron** [comment] 2019-02-19 16:52
It looks like this could have been introduced with #2012, which hides these links on error pages.

The file 'DNN Platform/Library/Entities/Portals/PortalSettingsExtensions.cs' simply checks if the current page is equal to the 404 error page or the 500 error page. This is fine for sites which have a dedicated error page, but will cause this bug when an existing page is used.

The simple solution would be for users not to set the error pages to be existing pages that are used elsewhere, but ideally a better check for errors should be used.

**Comment by valadas** [comment] 2019-02-19 23:50
Did you try the ShowInErrorPage as discussed in #2012 , I think it is a wanted behaviour to not show them on error pages but that property was added in case skin developers what to overwrite that behaviour ???

**Comment by colincameron** [comment] 2019-02-20 11:16
Hi @valadas - that works as a workaround, allowing the Login and Register items to show.

**Comment by valadas** [comment] 2019-02-25 05:55
And just out of curiosity, do they work too. I am trying to find why it was a wanted behavior to not show them on error pages by default.

**Comment by colincameron** [comment] 2019-02-25 10:30
I assume the original author of that PR removed them to avoid the situation where you are redirected back to a non-existent page after logging in or registering. For our site we have simply added a new page to use as a 404 error page, where previously we used the homepage as a 404 error page, bypassing the issue entirely.

**Comment by valadas** [comment] 2019-07-27 08:53
Since this appears to be by design and the is a way to not use the default behaviour documented, I am closing this issue.

**Closed by valadas** 2019-07-27 08:53 UTC
