### ISSUE TITLE
Portal.CSS is not loading last overriding all other stylesheets

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3578] opened 2020-02-19 01:16 UTC
## Description of bug
When editing Portal.CSS you have to pretty much use !important to get any CSS changes to take effect.  This is due to the load order of the css stylesheets

## Steps to reproduce
ONE EXAMPLE:

try to change logo size using Page.css.

  1  create a page
  2  upload a pagename.css to the root site directory
  3  include the following in the pagename.css file

` .navbar .brand {max-width:50px;}`

  4  Add pagename.css as Page Stylesheet in PersonaBar Page Settings editor
  5  Refresh the page notice nothing happens
  6   put the same code in Portal.css and it works however other CSS stylesheets load after Portal.css taking priority. I had to really dig to find where "CustomStylesheet" or Page Stylesheet was located. Funny part is Portal.css is called "Custom CSS" while Page.css files are "CustomStylesheet" and load way before default CSS loads with NO priority it just loads.

## Current behavior
Portal.CSS styles are loaded prior to module extensions CSS

## Expected behavior
Portal.css is loaded last and overrides all other styles as needed

## Additional context
Changing the load order of style sheets should fix the issue

## Affected version

* [x ] 10.0.0 alpha build
* [x ] 9.5.0 alpha build
* [x ] 9.4.4 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment] 2020-02-19 16:43
I noticed the wrong order of CSS files loaded in client projects as well. 
AFAIR the proper order should be:
- default.css
- module.css of any module on the page
- skin.css (or skinname.css)
- container.css for any module container used on the page
- portal.css
- page.css (css file specified in page settings)

**Comment by sleupold** [comment] 2020-02-19 16:48
In addition, we might need to provide an option for skin developers, not to load just skin.css and container.css, but additionally dependent css files (menu.css, slider.css) which would need to be included in combined css file as well - same for module developers for module.css.

**Comment by thabaum** [comment] 2020-02-20 03:16
My current PR changes only DefaultPriority to 99 and Portal.css to 100.

I will look for when Page.css is loaded and what priority which I am guessing it is "DefaultPriority" so we need to possibly give it a priority of it's own as it is not listed below.

I can see a potential issue here.

You can also see when Skin.css is loading here.  If we can come up with something that works for a solution I will get to work on the PR for version 10.

I am thinking that my current PR is going to be closed for 9.  And Page.css maybe an issue with it so I will dig deeper into it this week.

```

            /// <summary>
            /// The default priority (99) indicates that the ordering will be done based on the order in which the registrations are made
            /// </summary>
            DefaultPriority = 99,

            /// <summary>
            /// The default.css file has a priority of 5
            /// </summary>
            DefaultCss = 5,

            /// <summary>
            /// The admin.css file has a priority of 6
            /// </summary>
            AdminCss = 6,

            /// <summary>
            /// The feature.css file has a priority of 7
            /// </summary>
            FeatureCss = 7,

            /// <summary>
            /// The ie.css file has a priority of 8
            /// </summary>
            IeCss = 8,

            /// <summary>
            /// Module CSS files have a priority of 10
            /// </summary>
            ModuleCss = 10,

            /// <summary>
            /// Resources CSS files have a priority of 12
            /// </summary>
            ResourceCss = 12,

            /// <summary>
            /// Skin CSS files have a priority of 15
            /// </summary>
            SkinCss = 15,

            /// <summary>
            /// Specific skin control's CSS files have a priority of 20
            /// </summary>
            SpecificSkinCss = 20,

            /// <summary>
            /// Container CSS files have a priority of 25
            /// </summary>
            ContainerCss = 25,

            /// <summary>
            /// Specific container control's CSS files have a priority of 30
            /// </summary>
            SpecificContainerCss = 30,

            /// <summary>
            /// The portal.css file has a priority of 100 and loads last
            /// </summary>
            PortalCss = 100,

```

**Comment by thabaum** [comment] 2020-02-26 20:46
I think for now I will just create PageCss priority so it can load after PortalCss.  Everything else can load defaultpriority.  Can't keep stacking things on top and expect one to outdo the next.  For now I just want to fix what is here to an order I would understand correctly.  I want to know what file loads last and right now it is a wildcard.

Adding new load points is a bit beyond the scope of the issue here and should be possibly created in a separate issue and PR.  As of now those should load just before PortalCss with default priority in order it is loaded and PageCss I will create and setup to use PageCss priority and load last.  If you do not play with these Css files in DNN then whatever you have will load with Default priority for now like it probably does.  I just would love to know the last loading file is in fact those two files.  

If we can get this part dialed in we can then explore adding additional load points for different custom css files.  Maybe a panel can be made to even organize the order of files you want to load for your own custom DNN installation.  This way you can make your own priorities and load orders along with files and file locations.

For now I just want to see things get a little better :)

Make sense?

**Comment by valadas** [comment] 2020-02-28 02:19
Just my 2 cents but changing the file load order could have severe consequences on both themes and modules. Can we get a use case here to explain why such a change would be needed? The load order is the last thing considered when css rules are applied, if a rule is just one level more specific, it is easy to override anything no matter the load order...

**Comment by thabaum** [comment] 2020-02-28 05:31
because the load order is not correct IMO

I just put together a PR for version 10

2 files changes you can see where things are not right.  Portal.css and Page.css should load last... hands down in my opinion it is very confusing otherwise when everyone says they are suppose to but in fact as you can see here they do not.

**Comment by thabaum** [comment] 2020-02-28 05:43
P.S.  How many people currently use page specific CSS files?  I bet not many so I like to ask the question to see what kind of effect this would have on a version 9 fix.

**Comment by valadas** [comment] 2020-02-29 16:52
The major issue is that unlike c# code, this type of breaking change is very hard to properly deprecate in one version so 3rd parties know about it 2 version before it changes. It is an instant breaking change and we try to avoid them as much as possible. Css is very flexible and overrides can usually be done using other things than just the load order (IE specificity).

@sleupold it is currently possible for theme developers to do pretty much anything they can do in a module, which includes loading any css they want, directly or using the CDF and even building a dll if they want to.

**Comment by sleupold** [comment] 2020-02-29 23:45
@valades yes, module developers have about same options to affect integrity of a DNN site. Benjamin Herrmann demonstrated about a decade ago, how a malicious skin could provide host access, just by clicking a specific page element.

**Comment by thabaum** [comment] 2020-03-02 02:26
I have developed sites for my clients and this is a pain to work with.  There is work arounds but what is the point of Page.CSS, remove it it is horrible why have it?

Portal.CSS might as well remove it as well gives me a headache time and time again.

Can I see an example how this PR would make something load different that isn't already using !important like everyone has be using for workaround?

CustomStylesheet loads before Default.css 

This is just aweful for anyone new or even old like me to work with.  I complained or wrote an issue about it 10 years ago... here I am today saying the issue remains and it is annoying as a skin developer for my sites using DNN.

**Comment by david-poindexter** [comment] 2020-03-02 03:50
We have literally developed hundreds upon hundreds of custom DNN themes and sites over the years and have always relied upon two basic guiding principles in developing those themes and associated sites.

1. Know CSS.
2. Know how DNN loads CSS.

Using these two principles, we are able to be successful without any frustrations or hackish methods.  

That said, I am not in support of this proposed change.

**Comment by thabaum** [comment] 2020-03-02 15:06
I disagree...

**Comment by thabaum** [comment] 2020-03-02 15:38
I see I was not clear on my steps to reproduce on the issue.  I put a better example and how to reproduce it.  Other issues are trying to figure out why everything needs !important added.  When in fact we should never have to use !important if things loaded as intended.  

CSS stylers should clean up their code for modules removing !important might be a part of the issue.

I added new steps to reproduce an example issue of CustomPage.css loading.  That file loads first however it is advertised I believe it loads last.  Portal.css should load prior to this.

This can be changed by moving page.css to the end of the default.aspx file as it does not even have a priority.  Or add "DefaultPriority" to the priority at least so it loads closer to the end.   THen Portal.css should be default priority as well as it should load towards the end.

**Comment by mitchelsellers** [comment] 2020-03-02 16:00
Personally I'm not for this change either as the changes will be breaking.  I think that this is more about an education issue with regards to the documentation and purpose of these elements than it is an issue with the current priorities.

**Portal.css** = This is designed to allow users to make one-off changes for the entire site that are rendered BEFORE things such as page-specific CSS or default loaded items (those without a priority)

**Page.css** = This is loaded without a specific priority, and loaded AFTER portal.css since it falls on the defaults.  Personally, this is a sledgehammer approach for tweaking a single page and often times !important might be needed.

One could argue that portal.css should be loaded after all of the standard things, such as modules, etc, but that would be a **_HUGE_** breaking change and could be demonstrated with almost any module that uses any additional .css files other than module.css.

I think the crux here is that portal.css being "last" is last in the combination of default files.  One-off additional files are after portal.css which I believe is 100% by design

**Comment by thabaum** [comment] 2020-03-02 20:09
I really dont think anyone here has studied the PR or the code.

I dont like change either.

Unless someone can explain how computer languages work differently.  The code at the end of the file loads last.

Currently:  

Page.CSS loads before anything else.  Although default.css pretty much has no code I believe if you put something in there and then added a page.css same thing but different, default.css will win.  Portal.css for sure wins over Page.css as shown in my example.

So 1 issue:

Page.css should have DefaultPriority added to it that would make it currently load after Portal.css.

Or move it after all other css is loaded in the file with no priority.

That would resolve that issue.

Now for Portal.css there is CSS hard coded pushing into CSS order using DefaultPriority.  If you want to change these styles you would have to use !important to override any of the "DefaultPriority" css with Portal.css

I figured Portal.css then Page.css should load last.  As these are expected to load last.  Portal.css almost does load last so I just don't understand what is going to break.  If you have a blank portal.css nothing breaks.  If you have stuff in portal.css it loads as expected with the PR I submitted...

I am just trying to understand the logic and what the worry would be to move Portal.css load priority after DefaultPriority.  

Portal.css would only effect whatever is being loaded iwht default and this PR in NO WAY changes Module, SKin or any other css all of those would still enjoy the same exact load order.  With the exception of Page.css loading last.

What are we breaking?

**Comment by valadas** [comment] 2020-03-03 08:25
Ok, I am going to try to re-iterate a couple of key points:

**Breaking Changes**
We try to avoid breaking changes unless they are absolutely required.

**How is this a breaking change**
We have to think about working sites and not only the platform, people upgrading might have a lot of css in many places and changing the load order will affect them on upgrades, it is not just about not breaking what is on the platform or new sites, we need to make upgrades easy and non-breaking.

**About CSS load order and specificity**
In CSS, the load order is really the last thing considered. First each rules is assigned a number representing the specificity of the rule, it gets 1000 points for an inline rule, 100 points for each id in the selector, 10 points for each class or pseudo-class in the selector and 1 point for each element in the selector. I have this slide from my "Consistent styles everywhere" presentation at Dnn Summit that might help illustrate this:
![image](https://user-images.githubusercontent.com/6371568/75753090-fb3d5680-5cf7-11ea-8d6c-84025140ec54.png)
Only when that number is exactly the same does the load order makes one or the other conflicting rule win. For that reason, changing the load order will only affect those cases of the same specificity rules, it is not really a fix, but just a change since it will not make the whole stylesheet stick only by it's load order. So in other words, it has a potential to break existing sites but it would ONLY improve behaviour on new sites.

**About !important**
!important should be avoided at all costs unless it is a last resort thing. This is one of the reasons I hate bootstrap, but also 3rd party developers do tend to use it more than they should. 

**Bad documentation**
As far as I know the load order has not changed ever, if there is conflicting documentation about it, then I think that documentation needs a change to match the source code and not the other way around.

>Am I really the only one that can reproduce the issue I put above with steps? Maybe I am not explaining it right, or have you or anyone else actually tried?

I can totally reproduce as explained, but I would not do it this way, if I wanted to replace a rule for the whole portal as a developer, I would duplicated the theme and implement my customizations on that one. If I was not a developer but a designer with css knowledge, I would do my rules with at least one more level of specificity, thus not having this issue.

>Can you make all your skins without using !important?

Absolutely, I never use !important unless I do not have enough access to do proper CSS. A feature was added to not load default.css and provide your own implementation, something NvQuickTheme for instance does by default. Also I am soon working on a revamp/simplification of default.css to help there. And again if I do really have to override something, I just go one level more specific.

>CSS developers should clean up their code for modules removing !important might be a part of the issue. But they claim they are fighting with DNN issues to override css that is loading after skin.css or module.css.

That is true, but it is wrong from those who do that :) IMO modules should have a container with a unique class and the module styles should use that scope to prevent conflicts with things that are important to not be styled by the theme in some way. Another way to fix this is to use ShadowDom in modules to isolate them as components so their styles do not leak out and the environment styles do not break them. I had a whole session about this, working on something for Dnn10 to help having consistent styles everywhere... Still have to polish some rough edges but I hope to get that in in April  or some such. 

>Now if a module developer was using "DefaultPriority" to load their modules or skins custom css files somehow this might affect them. They are no following standards if they do...

3rd parties can also provide their own order for each css file they add (default 100), so changing any priority could change their load order unexpectedly, say one module declares 100 and another declares nothing, their order would swap because we changed the default to 99, or if one has 99 to begin with, it might change order with portal.css, hard to know. But this is totally not bad practice, it is provided on purpose to allow developers to inject their css in between any of the standard declared orders, hence why changing them would be a breaking change.

>Everyone says Portal.css loads last.. that is not the case.

@thabaum where did you see that please, as far as I know this has a priority of 35 and the default priority is 100, so to say it loads last would be wrong and a fix in where you read that would be needed.

In the spirit of cleaning the backlog with only actionable items "developable", I gonna close this issue which does not mean the discussion needs to stop. It is just that as described here it is by design and not something that needs development but maybe just more css knowledge or corrections to any documentation that might be wrong (if it's the case)...

**Closed by valadas** 2020-03-03 08:25 UTC
Labels: Status: New

**Comment by EPTamminga** [comment] 2020-03-03 09:04
@valadas **Great summary.** 

I suggest you do a copy of the text and paste it as a blog on https://dnncommunity.org/. If you are not in the position to do so, I would be happy to do it for you.

**Comment by valadas** [comment] 2020-03-03 10:08
You are welcome to copy-paste any of it if you do have time :)

I actually want to redo some of my presentations as either text or video and provide the powerpoints when I get some time to do so.

**Comment by thabaum** [comment] 2020-03-04 00:31
I still have not heard why CustomPage.css loads before skin.css

Shouldn't that load in "DefaultPriority" or after Page.css

If I just want to have a page use page.css to style the logo different for example it wont work as skin.css takes charge here.  How do you select the logo as I showed the .navbar .brand selector, how do you select it in Page.css so it works on that specific page differently.

If defaultpriority is to load stuff last and not portal.css and developers use default priority this is confusing people like me.

This can be closed obviously this is chaos and all over the map worrying about developers using defaultpriority IMO they should have more than one load point for such styles, one prior to Portal.css

My vote is still for portal.css and page.css to load last but I can deal with confusion it has been going on long time.

https://www.dnnsoftware.com/wiki/dotnetnuke-stylesheets-explained
Framework
Portal (Site)
Skin
Container(s)
Module(s)

So defaultpriority is for framework... no developers should really be using this.  There should be a load point prior to this or after this.

Page.css is not mentioned and is being neglected in this conversation.

**Comment by valadas** [comment] 2020-03-05 03:11
I think (I did not take time to dig into it) that page.css does not go though the content delivery framework (CDF) and as such has no priority. Any extension can load css using the CDF using a priority to place it before or after other declared priorities. Developers can define their own priority but for those who do not define it, they get the default of 100, which loads last (100). What is important to know is that the proper way to override css rules is to use specificity and not load order, load order only affect rules that have exactly the same specificity, it is an unreliable an non-future-proof way to do it, say for instance that an improvement comes in the future that removes duplicate rules or other situations.

**Comment by thabaum** [comment] 2020-03-14 02:06
>  use specificity and not load order

What if they used that specificity first? and used !important ?

**Comment by thabaum** [comment] 2020-03-14 02:38
> modules should have a container with a unique class 
I agree, but the buttons and things like this are really what bounces all over inconsistent with the theme most of the time in my experience.  I usually start stripping most all the color code except what is unique to the module and things look great.

But hard to convince this is what needs to be done as you can't teach old dogs new tricks very oftent :)

**Comment by valadas** [comment] 2020-03-21 21:09
>What if a module dev or skin dev used that specificity first or i meant ... last for top priority? and used !important ?

Well, there is no way to prevent people from using bad practices and this is not Dnn specific, there is a lot of bad css out there in everything. But a theme should wrap itself in some class like
```
<div class="myTheme">
</div>
```
Then use something like
```
.myTheme p {
}
```

Same for modules, they should have their own scope class to style just themselves and not leak out. For themes that do want to affect stuff outside the skin wrapper, then they can do so by just asking to not load the default.css and provide their own implementation for dialogs, etc.

**Comment by valadas** [comment] 2020-03-21 21:11
Also, Dnn10 will come with some Css variables that will help greatly having better styles harmony.

**Comment by Timo-Breumelhof** [comment] 2020-05-07 12:01
@valadas  I agree with the original description of this issue of @thabaum.
Portal.css should always be the last style sheet loaded and in DNN9 it's not.
The Persona Bar, Edit bar but also the CSS for the Module Action buttons are injected later in DNN 9.
I had to fix all my skins for DNN9 because one of these inserts a strange padding  (using important, *sigh*) around modules in edit mode.
I also agree that the default order injecting a style sheet through CRM is wrong as it inject style sheets at the end of the head, while the should load much earlier.
That fact that one can overrule anything in CSS doesn't make that this should not be fixed IMO (in a major version obviously).
We have had a "defined style sheet loading order" for many years, for good reasons. 
The fact that parts of DNN were implement the don't respecting that order does not mean we should not fix it IMO.

**Comment by Timo-Breumelhof** [comment] 2020-05-07 12:09
BTW, my current solution is this: https://www.40fingers.net/Blog/ID/148/Fixing-DNN-StyleSheet-load-order-using-StyleHelper-020905

**Comment by sleupold** [comment] 2020-05-07 12:23
I agree with Timo, please reopen

**Comment by Timo-Breumelhof** [comment] 2020-05-07 12:27
@sleupold Well not much chance it seems: https://github.com/dnnsoftware/Dnn.Platform/issues/3611 
I totally disagree with that decision TBH.

**Comment by valadas** [comment] 2020-05-11 22:26
As discussed in #3611 we weighted in the pros and cons of a change here and it would break for people who read documentation and also do proper css to favor people who just prefer a new way of things and/or use a lot of !important and not enough css scoping. We came to a consensus that we prefer avoiding a breaking change and having to change all current documentation for something that is easy to avoid using proper css specificity.

**Comment by sleupold** [comment] 2020-05-11 22:44
what a pity, this makes styling DNN messy "by design".

**Comment by Timo-Breumelhof** [comment] 2020-05-12 07:17
IMO this is not about something new at all.
And IMO the current solution leads to a lot of !important being used not less.
It does not influence met personally as it's just one extra line in less/scss to overruling these (or I'll just force my CSS files to a higher state), but I'm convinced that especially new or less experienced users will think "Huh?". IMO it's just not logical the way it is now.

Portal.css is not made for the CSS pros, it is in general used by people with limited CSS knowledge that bought or "inherited" a skin.
We are making things more complex than needed for those users.
Also if the order does not matter and you favor people who "do CSS properly", it's not a breaking change for those that are more knowledgable ;-)
I really wonder if this change would have a lot of impact on existing installations due to the fact that the existing CSS now must be more specific than needed after the change.

This is one of things were I really don't see how one can explain why it works this way:
If a module developer uses a module.css it gets loaded automatically and ends up with order: 10
Now if that same module developer renames the file and loads it using CRM, it gets order 100.
Can someone explain met "the logic" behind that?

I just checked and even nvQuicktheme sets the order of it's Style sheets to a higher value than the "regular" Skin.css value.
https://github.com/nvisionative/nvQuickTheme/blob/59cc6cf1303c8c74976ccfca8385f5172acda94e/partials/_includes.ascx#L4

That's a way to avoid this too, but if you continue like that Portal.css will be the first Style Sheet being loaded in the end.

**Comment by Timo-Breumelhof** [comment] 2020-05-12 09:42
> 
> 
> Personally I'm not for this change either as the changes will be breaking. I think that this is more about an education issue with regards to the documentation and purpose of these elements than it is an issue with the current priorities.
> 
> **Portal.css** = This is designed to allow users to make one-off changes for the entire site that are rendered BEFORE things such as page-specific CSS or default loaded items (those without a priority)
> 
> **Page.css** = This is loaded without a specific priority, and loaded AFTER portal.css since it falls on the defaults. Personally, this is a sledgehammer approach for tweaking a single page and often times !important might be needed.
> 
> One could argue that portal.css should be loaded after all of the standard things, such as modules, etc, but that would be a **_HUGE_** breaking change and could be demonstrated with almost any module that uses any additional .css files other than module.css.
> 
> I think the crux here is that portal.css being "last" is last in the combination of default files. One-off additional files are after portal.css which I believe is 100% by design

@mitchelsellers I agree that one could argue that page specific should come after portal.css. I'm fine with that. What I think is not logical is that for extensions that use the CRM to load a stylesheet without specifically setting the order, the SS ends up as last (order 100), after Portal.css and after Page.css.
And again, this is not about me, I think this is better for users that know less about CSS than we do (the typical Portal.css user IMO)
