### ISSUE TITLE
Editing in HTML module doesn't show files for image manager

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#3004] opened 2019-09-18 16:57 UTC
## Description of bug

See https://dnncommunity.org/forums/aft/333#1438

## Steps to reproduce
List the steps to reproduce the behavior:
1. Clean DNN 9.4.0 installation
2. Edit HTML Module
3. Browse Server

## Current result
only Root folder is shown

## Expected result
All folders and files should be shown.

See details in https://dnncommunity.org/forums/aft/333#1438

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
It's in the thread mentioned

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by sleupold** [comment] 2019-09-18 18:24
Did you sync database with file system and check folder permission (both in DAM)?

**Comment by jncraig** [comment] 2019-09-18 20:12
Yes, multiple times.

The installation was done using nvQuickSite.

**Comment by valadas** [comment] 2019-09-19 07:06
I cannot reproduce in 9.4.0

@jncraig Can you check if the permissions on those subfolders (and the root folder maybe too) are like this:
![image](https://user-images.githubusercontent.com/6371568/65221162-6cf75000-da8a-11e9-8d32-34c4d2888c11.png)

**Comment by jncraig** [comment] 2019-09-19 14:24
After my clean install, the Root folder had no privileges for All users,
but had full privileges for Administrators.

I added a Browse permission for All Users, and the directory structure
appeared when I edited a HTML module. (Clear Cache, Restart)

I removed the  Browses permission for All Users and, after clearing the
cache and restarting the site, things still work correctly.

I created a Test directory under Root and uploaded a jpg file to the new
directory.  I also uploaded a jpg to Root.  The file uploaded to Root is
not visible.  After a number of pokings around, the file in Root is not
visible (even after adding back the Browse permission).

**Comment by valadas** [comment] 2019-09-19 20:56
Strange, do you have any other pointers to figure this out?

- Are there differences in the filenames that work and don't (special characters) ?
- Are there errors in the browser console ?
- Are there interesting logs in Portals/_default/logs ?
- Are there errors in the Admin Logs ?

**Comment by jncraig** [comment] 2019-09-19 23:28
Basically I don't know.

The  person who posted in the forum said they saw only Root, no folders
below it and no files.

I did a clean install, and basically saw the same thing.  I used
nvQuickSite to do the install (quick and easy).

I went to site assets and fiddled with permissions, it started working, and
I put permissions back and it continued to work.

I have jpg files in Root and don't see them.  Yes, I even try selecting
Root.  I see jpgs in a folder I created.

I didn't look for errors.

If I get some energy tomorrow, I'll try to do the whole thing again and see
if I can repeat.

**Comment by valadas** [comment] 2019-09-24 08:12
In the spirit of cleaning the backlog I am closing this issue, if you can come up with more details or an accurate way to reproduce, feel free to comment here or open a new issue.

**Comment by jncraig** [comment] 2019-10-04 03:05
I tested this in a clean install of 9.4.1.  The problem is still there.

Please reopen.

**Comment by valadas** [comment] 2019-10-05 04:19
If we cannot reproduce, reopening the issue as is will only jam the backlog.

> After my clean install, the Root folder had no privileges for All users,
> but had full privileges for Administrators.

This part does not happen for me... Anyone else can see this happening?

> Basically I don't know.
> 
> The  person who posted in the forum said they saw only Root, no folders
> below it and no files.

Did you open this issue for an issue someone else is having, just trying to figure out how to make it happen here and if it could be environment related...

> Are there differences in the filenames that work and don't (special characters) ?
> Are there errors in the browser console ?
> Are there interesting logs in Portals/_default/logs ?
> Are there errors in the Admin Logs ?

There was no reply to these questions, we need some way to make this issue actionable in order to reopen or it will just never get resolved...

**Comment by jncraig** [comment] 2019-10-08 20:34
I have been able to reproduce this on two different computers with 9.4.1.

When I get a chance I'll try to document this better, but may be a couple of weeks.

Basically, install 9.4.1 and go to edit a HTML module.  I generally install a blank site and edit an empty HTML module on the home page.  Click the image tool, browse server for an image and you'll see only the root folder.  Create a folder, it works but you cant see it.  Upload an image into the root folder, and you won't be able to see that either.

**Comment by TopCat6** [comment] 2019-10-08 22:13
I have confirmed this issue on two servers as well, one a localhost and one production, both 9.4.1.

**Comment by valadas** [comment] 2019-10-09 07:13
Guys, please add details, if developers cannot reproduce the issues, they just increase the backlog and the issue will never get resolved. Please reply to these questions as a starter:

Are there differences in the filenames that work and don't (special characters) ?
Are there errors in the browser console ?
Are there interesting logs in Portals/_default/logs ?
Are there errors in the Admin Logs ?

**Comment by TopCat6** [comment] 2019-10-09 16:24
DNN 9.4.1, updated from 9.3.2.
To produce issue:
1. Edit an HTML module's content.
2. Click the insert image button on the toolbar.
3. Click the 'Browse Server' button.
4. Notice that the only folder you can see is the 'Root' folder, with no ability to access subfolders.

Admin Logs show no entries for this process/time-frame.
Browser console errors are as follows
`JQMIGRATE: Migrate is installed with logging active, version 3.0.0 jquery-migrate.js:18:36
JQMIGRATE: jQuery.expr[":"] is now jQuery.expr.pseudos jquery-migrate.js:62:12
console.trace() jquery-migrate.js:64:13
    jQuery 5
JQMIGRATE: jQuery.expr.filters is now jQuery.expr.pseudos jquery-migrate.js:62:12
console.trace() jquery-migrate.js:64:13
    jQuery 6
JQMIGRATE: jQuery.fn.bind() is deprecated jquery-migrate.js:62:12
console.trace() jquery-migrate.js:64:13
    jQuery 3
        migrateWarn
        bind
        hoverIntent
    dnnModuleActions http://localhost/dotnetnuke/admin/menus/ModuleActions/ModuleActions.js?cdv=1282:402
    setUpActions http://localhost/dotnetnuke/Home/ctl/Edit/mid/3417?popUp=true:85
    <anonymous> http://localhost/dotnetnuke/Home/ctl/Edit/mid/3417?popUp=true:195
    jQuery 2
        dispatch
        handle
`
The above warnings happen when the HTML editor loads. No additional entries are logged when the 'insert image' button is clicked on the toolbar.

I tried this on two production systems and one localhost test system all with essentially the same result. The production system using dependency handlers was slightly different:
`The script from “https://website.ca/dnn.controls.dnntoolbar.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
Loading failed for the <script> with source “https://website.ca/dnn.controls.dnntoolbar.js”.
JQMIGRATE: Migrate is installed with logging active, version 3.0.0 js:636:158
JQMIGRATE: jQuery.expr[":"] is now jQuery.expr.pseudos js:641:266
console.trace() js:641:337
    migrateWarn https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:641
    get https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:642
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:737
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:668
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:668
JQMIGRATE: jQuery.expr.filters is now jQuery.expr.pseudos js:641:266
console.trace() js:641:337
    migrateWarn https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:641
    get https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:642
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:1722
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:1763
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:668
    <anonymous> https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:668
JQMIGRATE: jQuery.fn.bind() is deprecated js:641:266
console.trace() js:641:337
    migrateWarn https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:641
    bind https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:663
    hoverIntent https://website.ca/DependencyHandler.axd/b05e51c96ccee28759b2461c740ddc8c/734/js:3
    dnnModuleActions https://website.ca/DependencyHandler.axd/b05e51c96ccee28759b2461c740ddc8c/734/js:42
    setUpActions https://website.ca/home/ctl/edit/mid/763?popUp=true:86
    <anonymous> https://website.ca/home/ctl/edit/mid/763?popUp=true:196
    dispatch https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:315
    handle https://website.ca/DependencyHandler.axd/fca0ea5a756c91444cd1b189d28bf741/734/js:301
	`
Nothing seems unusual in Portals/_default/logs .
Happens with existing HTML modules and with newly added HTML modules

All these systems were updated from 9.3.2 to 9.4.1, so I tried another production system that was updated from 9.2.2 to 9.4.1 and it worked properly. I can't think of another significant difference among the systems.

**Comment by jncraig** [comment] 2019-10-09 16:42
In my case, this is a clean install of DNN 9.4.1 and I've done it on two different computers with the same result.

**- Are there differences in the filenames that work and don't (special characters) ?**

Not that I can tell.  File names are PICT0054.jpeg and 67696103_945160749154434_3752235102260690944_n.jpg

This is what Site Assets shows.

![image](https://user-images.githubusercontent.com/4732485/66501473-78d6a080-ea91-11e9-92ad-70fa36d69a58.png)

This is what is in the edit window.

![image](https://user-images.githubusercontent.com/4732485/66501621-b5a29780-ea91-11e9-882d-0d55b26229c3.png)

The image in the Root directory is not shown.  The other directories under the Root directory are not shown.

- Are there errors in the browser console ?

None

- Are there interesting logs in Portals/_default/logs ?

This is the contents of today's log file, after I've done several things, including editing the HTML module and trying to insert an image.

2019-10-09 12:35:12.004-04:00 [Surface-Joe][D:2][T:36][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-10-09 12:35:12.194-04:00 [Surface-Joe][D:2][T:36][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

- Are there errors in the Admin Logs ?

No.

**Comment by TopCat6** [comment] 2019-10-09 17:00
I've just discovered that this seems to be portal dependent. Some portals on my localhost test server have this problem, while others do not.  I will investigate more to try and find differences.

**Comment by valadas** [comment] 2019-10-09 17:09
Awesome, reopened issue, now we have something to work with, thanks guys.

**Comment by valadas** [comment] 2019-10-09 17:15
I still have no clue why, but at least we now have something to look at. @TopCat6 if you find the common difference between those portals that work and do not work, please drop hints in here for comparison with other people that are experiencing the issue.

One thing that comes to mind would be the portal folder name, are they all like:
Portals/0, Portals/1 and so on or are there some names ones with maybe spaces in the path like "Portals/My Portal" ?

**Comment by jncraig** [comment] 2019-10-09 17:17
Initially folder permissions look like this (for Root and for its children):

![image](https://user-images.githubusercontent.com/4732485/66504201-a8d47280-ea96-11e9-8b29-e3a0f8a7e86c.png)

I set permissions for the Root and copied to children:

![image](https://user-images.githubusercontent.com/4732485/66504362-f3ee8580-ea96-11e9-8007-c21b3657de9a.png)

Now, if I go to edit the module and browse server:

**Comment by valadas** [comment] 2019-10-09 17:38
Hmm, interesting. Yes one thing is that you need browse files permission to view them there. now for the missing file I have no clue though...

**Comment by jncraig** [comment] 2019-10-09 17:41
Shouldn't the permissions for administrators suffice, given that I'm logged
in as an administrator?  And, when I turn off the permissions for all
users, the correct behavior persists!!!

And, my portal is portal 0.  I created another portal 1 and the same
behavior happens.

**Comment by TopCat6** [comment] 2019-10-09 18:23
Portals are just numbered, like Portals/18 etc. The portal numbers do not seem to correlate to the problem, i.e. 26 works, 27 no, 28 no, 30 works.

However, this is weird... I'm signed in as host/superuser but I can't see these subfolders. I usually put images etc. in a folder called Media off the Root. If I go into Site Assets and set All Users permissions for Browse Files and Open Files for the Media folder, then I can see the folder and files in the HTML editor. Here's the weird part: If I then remove those All Users permissions from the Media folder so that only the default Administrators have permissions, then I can still see the Media folder and files in the HTML module, even after clearing cache and restarting the app.

So I try this work-around on a production site and it works: 
I go into Site Assets, change Permissions on the Media folder to All Users, then immediately remove those same permissions. I go back to a page and edit and it works. Strange, but I now have a work-around.

**Comment by valadas** [comment] 2019-10-14 02:57
Well, that is strange, gotta dig into that code to find the logic about it. I was asking about the portals folder because I had issues in the past with a client creating portals with spaces in the portal folder name, so I was guessing maybe that was it...

**Comment by andyduo** [comment] 2020-01-09 10:24
Just to try and add to this:
Are there differences in the filenames that work and don't (special characters) ?
No
Are there errors in the browser console ?
None that I can see.
Are there interesting logs in Portals/_default/logs ?
I'll need to check this.
Are there errors in the Admin Logs ?
No.

Also I can confirm that a site I upgraded to 9.4.4 is now broken where once it was working so maybe this eliminates some factors for the devs like portal folder names...

**Comment by andyduo** [comment] 2020-02-18 02:52
I had to upgrade a v8 DNN install with 6 portals so I went to 9.4.3 but all but one portal now has this issue. It does seem a @TopCat6 mentions that it is some portals within an install and not all. Also I note that the portals that are not working don't show the folder structure in the root folder except for one which shows just a couple of the folders in the root structure. I'm not sure what the difference is that would cause that behavior.

**Comment by TopCat6** [comment] 2020-02-18 16:39
@andyduo try this workaround:  go into Site Assets, change Permissions on the root, or in the case of those portals showing some folders, the deepest folder (in the path that does not show) to All Users, then immediately remove those same permissions and put them to what they should be. Go back to a page that was a problem and edit, and see if it works. Hopefully, that will give you a work-around.

**Comment by andyduo** [comment] 2020-02-19 01:50
@TopCat6 Thanks for that, I have tried your workaround but it doesn't seem to make any difference to being able to access the files in the root folder.

**Comment by andyduo** [comment] 2020-04-14 23:37
On my test site I just installed the CKEditor Editor Provider v2.1.27 https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.27 and can successfully browse the root folder on an affected portal.

**Comment by valadas** [comment] 2020-04-16 04:59
Interesting, maybe it is an issue with https://github.com/DNN-Connect/CKEditorProvider/issues

Could it be that the missing files would have an apostrophe ('), there are 2 issues logged there. I already asked about special characters, but just in case :)

**Comment by andyduo** [comment] 2020-04-16 07:52
No special characters for me. I do suspect CKEditor V1.07 as the culprit but I'm not a developer so just a hunch from the experiments I've been doing to try and figure this out.

**Comment by andyduo** [comment] 2020-04-20 10:36
@valadas Do you want me to open this as a new issues for CKEditor?

**Comment by valadas** [comment] 2020-04-20 14:49
Well, good question, it is also a hunch on my side since I cannot reproduce the issue I am not sure what causes it.

**Comment by sleupold** [comment] 2020-04-20 14:56
there might be an issue with folder permission on your site. 
Go to Site Digital Asset Management, right click the root folder, select properties.
Check folder permission and click save (even if you didn't change any permission).

**Comment by andyduo** [comment] 2020-04-20 23:25
@sleupold This has all been checked. I have more than one site with the issue and each site has multiple portals where some portals are affected and other aren't. I'm also not alone with the issue as others have reported the same behavior. I believe it is a bug with v1.07 of the editor as other modules such as 2sic's Content module have no issues accessing the folders structure. The issue is unique to the CKEditor.

On that note, is there any way of installing an earlier version of the editor to use instead? Or an alternative supported provider that could be used of the affected sites? I've basically stopped upgrading my sites as it is introducing the issue to any sites I do upgrade.

**Comment by tstallan** [comment] 2020-05-06 11:14
I have the same problem on 3 sites that are on 9.41, 9.44 or 9.5
I can see sub folders but no images. 
None of my images have strange characters
File permissions have been set and synced, several times including to All users

One thing I notice if you select the Link icon and then browse the server then you can see all files
In the Url for the Browse server page, changing Type=Image to something else like Type=xxx makes all of the files appear

**Comment by andyduo** [comment] 2020-05-18 00:50
I have reported this as an issue on the CKEditor Github here as I believe this is where the issue most likely is coming from: [https://github.com/DNN-Connect/CKEditorProvider/issues/146](url)

**Comment by andyduo** [comment] 2020-05-18 00:55
@tstallan I can confirm changing the type from image in the url works as well.

**Comment by valadas** [comment] 2020-07-28 19:54
I am closing this issue as it needs to be handled in the other repository, if it ends up needing to be done here, please comment and I will reopen

**Comment by valadas** [comment] 2020-09-18 22:16
Reopening this issue as we are moving that project to this repository.

**Comment by andyduo** [comment] 2021-02-24 05:26
Just upgraded a bugged site to DNN 9.9.0 but have the same issue with image manager. As an experiment I switched to the CKHtmlEditorProvider (Not supported by the HTML Editor Manager) and the image browser works fine. So for fun I copied the Browser.aspx from the CKEditor/Browser folder into the DNNConnect.CKE/Browser folder and I could see all the images in the Root folder. Of course it had no styling so looked a mess but it actually worked. 

So maybe the error is in the Browser.aspx file? Maybe this helps narrow down what/where could be causing this issue? 

Other thing to mention from earlier comments is that if you remove or change the URL so it does not say 'Type=Image' it will then show everything in the root folder. 

Example change:
 /Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Type=Image&tabid=20&PortalID=0&mid=353&ckid=txtContent&mode=Portal&lang=en-US

To:
 /Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Type=ImageXX&tabid=20&PortalID=0&mid=353&ckid=txtContent&mode=Portal&lang=en-US

**Comment by rstordeur** [comment] 2021-08-19 03:53
Just in case someone is still working on this. I have 2 DNN installations. Both are on DNN 9.9.1. One was not showing anything under the Root folder for any of the portals. The other was fine. Troubleshot for about a week and was able to fix it.

1. Both installation had concurrent installations and upgrades over the last dozen years or so. Didn't have the problem until recently. Not sure which upgrade (9.4, 9.8, 9.9.1) it occurred.
2. Restored both DNN installations on my local server that I use for testing modules and upgrades prior to releasing them to production. They both run off of the same system, IIS and SQL. All directories have identical rights. The problem remained on the one installation and not the other.
3. After reviewing the installations, I compared various files in VS Studio Code. Noticed that the CKEditor config files had slight differences.
4. Checked CKEditor provider version on both installation. The faulty installation had CKEditor Provider 2.0.14 while the other was on the newer version for DNN 9.9.1,
5. The CkEditor Config Manager module was still on 2.0.14 as well.
6. The DNN Connect CKEditor Provider was on 9.9.1 for both installations.
7. Upgraded the good installation with CKEditor 2.1.27. Still no problems on that installation.
8. Upgraded the faulty installation with CKeditor 2.1.27. Still only showed Root directory entry.
9. Based on the comments here and other places, I checked for bad filenames that might break the CKEditor routines. All were fine.
10. Then realized that the faulty installation had a 'abandoned' portal directory. There was no content and no '-System' directory. Checked the Portal table in the database and that portal didn't exist there. Checked my records and that portal was deleted years ago, but somehow the main directory number was not removed.
11. Removed the directory, cleared cache, restarted the application. Problem remained. 
12. Went to one portal and using the 'site assets' module, clicked on the site root folder and used the 'sync this folder & subfolders'.
13. The sync started but the image indicating progress remained for a VERY long time. Finally after several minutes and my trying reloads, the page refreshed.
14. Went to a page and opened an HTML module that formerly didn't work. Clicking on the image icon in the toolbar, going to the 'browse server' button. All files and directories are now showing.
15. Checked several other portals on the installation and they all showed the correct files and directories without having to sync. that particular portal's files.

Conclusion:

According to my records, the empty portal directory should have been deleted a couple of years ago when I used the 'delete portal' function. For whatever reason, it appears it didn't finish the removal properly.

The empty portal directory didn't appear to affect earlier installations. I haven't restored other backups to confirm exactly when, but I believe it was okay until around 9.4.

Instead of reviewing code, I'm guessing that the update scripts for one on the upgrades didn't remove the directory but didn't throw an error. I haven't seen an error during upgrades of my development or production servers. I have not checked the actual logs however.

TD;LR
Broken installation will not show files or directories
Upgraded to CKEditor 2.01.27
Deleted orphaned portal directory from previous site
Synced Root folder in one portal.
All portals work.

Hope this helps someone else. I'm leaving the code review and fix for the real brains here.

![Modules_After](https://user-images.githubusercontent.com/10821908/130004578-44afaa78-f12d-478d-9183-7c61b4a28a81.jpg)
![Modules_Before](https://user-images.githubusercontent.com/10821908/130004579-2550cf15-171b-4f84-84e1-8b73c7daa75d.jpg)
![Providers_After](https://user-images.githubusercontent.com/10821908/130004581-4dafc239-d3e0-4979-83f9-c83bc77a4c13.jpg)
![Providers_Before](https://user-images.githubusercontent.com/10821908/130004583-568315a9-0a02-4f91-b8d6-bb09c129b846.jpg)

**Comment by andyduo** [comment] 2021-08-19 05:25
This is interesting stuff. So you managed to fix your site somehow by doing those things. Interestingly though, I have a site that was a clean install that has the issue and is already using the latest CKEditor Provider 2.1.27 and no previously deleted portals. I had a quick mess round to see if anything you did would fix mine but no luck so far.

**Comment by rstordeur** [comment] 2021-08-19 14:17
During this testing, I also did clean installs of 9.8 and 9.9.1 but didn’t have the problem on them. 

One thing to note is that those installs don't have a separate entry for the CKEditor listed in the Providers or Modules section of the Extensions menu. Only the DNN Connect CKEditor Provider is listed. But yet, when using it in the Site Settings, it's obviously accessing the CKEditor and allowing modification of it's settings. And, in the HTML module it's the CKEditor being used.

I am on the latest version of IIS. Even running on Windows 11. I will apply these fixes to production this weekend.

As far as the missing directory I had vs. the bad filenames that others have suggested, it appears that more than one issue may be affecting the CKEditor installation.

Good luck.

**Comment by valadas** [comment] 2021-10-03 19:39
In the spirit of cleaning up the issue backlog, I am closing this issue as it looks it requires some set of pre-existing conditions which are very hard to reproduce for a developer to test out and implement a fix.

If anyone has very clear steps to reproduce this from scratch, please do add those instructions step by step so we can make this issue actionable.

**Closed by valadas** 2021-10-03 19:39 UTC
Labels: Type: Bug

**Comment by cklenk** [comment] 2021-10-07 20:58
I actually just ran into this today on one of our clients' sites. They are on 9.9.1. But we did remove telerik and are using the new resource manager module. I can't seem to figure it out. No console errors, no admin logs.

![image](https://user-images.githubusercontent.com/12185742/136461117-c046dae6-2b84-48d0-b2ab-1390c998654d.png)

**Comment by andyduo** [comment] 2021-10-07 21:09
@cklenk what's your server environment? I'm on win2016. 

I've spent hours tinkering around trying to work out the cause without success. I basically have about 20 odd DNN installs I can't upgrade as it introduces this bug. At this stage moving forward I've moved away from using DNN for future site builds until I can figure it out.

**Comment by andyduo** [comment] 2021-10-07 21:44
@cklenk So it's not server version then. For me host and admin are both broken. It seems a bit random if it works for you as host but not admin. It seems to only be the root folder of the portal that doesn't work. I can create new sub folders and see everything in those.

**Comment by erw13n** [comment] 2022-08-09 17:38
I'm facing the same problem after continues upgrade from DNN 7 to latest one.

Sharing experience :
Turn out `IsProtected` field on Table `Folders` been set to `true`, especially on Portal Root Folder.
Set it to false, and clear cache will display the image on image manager.

**Comment by andyduo** [comment] 2022-08-09 21:56
@erw13n Do you mean in the actual database you changed this or is there a setting somewhere in the DNN admin panel?

**Comment by erw13n** [comment] 2022-08-10 00:03
@andyduo I change it directly on database, don't see how to change from admin panel.

**Comment by andyduo** [comment] 2022-08-10 00:52
@erw13n Awesome! Thanks for sharing this. I have a few sites that have this issue I can finally fix!

**Comment by vmasanas** [comment] 2022-08-30 10:50
Been having this issue myself and the problem is on the GetFoldersByPermissions SP. There's some bad logic in there even in DNN 9.10.2.

**Comment by andyduo** [comment] 2022-08-30 20:51
@valadas is this worth reopening given the possible cause is outlined above?

**Comment by valadas** [comment] 2022-08-31 02:25
@vmasanas do you have any details, happy to reopen if we have some clue but if not, it just clutters the backlog...

**Comment by r90727** [comment] 2025-10-30 06:36
> I'm facing the same problem after continues upgrade from DNN 7 to latest one.
> 
> Sharing experience : Turn out `IsProtected` field on Table `Folders` been set to `true`, especially on Portal Root Folder. Set it to false, and clear cache will display the image on image manager.

That's the root cause; bit me when I imported an old template to a new portal. Thank you!
