### ISSUE TITLE
Add ability to style login in more detail

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3269] opened 2019-11-10 04:59 UTC
In response to the following issue among others along with my own interests the login form needs more ability apply more style.

https://github.com/dnnsoftware/Dnn.Platform/issues/2471

**Comment by valadas** [comment] 2019-11-12 06:17
Closing this one in favour of #3278 where this overall css discussion is being held. This issue has no details on what the problem is currently, as far as I can tell every single element can already be selected using css specificity.

**Closed by valadas** 2019-11-12 06:17 UTC
Labels: Enhancement
