### ISSUE TITLE
While logged in as host ability to configure multiple sites SMTP setting from persona bar.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2245] opened 2018-08-16 19:26 UTC
## Description 
While logged in as host ability to configure multiple sites SMTP setting from persona bar.
## Steps to reproduce
Logged in a host into DNN Portal.
1. Go to Manage > Sites
Edit settings for a site
Try to edit SMTP settings for a different site than the one you are logged into

2. Go to Settings > Servers > Server Settings > SMTP
Ability to set the site you are on or for the host, not for other sites

## Current result
No way to edit settings for different sites.
## Expected result
A list of sites in Server Settings for configuring all the SMTP server settings in one place instead of trying to log into so many portals when mail server changes or the configuration of the mail server being used for those portals is changed.

## Affected version

* [ ] 9.2.1
* [ ] 9.2.0
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment] 2019-07-27 10:00
This is by design, most settings are for the currently used site, the only exception I can think of is site export-import that allows selecting the sites to export from and import to. Also if you have a huge amount of sites, you could use an sql query to change them all quickly. For those reasons, I am closing this issue, if you have good arguments for this behaviour change please create a new issue at  https://github.com/dnnsoftware/Dnn.AdminExperience

**Closed by valadas** 2019-07-27 10:00 UTC
