### ISSUE TITLE
Google analytics and Google tag manager setting "track for administrators" doesn't work correctly.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [dnnsoftware/Dnn.Platform#5198] opened 2022-07-25 16:24 UTC
## Description of bug
If you edit Google Analytics or Google Tag Manager connectors via persona bar, it doesn't work correctly. If you check the checkbox, then value in .config file is `true`. However if you deselect this checkbox and save, then the same value is not false - it's empty. As result the code for Google Analytics and Google Tag Manager is added to the page anyway. So you need to edit corresponding .config file manually and set that value to be `false`. Then it won't add that code to the page for admins.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to PersonaBar => Settings => Connectors => GOOGLE ANALYTICS
2. Setup your google analytics so that PersonaBar => Settings => Config Manager => SiteAnalytics.config
contains code for google analytics and Connector has the id for google analytics
4. Make sure that in connectors settings you don't check the checkbox Track for Administrators
5. Reload page while logged in as a superuser.
6. Open dev tools
7. See the google analytics code is still on the page
8. Check the checkbox `Track for Administrators` for Google Analytics connector
9. Save changes
10. Go to file GoogleAnalytics.config for your portal in file explorer or in git changes in visual studio
11. Edit value for `TrackForAdmin` from `true` to `false` manually.
12. Save changes
13. Check the same page again both logged in as superuser and not logged in: now Google Analytics code is added only for non admin users

## Current behavior
It doesn't work correctly when checkbox is unchecked. You need to either handle empty value or add false to the file when the checkbox is unchecked.

## Expected behavior
If checkbox `Track for Administrators` is unchecked - then Google Analytics shouldn't track for administrators.

## Screenshots
No need.

## Error information
N/A

## Additional context
N/A

## Affected version

* [ ] 09.10.02 release candidate

## Affected browser

* [ ] Chrome

**Comment by cklenk** [comment] 2022-09-06 18:31
Duplicate of #4867

**Comment by valadas** [comment] 2022-09-06 19:33
Closing this one in favor of the older #4867

**Closed by valadas** 2022-09-06 19:33 UTC
Labels: Status: New
