### ISSUE TITLE
Error loading HTML editor 9.4.1

### ISSUE THREAD

**Issue by rmick209** [dnnsoftware/Dnn.Platform#3098] opened 2019-10-04 23:37 UTC
## Description of bug
Receiving a page load error when trying to edit HTML.

An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Value cannot be null. Parameter name: source ---> System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate) at DNNConnect.CKEditorProvider.Utilities.SettingsUtil.CheckSettingsExistByKey(List`1 editorHostSettings, String key) at DNNConnect.CKEditorProvider.Web.EditorControl.LoadAllSettings() at DNNConnect.CKEditorProvider.Web.EditorControl.CKEditorInit(Object sender, EventArgs e) at System.Web.UI.Control.OnInit(EventArgs e) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.AddedControl(Control control, Int32 index) at System.Web.UI.ControlCollection.Add(Control child) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace

## Affected version
* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ X] 9.4.1 latest supported release

**Comment by valadas** [comment] 2019-10-05 00:56
I cannot reproduce on a clean or upgraded installation.

From the looks of it, it is something do do with the CkEditor provider settings. 

Do you have more info in the Admin Log or in the /Portals/_default/logs folder ?

Anything else you may think is out of the ordinary on this site compared to a new install ?

**Comment by rmick209** [comment] 2019-10-07 19:44
Looks like it was a cache issue after upgrading to 9.4.1. It'working now.

**Comment by valadas** [comment] 2019-10-08 11:43
Awesome, thanks for reporting back :) Closing the issue now.

**Closed by valadas** 2019-10-08 11:43 UTC
