### ISSUE TITLE
Site Settings not working after setup "PRIVACY" section on multi language (fa-ir , ar-sa)

### ISSUE THREAD

**Issue by soheilkheiri** [dnnsoftware/Dnn.Platform#3010] opened 2019-09-20 14:01 UTC
## Description of bug
Site Settings not working after setup "PRIVACY" section on multi language (fa-ir , ar-sa)

Errors are listed in the screenshots section.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Site Settings'
2. Active multi language : example (en-us , fa-ir) or (en-us , ar-sa)
3. open website with fa-ir language 
2. Go to 'Site Settings > Site Behavior > PRIVACY'
3. Setup and Config 'COOKIE CONSENT SETTINGS' and 'DATA CONSENT SETTINGS'
6. Save and Restart Application
4. Go to 'Site Settings' See error only (fa-ir , ar-sa)

## Current result
Explain what the current result is.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
Main error :
![privacy9 4 0](https://user-images.githubusercontent.com/4438819/65332693-67a61c80-dbd4-11e9-8482-f9d537d86d2d.JPG)

![error940-a](https://user-images.githubusercontent.com/4438819/65332749-84daeb00-dbd4-11e9-9212-a88386416c3d.JPG)

![error940-b](https://user-images.githubusercontent.com/4438819/65332755-886e7200-dbd4-11e9-99c6-94012eb8961b.JPG)

## Error log
root/API/PersonaBar/SiteSettings/GetDefaultPagesSettings?portalId=0&cultureCode=fa-IR
error : 
```xml
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>String was not recognized as a valid DateTime.</ExceptionMessage>
<ExceptionType>System.FormatException</ExceptionType>
<StackTrace>
at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles) at DotNetNuke.Entities.Portals.PortalSettingsController.LoadPortalSettings(PortalSettings portalSettings) at DotNetNuke.Entities.Portals.PortalSettings.BuildPortalSettings(Int32 tabId, PortalInfo portal) at Dnn.PersonaBar.SiteSettings.Services.SiteSettingsController.GetDefaultPagesSettings(Nullable`1 portalId, String cultureCode)
</StackTrace>
</Error>
```

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by Cloze** [comment] 2019-09-24 08:11
Tested it out.
Totally break the admin area when I enable those settings.

I think this issue should be fixed in 9.4.1 milestone because it's a critical bug.

**Comment by valadas** [comment] 2019-09-24 09:56
I did not have time to test this but assigning to 9.4.1 for now

**Comment by donker** [comment] 2019-09-27 07:51
A fix has been merged into the 9.4.1 release. This should fix the issue. If you see any more issues try resetting the consents using the button on the Site Settings screen while logged in with a locale that has access.

The core of the issue is the way the date is stored in SQL in the PortalSettings table (key = "DataConsentTermsLastChange"). This was done using a generic universal format. It will now be stored in a so-called round-trip format (more robust to storage and retrieval).

It impacted (as far as I can tell) only non-"Western" sites (i.e. ones with divergent calendars from the Gregorian that we use) under that locale.

**Closed by donker** 2019-09-27 07:51 UTC
Labels: bug

**Comment by donker** [comment] 2019-09-28 09:52
It would really help @soheilkheiri and @Cloze if you could verify resolution of this issue in this RC:

https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.4.1-rc1

**Comment by Cloze** [comment] 2019-10-03 08:15
@donker 
I believe the errors is gone and the fix is working. 

Thank you.
