### ISSUE TITLE
SiteSettings of type "RedirectAfter" are not saved correctly in a multi-lingual environment

### ISSUE THREAD

**Issue by robsiera** [dnnsoftware/Dnn.Platform#4232] opened 2020-10-21 18:09 UTC
## Description of bug
Changing the Settings>Site Settings>RedirectAfterLogout in the default language works as expected. But fails in any other language of the portal.

## Steps to reproduce
List the precise steps to reproduce the bug:
0. Make sure you have at least 2 languages active in your site, and you are in the default language part of the site
1. Go to Settings>Site Settings>RedirectAfterLogout 
2. Select any page from the dropdown
3. Scroll down and click 'Save'
4. The TabId of the selected page is saved correctly in table PortalSettings with SettingName='Redirect_AfterLogin', with the correct CultureCode
5. Now scroll to the top of the Settings>Site Settings page and click on another language in the language selector (top-right corner)
6. repeat step 1,2 and 3

## Current behavior
The TabId of the selected page is NOT saved correctly in table PortalSettings with SettingName='Redirect_AfterLogin'.  CultureCode in not take into account.

The applies to all settings of this type:
RedirectAfterLoginTabId 
RedirectAfterLoginTabName
RedirectAfterLogoutTabId
RedirectAfterLogoutTabName 
RedirectAfterRegistrationTabId 
RedirectAfterRegistrationTabName 

## Expected behavior
A new record should have been created in the PortalSettings, with the correct value and the correct Culture.

## Additional context
Initial code analysis shows that to problem starts in GetDefaultPagesSettings() on lines 312/313
`    var portal = PortalController.Instance.GetPortal(pid, cultureCode);`
`    var portalSettings = new PortalSettings(portal);`
Here the PortalInfo variable 'portal' is correctly created (with the cultureInfo) and passed through to PortalSettings() constructor.
But clearly, down the line, the cultureInfo is not take into account when needed.

## Affected version
* [ X] 09.08.00 release candidate
* [ X] 09.07.02 latest supported release

**Comment by Tychodewaard** [comment] 2020-11-02 13:18
Looks like related to #4261

**Comment by valadas** [comment] 2020-11-10 19:09
There where some localization issues resolved in the last few days, can you try if you can reproduce using this custom build to check if those fixes maybe resolved this:

https://dev.azure.com/dotnet/DNN/_build/results?buildId=41521&view=artifacts&type=publishedArtifacts

**Comment by Tychodewaard** [comment] 2020-11-10 20:02
I took the following steps and ended up in a less than desired situation:

  *   I have a subscription in Plesk http://handsondnn.nl<http://handsondnn.nl/en-us/> (I do not own that domain but that is just a temp domain name)
  *   Add dnnacademy.tjeps.com as an alias in IIS
  *   Add dnnacademy.tjeps.com as site alias in DNN
  *   A record for dnnacademy.tjeps.com  in DNS

I now have a working DNN on a live server

  *   Add language (Dutch)
  *   Enable language (at first this wasn't available but after 10 seconds the language was enabled automatically)
  *   Allow Content localization - Save
  *   Enable localized content
  *   Make all pages translatable

After this, the site goes to http://handsondnn.nl/en-us/ (which does not exist as I do not own that domain)
http://dnnacademy.tjeps.com/ redirects to that same url so that is not working either
http://dnnacademy.tjeps.com/nl-nl gives a 404 just like any page after that, so http://dnnacademy.tjeps.com/nl-nl/*


________________________________
Van: Daniel Valadas <notifications@github.com>
Verzonden: dinsdag 10 november 2020 20:10
Aan: dnnsoftware/Dnn.Platform <Dnn.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] SiteSettings of type "RedirectAfter" are not saved correctly in a multi-lingual environment (#4232)


There where some localization issues resolved in the last few days, can you try if you can reproduce using this custom build to check if those fixes maybe resolved this:

https://dev.azure.com/dotnet/DNN/_build/results?buildId=41521&view=artifacts&type=publishedArtifacts

**Comment by valadas** [comment] 2020-11-10 21:22
I am not sure what you mean, those aliases got added magically ?

**Comment by sleupold** [comment] 2020-11-10 22:15
@valadas: by design, DNN does add aliases for currently used alias (or primary alias) for all active languages, when a second language is  added.

**Comment by valadas** [comment] 2020-11-10 23:37
@sleupold  I know, but what I don't understand is that in the setup @Tychodewaard mentions tjeps.com and then in the bug report it has handsondnn.nl the whole root domain is different.

@Tychodewaard Can you rewrite the steps to reproduce more clearly.

**Comment by Tychodewaard** [comment] 2020-11-11 08:37
@valadas I recorded my scenario (3,5 minutes) on https://www.youtube.com/watch?v=M5IyS1HQP58
@sleupold if I do something the wrong way, please feel free to elaborate :-)

**Comment by valadas** [comment] 2020-11-11 20:01
Ok, I see, well, from the looks of it, your primary domain does not resolve and that's the main issue here.

**Comment by Tychodewaard** [comment] 2020-11-11 22:02
Nope, I don't think that's it. 
If you create a new website, it is quite common to use a temp domain. Of course, I could change the primary for now but as soon as I go live, the whole thing stops working. I can not recall having these issues at this level before....
@Timo-Breumelhof I know we have had issues with certain setups in the past regarding multi language. That was not this scenario, right?

**Comment by Timo-Breumelhof** [comment] 2020-11-12 20:36
@Tychodewaard no, this was not it, but there are definitely redirect issues.
Unrelated I guess but for some client sites I had to use redirects web.config because the dnn redirect to the default portal alias did not work.
Anyway, I'm not sure that has anything to do with this issue logged by @robsiera

**Comment by robsiera** [comment] 2020-11-13 05:40
Idd @Timo-Breumelhof, imo none of the above is related to the issue I logged. Well, except for the fact that multi-lingual still does not seem to be a real priority.
My bug report was clear and simple. So why didn't I fix it myself? Well, I tried, but PortalSettings() has become a real rabbit hole. I do not want to hack a fix in there. There are serious conceptual problems with the current PortalSettings. Someone should take the lead in tackling these. I'm willing to share my experiences/views in a meeting, not in writing (because too inefficient). 
Anyway, this bug report is a great little starter to follow the rabbit hole.

**Comment by valadas** [comment] 2020-11-15 19:12
Well before digging too deep into this, is it not an expected behavior (by design) that it actually uses the primary alias ?

**Comment by Tychodewaard** [comment] 2020-11-16 08:02
AFAIK, design is to listen to the aliasses that are in the alias settings. I can not recall encountering this issue before.

**Comment by Timo-Breumelhof** [comment] 2020-11-16 08:36
@valadas @Tychodewaard This issue is about Redirect_AfterLogin, not the portalalias... :-)

**Comment by sachatrauwaen** [comment] 2021-02-15 11:22
I have seen the same issue on dnn 9.8.0

**Comment by robsiera** [comment] 2021-02-15 11:53
@valadas This issue is easy to reproduce. You only need a multi-lingual site with two languages.

**Comment by Tychodewaard** [comment] 2021-06-02 17:10
unstale
________________________________
Van: stale[bot] ***@***.***>
Verzonden: woensdag 2 juni 2021 18:05
Aan: dnnsoftware/Dnn.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] SiteSettings of type "RedirectAfter" are not saved correctly in a multi-lingual environment (#4232)


We have detected this issue has not had any activity during the last 90 days. That could mean this issue is no longer relevant and/or nobody has found the necessary time to address the issue. We are trying to keep the list of open issues limited to those issues that are relevant to the majority and to close the ones that have become 'stale' (inactive). If no further activity is detected within the next 14 days, the issue will be closed automatically.
If new comments are are posted and/or a solution (pull request) is submitted for review that references this issue, the issue will not be closed. Closed issues can be reopened at any time in the future. Please remember those participating in this open source project are volunteers trying to help others and creating a better DNN Platform for all. Thank you for your continued involvement and contributions!

**Comment by valadas** [comment] 2021-09-06 02:43
Cool, unstaled...

**Closed** 2021-10-04 13:19 UTC
Labels: Type: Bug, Effort: Medium, Priority: Medium, Status: Development
