### ISSUE TITLE
Site import fails if the language of the Target Site does not match that of the Exported site

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2125] opened 2018-06-19 14:44 UTC
## Description 

Site Import fails partway through if the language of the Target Site does not match that of the Exported site.

The Import/Export screen does not inform the user of the failure - it continues to say "In Progress".

## Steps to reproduce

1. Create a new DNN site with default settings
2. Under Site Settings > Language, add *English (United Kingdom)* and set it as the Site Default
2. Add some content to that site
3. Using the Import/Export functionality, run a Full export of that site
4. Create a brand new DNN installation with default settings (so the language is *English (United States)*)
5. Copy the exported data to the new site's `App_Data\ExportImport` folder
6. Run the Import task on the new site

## Current result

The Import/Export screen will say "In Progress" forever. Meanwhile, looking in the scheduler history shows the SITE IMPORT job has failed:

```
SITE IMPORT Started. JOB #1
SITE IMPORT Preparing Check Points. JOB #1: Testing 123
Imported: USERS
Export/Import EXCEPTION: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PortalLanguages_PortalLanguages". The conflict occurred in database "920-import-test", table "dbo.Languages", column 'LanguageID'. The statement has been terminated.
```

## Expected result

1. If the Import task fails, the progress on the Import/Export screen should be updated accordingly
2. The Import task should be able to change the language settings on the target site

## Affected version

I have only tested against 9.2.0, but can reproduce the issue in both Platform and Evoq Engage.

## Affected browser

n/a, although I tested in Firefox on Windows Server 2012.

## Workaround

As a workaround, you can visit Site Settings in the Target site and manually make the language settings line up with the Exported site. then re-run the Import task from the scheduler.

**Comment by valadas** [comment] 2019-07-27 07:10
I was able to reproduce in 9.4.0 RC

**Comment by valadas** [comment] 2019-07-29 05:53
I am closing this issue in favor of the duplicate #2640 so that we have only one issue for the same problem, the reason I keep the newer one is that it covers this case and another case so it is more complete. Also #2882 has multiple fixes regarding import/export, I did not do a full review of it neither tests but just noting it here in case it resolves this issue once merged.

**Closed by valadas** 2019-07-29 05:53 UTC
Labels: bug
