### ISSUE TITLE
can't use the same tabname for different locales when en-US is not default

### ISSUE THREAD

**Issue by dieterdtx** [dnnsoftware/Dnn.Platform#3187] opened 2019-10-22 15:25 UTC
## Description of bug
When not using en-US as the default language and adding other languages, urls to tabs with the same tabnames always redirect to the default language tab.

## Steps to reproduce
1. default blank install
2. set alias behavior to redirect
3. add 2 extra languages, eg. nl-BE and de-DE
4. set nl-BE as the site standard language
5. disable en-US
6. I often set portal aliases to /nl and /de instead of /nl-BE and /de-DE. This step is probably unrelevant.
7. Enable content localization
8. create localized content
9. add a page, eg: "test1", add view rights
10. localize this page so the tabname is the same in German: "test1", add view rights

## Current result
navigating to /de/test1 redirects to /nl/test1

## Expected result
navigating to /de/test1 stays on /de/test1

## Additional context
The same issue is prominent when:
- disabling popups for the site
- setting the home page for both languages to "home"
- trying to edit a module on the home page.
This causes the redirect of: 
/de/home/ctl/Edit/mid/400
to
/nl/home/ctl/Edit/mid/400
Which makes editing modules impossible on the German home page. (When not using popups)

## Affected version
* [x ] 9.4.1 alpha build
* [x] 9.4.0 latest supported release

**Comment by dieterdtx** [comment] 2020-04-10 06:41
Has this issue been addressed in a newer version?

**Comment by valadas** [comment] 2020-04-15 07:41
Not that I am aware of, did you try to replicated the issue in 9.5.0 https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.5.0 

or in the latest RC 9.6.0 ( this is a release candidate not meant for production) https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.6.0-rc1

It would help triage the issue if you could give it a test, we do need some help with triage, and testing on the latest release is a good way to help cleanup the issues and help them move up faster :)

**Comment by dieterdtx** [comment] 2020-04-30 09:42
I just had 20 minutes to try this, so I created a new installation with 9.5.0.

I could not reproduce this in 9.5, which is good. However with the limited time I had I could not try it again in 9.4 to see if I did indeed do the same steps. We have delayed our move to a newer versions of DNN for our sites because of other projects. At the moment I am not testing any further. If I do find the time, do I reference this ticket and create a new one should I encounter similar issues in the future?

**Comment by valadas** [comment] 2020-04-30 19:14
Well, since you could not reproduce in 9.5.0 I am gonna assume some other localization fix also fixed this and I am going to close the issue. Everyone involved in this issue will still receive notifications if anyone comments, so if for some reason you realize it is indeed not fixed, please comment and I will be happy to reopen it.

**Closed by valadas** 2020-04-30 19:14 UTC
Labels: Status: New

**Comment by edisfera** [comment] 2020-05-03 16:57
Please review my final comment in #3219 it could address what has been described here (that is, not setting User Profile Page in each language prevents TabIndexController from correctly creating the TabDictionary thus not correctly serving the right page).
