### ISSUE TITLE
Error File Output Caching

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#4829] opened 2021-09-16 13:59 UTC
## Description of bug
Recently upgraded to DNN 9.10.1 and found an issue withe the File Output Caching Provider.
When File Output Caching is enabled on a page:

![image](https://user-images.githubusercontent.com/7567981/133625562-5034339e-870a-41e4-8022-2487271a7a8a.png)

you get this error:  

Server Error in '/' Application.
The process cannot access the file '\wwwroot\Portals\10-System\Cache\Pages\3055_EDB6574E377BD7139F1064B7D02E155263211131A500582A7B937A78325FE531.attrib.resources' because it is being used by another process.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.IOException: The process cannot access the file '\wwwroot\Portals\10-System\Cache\Pages\3055_EDB6574E377BD7139F1064B7D02E155263211131A500582A7B937A78325FE531.attrib.resources' because it is being used by another process.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:
[IOException: The process cannot access the file '\wwwroot\Portals\10-System\Cache\Pages\3055_EDB6574E377BD7139F1064B7D02E155263211131A500582A7B937A78325FE531.attrib.resources' because it is being used by another process.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +935
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1242
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +146
   System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost) +126
   System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost) +105
   System.IO.StreamWriter..ctor(String path, Boolean append) +57
   System.IO.File.CreateText(String path) +49
   DotNetNuke.Services.OutputCache.Providers.FileResponseFilter.StopFiltering(Int32 itemId, Boolean deleteData) +120
   DotNetNuke.HttpModules.OutputCaching.OutputCacheModule.OnUpdateRequestCache(Object sender, EventArgs e) +418
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +142
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +75
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +93

when you delete the file, the error is gone untill you refresh/reload the page

![image](https://user-images.githubusercontent.com/7567981/133625460-ae143c2e-7736-4299-996a-b4baa060df4a.png)

## Affected version
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment] 2021-09-16 14:24
Typically this is due to a configuration issue, and the provider hasn’t been modified in recent releases. A few questions. 

1. Do you happen to have more than one server in play?  If so, how are you handling this. 
2. Do you happen to have a web garden enabled (more than one process)?

**Comment by EPTamminga** [comment] 2021-09-16 14:24
This looks the same as the error that I get for OpenContent URL handling.

See: https://github.com/sachatrauwaen/OpenContent/issues/177

**Comment by wbonekamp** [comment] 2021-09-20 07:19
> Typically this is due to a configuration issue, and the provider hasn’t been modified in recent releases. A few questions.
> 
> 1. Do you happen to have more than one server in play?  If so, how are you handling this.
> 2. Do you happen to have a web garden enabled (more than one process)?

No it's not a webfarm, single webserver...

**Comment by wbonekamp** [comment] 2021-09-20 07:20
Checked other DNN instances and the bug/issue also exist in DNN 9.9.0 +

**Comment by valadas** [comment] 2021-10-05 03:31
I cannot reproduce this issue, it might be something environmental like an antivirus or some sort of permissions issue. I will close this issue for now but if you figure out any new details that could point us in the right direction, please comment and I will re-open the issue.

**Closed by valadas** 2021-10-05 03:31 UTC
Labels: Status: New
