### ISSUE TITLE
Strange behaviour when adding a new language

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2866] opened 2019-06-21 11:39 UTC
## Description of bug
It seems some funny things are going on when I add a new language to DNN 9.3.2
- add language (through extenstions) (in this case Dutch)
- go to site settings, languages
- language is not available directly, seems some caching issue

- set Dutch as the default language
- try to remove English as the default language
- it still says you cannot remove English because it is the default language, so probably also a caching issue

- DNN autmatically adds some portalaliasses for the languages (site.com/nl and site.com/en)
- though I am only adding the languages so I can disable the other one.
- so I will not be using the aliasses, for me it is not necesarry to add the extra aliasses automatically

- sudenly I see /language/en-us/ in my url, that's strange, I don't need that...
- the setting for showing parameters in the url was already set to OFF, and still DNN adds them...
![Naamloos7](https://user-images.githubusercontent.com/1827559/59920149-ebac0500-9429-11e9-93f3-8f615959bc86.png)

## Affected version

* [x] 9.3.2

**Comment by sleupold** [comment] 2019-06-21 11:43
this is intended behavior for adding a second language. 
i admit, this is not optimal, if you just want to switch default language to your preferred local.
However, usually, you would have selected the preferred language in the install wizard - though this process is currently under review.

**Comment by trouble2** [comment] 2019-06-23 20:16
Ok, so is the 'include language paramater in url' not something that is not necessary anymore? Since DNN now uses the method of using multiple portal aliasses?

**Comment by sleupold** [comment] 2019-06-23 20:31
AFAIK, it depends on the url rewriter, you are using

**Comment by valadas** [comment] 2019-07-29 22:20
If I understand correctly this is inteded behaviour and I am closing this issue for that reason. If I am wrong and there is actually something to change or discuss further, please comment and I will be happy to reopen.

**Closed by valadas** 2019-07-29 22:20 UTC

**Comment by sleupold** [comment] 2019-07-30 00:28
there seems to be missing a page request, but this has already been reported in a different issue.
