### ISSUE TITLE
Not all pages visible when adding existing module

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#2594] opened 2019-02-25 10:34 UTC
## Description of bug
I want to add an existing module but the page residing that module is not visible in the UI for adding the module

## Steps to reproduce
List the steps to reproduce the behavior:
1. A have a page 'For who'
2. This page has sub pages Developer, Projectmanager, Scrum master
3. In the page Scrum Master I click on the Add exsiting module page as I want to use a copy of modules on the Developer page
4. In the UI the Page 'For who' is not visible.

## Expected result
I expect the page in the UI so I can expand that page to select the subpage

## Additional context
If I paste the pagename in the UI, the page is visible. So, there is a workaround but not a friendly one.

## Affected version
* [x] 9.2.2
Did not test other versions

## Affected browser

* [x] Chrome
* [x ] Edge
Did not test other versions.

**Comment by valadas** [comment] 2019-02-25 11:55
I cannot reproduce on Dnn 9.3.0 RC2
Also tried Dnn 9.2.2 and with and without localization enabled.
Tried with a couple of variations of permissions and with "show in menu" enabled and disables. Could not reproduce.

**Comment by valadas** [comment] 2019-02-25 11:58
Could there be something special about that page that is non standard and I could have forgotten to test out ?

**Comment by Tychodewaard** [comment] 2019-02-25 13:00
I got it...As I did not want the top menu to be clickable, I disabled that toplevel page. If I enable the page, the page is visable in the UI again. It is a bit confusing as the page is visable in other UI's (pages or add page-select parent). I don't know if it is by design or considered a (small) bug?

**Comment by sleupold** [comment] 2019-02-25 13:36
this is an (annoying) old bug

**Comment by EPTamminga** [comment] 2019-02-25 14:47
You could wuestion if this is a bug. 

If the page is non clickable, what is use of having modules on that page? Users cannot reach that non clickable page.

**Comment by Tychodewaard** [comment] 2019-02-25 14:58
I want to add the modules that have the disabled page as a parent. Those pages can be reached.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Ernst Peter Tamminga <notifications@github.com>
Verzonden: maandag, februari 25, 2019 3:48 PM
Aan: dnnsoftware/Dnn.Platform
CC: Tycho de Waard; Author
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Not all pages visible when adding existing module (#2594)


You could wuestion if this is a bug.

If the page is non clickable, what is use of having modules on that page? Users cannot reach that non clickable page.

**Comment by sleupold** [comment] 2019-02-25 15:09
@Tychodewaard is correct, if a parent page is set to be disabled in menu (just to open the submenu), pages in submenus are hidden from the list of available pages - which is not correct.

**Comment by Mhtshum** [comment] 2019-03-08 06:27
This is producible
Title should be: 
> Unable to "Add an Existing Module" from a disabled page

**Comment by daguiler** [comment] 2019-05-21 14:45
I just discovered this was only partially fixed by #2686.
In the same file, `getChildren` and `search` methods should have been fixed as well, because this issue can still be reproduced when child pages are disabled and not just the top-level page.

**Comment by roman-yagodin** [comment] 2019-06-17 09:07
> If the page is non clickable, what is use of having modules on that page? Users cannot reach that non clickable page.

Disabling page in menu just means you do not want menu link to be clickable. But page still could be accessible via direct URL and have modules on it. This means that single "Disabled in menu" flag is just not enough for all use cases, but this is subject of another issue.

**Comment by daguiler** [comment] 2019-06-17 11:25
Closing as PR was merged.

**Closed by daguiler** 2019-06-17 11:25 UTC
