### ISSUE TITLE
Error Clear Cache

### ISSUE THREAD

**Issue by idasbv** [dnnsoftware/Dnn.Platform#3446] opened 2020-01-03 07:53 UTC
## Description of bug
Clear cache returns error: "Error trying to clear cache" 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to persone bar
2. Go to Servers
3. Click button "Clear cache"

## Current behavior
Returns error: "Error trying to clear cache" 

## Expected behavior
Clear cache of the website

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13104302/71712556-082bef80-2e06-11ea-94be-10d47f0e498d.png)

## Error information
No message in de admin log

Browser console log:
![image](https://user-images.githubusercontent.com/13104302/71712611-42958c80-2e06-11ea-8e0f-bff9f5abe720.png)

## Additional context
Click on "Restart Application" also returns a simular error 

## Affected version
* [ ] 9.4.4 clean install
* [ ] 9.4.4 upgrade

## Affected browser
All

**Comment by valadas** [comment] 2020-01-03 07:59
I cannot reproduce, could this be a permissions issue, can you check if the application pool user has full permissions on the hosting folder.

**Comment by idasbv** [comment] 2020-01-03 08:14
Problem with action form... upgrade to the latest version (hotfix)

**Comment by david-poindexter** [comment] 2020-01-03 14:01
@idasbv glad you figured it out and thanks for letting us know.  We will go ahead and close this issue.

**Closed by david-poindexter** 2020-01-03 14:01 UTC
Labels: Status: On Hold

**Comment by idasbv** [comment] 2020-01-06 10:32
We found out the hotfix also doesn't work... The modules simple isn't compatible with DNN 9.4 because of the changes in some dependency injections... This is quite an issues for all people that use the DNNSharp modules...
