### ISSUE TITLE
Error Installing 9.3 - 9.3.1

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2651] opened 2019-03-28 21:48 UTC
## Description of bug
Clean Installation Error at 18%

## Error log
1:03 Minutes   |   18% ERROR occured - System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding. Drop constraints from dbo.[TabModuleSettings] Drop constraints from dbo.[TabModules] Drop constraints from dbo.[ModuleSettings] Drop constraints from dbo.[Modules] Drop constraint FK_CoreMessaging_Subscriptions_Modules from dbo.[CoreMessaging_Subscriptions] Drop constraint FK_ModulePermission_Modules from dbo.[ModulePermission] Drop constraints from dbo.[ModuleControls] Drop constraints from dbo.[CoreMessaging_NotificationTypeActions] Drop constraints from dbo.[Skins] Drop constraints from dbo.[ModuleDefinitions] Drop constraints from dbo.[CoreMessaging_NotificationTypes] Drop constraint FK_CoreMessaging_Messages_CoreMessaging_NotificationTypes from dbo.[CoreMessaging_Messages] Drop constraints from dbo.[ContentItems_Tags] Drop constraints from dbo.[Taxonomy_Terms] Drop constraints from dbo.[Tabs] Drop constraint FK_TabPermission_Tabs from dbo.[TabPermission] Drop constraint FK_TabSettings_Tabs from dbo.[TabSettings] Drop constraint FK_TabUrls_Tabs from dbo.[TabUrls] Drop constraint FK_TabVersions_TabId from dbo.[TabVersions] Drop constraints from dbo.[SkinPackages] Drop constraints from dbo.[SkinControls] Drop constraints from dbo.[DesktopModules] Drop constraint FK_PortalDesktopModules_DesktopModules from dbo.[PortalDesktopModules] Drop constraints from dbo.[Authentication] Drop constraints from dbo.[Assemblies] Drop constraints from dbo.[Taxonomy_Vocabularies] Drop constraints from dbo.[Packages] Drop constraint FK_JavaScriptLibrariesPackages from dbo.[JavaScriptLibraries] Drop constraint FK_LanguagePacks_Packages from dbo.[LanguagePacks] Drop constraint FK_PackageDependencies_Packages from dbo.[PackageDependencies] Drop constraints from dbo.[EventLogConfig] Drop constraint FK_EventLog_EventLogConfig from dbo.[EventLog] Drop constraints from dbo.[ContentItems] Drop constraint FK_ContentItems_MetaData_ContentItems from dbo.[ContentItems_MetaData] Drop constraint FK_ContentWorkflowLogs_ContentItems from dbo.[ContentWorkflowLogs] Drop constraint FK_Files_ContentItems from dbo.[Files] Drop constraint FK_ScheduleItemSettings_Schedule from dbo.[ScheduleItemSettings] Drop constraints from dbo.[Roles] Drop constraint FK_DesktopModulePermission_Roles from dbo.[DesktopModulePermission] Drop constraint FK_FolderPermission_Roles from dbo.[FolderPermission] Drop constraint FK_ModulePermission_Roles from dbo.[ModulePermission] Drop constraint FK_TabPermission_Roles from dbo.[TabPermission] Drop constraint FK_UserRoles_Roles from dbo.[UserRoles] Drop constraint FK_Relationships_RelationshipTypes from dbo.[Relationships] Drop constraints from dbo.[ProfilePropertyDefinition] Drop constraint FK_UserProfile_ProfilePropertyDefinition from dbo.[UserProfile] Drop constraint FK_ContentWorkflowStatePermission_Permission from dbo.[ContentWorkflowStatePermission] Drop constraint FK_DesktopModulePermission_Permission from dbo.[DesktopModulePermission] Drop constraint FK_FolderPermission_Permission from dbo.[FolderPermission] Drop constraint FK_ModulePermission_Permission from dbo.[ModulePermission] Drop constraint FK_TabPermission_Permission from dbo.[TabPermission] Drop constraint FK_ContentItems_MetaDataMetaData from dbo.[ContentItems_MetaData] Drop constraint FK_PortalLanguages_PortalLanguages from dbo.[PortalLanguages] Drop constraints from dbo.[FolderMappings] Drop constraint FK_FolderMappingsSettings_FolderMappings from dbo.[FolderMappingsSettings] Drop constraint FK_Folders_FolderMappings from dbo.[Folders] Drop constraint FK_EventLog_EventLogTypes from dbo.[EventLog] Drop constraint FK_ContentWorkflowActions_ContentTypes from dbo.[ContentWorkflowActions] Add 6 rows to dbo.[ContentTypes] Add 146 rows to dbo.[EventLogTypes] Add 3 rows to dbo.[FolderMappings] Add 1 row to dbo.[IPFilter] Add 35 rows to dbo.[Journal_Types] Add 1 row to dbo.[Languages] Add 5126 rows to dbo.[Lists] ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:05449aa8-8ba7-486b-9255-58a617502490 Error Number:-2,State:0,Class:11 /************************************************************/ /***** SqlDataProvider *****/ /***** *****/ /***** *****/ /***** Note: To manually execute this script you must *****/ /***** perform a search and replace operation *****/ /***** for dbo. and *****/ /***** *****/ /************************************************************/ -- Pointer used for text / image updates. This might not be needed, but is declared here just in case DECLARE @pv binary(16) -- minimum date to set for all creted on last modified on columns DECLARE @CreateBy int = -1 DECLARE @UpdateBy int = NULL DECLARE @UpdateByNotNull int = -1 DECLARE @CreateOn datetime = {ts '2000-01-01 00:00:00'} DECLARE @UpdateOn datetime = NULL DECLARE @UpdateOnNotNull datetime = {ts '2000-01-01 00:00:00'} PRINT(N'Drop constraints from dbo.[TabModuleSettings]') ALTER TABLE dbo.[TabModuleSettings] NOCHECK CONSTRAINT [FK_TabModuleSettings_TabModules] PRINT(N'Drop constraints from dbo.[TabModules]') ALTER TABLE dbo.[TabModules] NOCHECK CONSTRAINT [FK_TabModules_Modules] ALTER TABLE dbo.[TabModules] NOCHECK CONSTRAINT 

.... super duper long log error 

2012 server, sql 2014

## Additional context
I clean installed 9.2.2 ok, upgraded to 9.3.1 RC0 ok and without the banner rotator security error #2650 

I was upgrading to 9.3.0 another site instance and it bugged out locked the site up with a DNN installation error saying the connection was busy with another installation... I see that build is no longer downloadable.  Had to go to backup...

## Affected version

* [x] 9.3.0

* [ ] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by winsider** [comment] 2019-04-04 19:08
I get the same error when trying install on a clean Azure db.

04/04/2019 18:56:08 [ERROR] DotNetNuke.Services.Upgrade.Upgrade System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

**Comment by pjkruger** [comment] 2019-04-09 05:38
DNN9.3.1 Installation error

I get the same erro when trying to install on a clean SQL db.

**Comment by thabaum** [comment] 2019-04-09 17:27
i had ot use 9.2.2 then upgrade from that

**Comment by pjkruger** [comment] 2019-04-10 06:10
I was also only able to upgrade from DNN9.2.2

**Comment by beckerben** [comment] 2019-04-20 17:10
Exact same issue here, mine was a clean install using the install file, clean database / fresh install, i hit the retry several times and same thing. Guess I need to go back a version.

**Comment by valadas** [comment] 2019-04-20 22:49
I highly recommend to everyone experiencing this issue to give a try to the 9.3.2 RC0. I think this is related to a timeout issue that should be resolved in 9.3.2.

Obviously it is an RC (Release Candidate) so do not use that in production, but it would help a lot to get your testing on this, I think this is resolved but since it does not happen on all environments, it would be very nice to have your testing on this to know if the fix is good or not while we are still in the RC phase. 

You can download it here:
https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.3.2-rc0

**Comment by OllyHodgson** [comment] 2019-04-22 19:07
@valadas I got the same error installing 9.3.2-RC0 on a free tier Azure app service. When I get time, I'll give it another go with some more DTUs.

This was a blank slate install, not an upgrade. I created an Azure app service using the DNN Platform 9.1.0 template, then used KUDU to delete all the files in wwwroot folder, and uploaded the 9.3.2-RC0 install files instead. Then visited the site to start installation.

**Comment by pjkruger** [comment] 2019-04-23 11:35
I did a clean install now of DNN932 RC0 without any errors.

**Comment by valadas** [comment] 2019-04-24 10:38
@pjkruger I had a timeout installing 9.3.1 on a low end server (not azure though) and 9.3.2 RC0 did install fine. We are progressing...

@OllyHodgson I guess we still need to improve this more, I know 9.4.x will have a few more enhancements to the install process, crossing fingers.

**Comment by idasbv** [comment] 2019-05-01 07:06
Same error here on a clean install of 9.3.1. (not azure)

**Comment by idasbv** [comment] 2019-05-01 07:31
Tried a clean 932 (9.3.2-rc0_install) install, again a timeout error:

18% ERROR occured - System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
 Add 1 row to dbo.[Languages]
 Add 5126 rows to dbo.[Lists] ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:e58e2691-2766-4649-aba1-d3657560915c
 Error Number:-2,State:0,Class:11
 
 DECLARE @CreateBy int = -1
 DECLARE @UpdateBy int = NULL
 DECLARE @UpdateByNotNull int = -1
 DECLARE @CreateOn datetime = {ts '2000-01-01 00:00:00'}
 DECLARE @UpdateOn datetime = NULL
 DECLARE @UpdateOnNotNull datetime = {ts '2000-01-01 00:00:00'}
 
 PRINT(N'Add 1 row to dbo.[Languages]')
 SET

**Comment by idasbv** [comment] 2019-05-01 08:17
went back to 9.2.2. and did clean install without errors

**Comment by OllyHodgson** [comment] 2019-05-01 19:29
9.3.2 Release worked for me too.

**Comment by valadas** [comment] 2019-07-29 05:58
There was some final improvements after the RC in this regards which I think solves this issue and I am closing it for that reason, you you can still reproduce using 9.3.2 official release, please open a new issue.

**Closed by valadas** 2019-07-29 05:58 UTC

**Comment by dush-a** [comment] 2021-03-05 14:28
It is back again in latest 9.9.0. Same error at 18% of the installation when I Install in shared hosting. 
But in local IIS in Windows 10 installation with the same MSQL server 2017 worked without a problem.
Is this mean we can't install DNN in to shared hosting anymore?

**Comment by sleupold** [comment] 2021-03-05 14:44
the original error (Timeout) sounds like a performance issue. If this happens ins hosting environment, there might be a performance lack of the shared SQL Server, being much slower than a local one, maybe due to not enough memory for caching.
