### ISSUE TITLE
Upgrade 9.11 HTML editor issue

### ISSUE THREAD

**Issue by rashidbilgrami** [dnnsoftware/Dnn.Platform#5483] opened 2023-01-14 16:17 UTC
After upgrading the 9.11 following error arriving while click on edit text in HTML editor 
An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Could not find stored procedure 'dbo.CKEditor_GetEditorHostSettings'. ---> System.Data.SqlClient.SqlException: Could not find stored procedure 'dbo.CKEditor_GetEditorHostSettings'. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior) at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args) at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args) at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteReader(String connectionString, CommandType commandType, Int32 commandTimeout, String procedureName, Object[] commandParameters) at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters) at WatchersNET.CKEditor.Utilities.Utility.GetEditorHostSettings() at WatchersNET.CKEditor.Web.CKEditorControl.LoadAllSettings() at WatchersNET.CKEditor.Web.CKEditorControl.CKEditorInit(Object sender, EventArgs e) at System.Web.UI.Control.OnInit(EventArgs e) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.AddedControl(Control control, Int32 index) at System.Web.UI.ControlCollection.Add(Control child) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace ---

**Comment by sleupold** [comment] 2023-01-14 16:40
which version of CKEditor provider are you using?

**Comment by rashidbilgrami** [comment] 2023-01-14 18:47
I have resolved issue by creating tables and sp in it 

CREATE TABLE [dbo].[CKEditorProviderSettings](
	[SettingName] [nvarchar](300) NOT NULL,
	[SettingValue] [ntext] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


Create PROCEDURE [dbo].[CKEditor_AddOrUpdateEditorHostSetting]
    @SettingName		nvarchar(300),
	@SettingValue		ntext
AS
    if exists (select 1 from dbo.CKEditorProviderSettings where SettingName = @SettingName)
	    begin
		    update dbo.CKEditorProviderSettings 
			   set
			       SettingValue = @SettingValue
			   where
			       SettingName = @SettingName
		end
    else 
	    begin
		    insert into dbo.CKEditorProviderSettings (SettingName, SettingValue) 
	                    values (@SettingName,@SettingValue)
		end


Create PROCEDURE [dbo].[CKEditor_DeleteAllChildPageSettings]
  @TabID int
	AS
	SET NOCOUNT ON
	DELETE  hs
  FROM dbo.CKEditorProviderSettings hs
  INNER JOIN	
		dbo.Tabs t  ON t.ParentId = @TabID
  Where SettingName like 'DNNCKT#%' AND t.TabID  = t.TabID


Create PROCEDURE [dbo].[CKEditor_DeleteAllModuleSettings]
  @PortalID varchar
	AS
	SET NOCOUNT ON
	Delete ms
  FROM dbo.ModuleSettings ms
  INNER JOIN	
		dbo.Modules m  ON m.PortalID = @PortalID
   Where SettingName like 'DNNCKMI#%' AND ms.ModuleID  = m.ModuleID


Create PROCEDURE [dbo].[CKEditor_DeleteAllModuleSettingsByTab]
  @TabID int
	AS
	SET NOCOUNT ON
	Delete ms
  FROM dbo.ModuleSettings ms
  INNER JOIN	
		dbo.TabModules tm  ON tm.TabID = @TabID
  Where SettingName like 'DNNCKMI#%' AND ms.ModuleID  = tm.ModuleID


Create PROCEDURE [dbo].[CKEditor_DeleteAllPageSettings]
  @PortalID varchar
	AS
	SET NOCOUNT ON
	DELETE  hs
  FROM dbo.CKEditorProviderSettings hs
  INNER JOIN	
		dbo.Tabs t  ON t.PortalID = @PortalID
   Where SettingName like 'DNNCKT#%' AND t.TabID  = t.TabID


Create PROCEDURE [dbo].[CKEditor_DeleteAllPortalSettings]
  @PortalID varchar
	AS
	SET NOCOUNT ON
	delete from dbo.CKEditorProviderSettings where SettingName like 'DNNCKP#' + @PortalID + '%'

Create PROCEDURE [dbo].[CKEditor_DeleteCurrentPageSettings]
  @TabID varchar
	AS
	SET NOCOUNT ON
	delete from dbo.CKEditorProviderSettings where SettingName like 'DNNCKT#' + @TabID + '%'

Create PROCEDURE [dbo].[CKEditor_GetEditorHostSettings]
  AS
	SET NOCOUNT ON
    SELECT SettingName,
	       SettingValue
    FROM dbo.CKEditorProviderSettings

**Comment by mitchelsellers** [comment] 2023-01-14 19:06
Based on these errors. It seems you had an upgrade failure at some point. 

We're there any errors when upgrading.

**Comment by valadas** [comment] 2023-01-18 23:38
I cannot reproduce this issue. I am closing it because there is nothing to to at this time, but you can keep commenting on it to further discuss it if you want. If it ends up we figure out a bug that is not a fluke, I'll reopen the issue when it is more actionable.

**Closed by valadas** 2023-01-18 23:38 UTC
Labels: Status: New
