### ISSUE TITLE
Full Editor Removing UL Classes

### ISSUE THREAD

**Issue by JaySMa** [dnnsoftware/Dnn.Platform#3139] opened 2019-10-10 16:16 UTC
## Description of bug
When editing the source HTML code within the HTML module using "Edit Content", the editor is removing the class of a UL.

## Steps to reproduce
Using the bloxfree skin (http://bloxxfree.t-worxsites.com/)
At the bottom in the footer, you see the "Featured Links" example.
The code is:
`<u l class="widget-links fa-ul">
....
</u l>`

Using this example and adding to the footer pane on my website, it's fine.
If I go into the module to edit the code for my words, links, etc., the editor at some point removes the "class" from the UL.  E.g.
`<u l>
...
</u l>`

## Current result
Removed the class look/feel of the UL.

## Expected result
The UL class shouldn't be removed.

## Error log
Nothing in the event logs.

## Affected version
* [ ] 10.0.0 nightly build
* [X] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by JaySMa** [comment] 2019-10-10 16:57
Even doing something for a parallax div, the editor REMOVES THE CODE.

`<div class="parallax parallaxGIS">&nbsp;</div>`

**Comment by JaySMa** [comment] 2019-10-11 15:43
And AGAIN, had the editor change code which I had originally posted into it.

And AGAIN, NO RESPONSES FROM OPS.  Seriously??!  This is a major issue since the editor is deciding what it's going to keep and remove everytime I try to edit my HTML code.

This is a MAJOR BUG!!!

`			<div id="cbp-so-scroller" class="cbp-so-scroller">
				<section class="cbp-so-section">
					<article class="cbp-so-side cbp-so-side-left">
						<h2>Lemon drops</h2>
						<p>Fruitcake toffee jujubes. Topping biscuit sesame snaps jelly caramels jujubes tiramisu fruitcake. Marzipan tart lemon drops chocolate sesame snaps jelly beans.</p>
					</article>
					<figure class="cbp-so-side cbp-so-side-right">
						<img src="images/1.png" alt="img01">
					</figure>
				</section>`

Changed to:
`<div class="cbp-so-scroller" id="cbp-so-scroller">
<h2>Appraisal / Value Assessment</h2>

<p>Fruitcake toffee jujubes. Topping biscuit sesame snaps jelly caramels jujubes tiramisu fruitcake. Marzipan tart lemon drops chocolate sesame snaps jelly beans.</p>

<p><img alt="img01" src="/portals/0/images/1.png" /></p>`

**Comment by mitchelsellers** [comment] 2019-10-11 23:29
Sadly, this is a behavior/trait of the CKEditor.  We don't have much control to adjust this.

**Comment by valadas** [comment] 2019-10-14 11:49
Hmm, I use the html editor quite often and the only times I notice stripping is when the content is not xhtml compliant. For instance, in your first example you have `<u l` instead of  `<ul`  and your second example starts with an opening div but then ends with a closing section.

Do you have other examples where it strips stuff away that is actually compliant?

**Comment by valadas** [comment] 2019-10-14 11:54
Oh, I can reproduce the second example though...

**Comment by valadas** [comment] 2019-10-14 12:11
Like Mitchel said, it is a CkEditor thing, now the setting for this is not exposed in the UI, but it is configurable by using a custom config file. I have no time now to look deeply into the default settings we use, but a temporary workaround would be to use zwnj instead of nbsp in empty nodes as such:

<div class="parallax parallaxGIS">&zwnj;</div>

**Comment by valadas** [comment] 2019-10-14 12:12
Also, since this improvement (exposing that setting in the UI) would need to go into the provider, I will close this issue here and recommend opening it at https://github.com/DNN-Connect/CKEditorProvider instead.

**Closed by valadas** 2019-10-14 12:12 UTC

**Comment by JaySMa** [comment] 2019-10-16 12:02
The reason I put in the spaces for the u l is that this would render the source code even after selecting "enter code" above.

**Comment by JaySMa** [comment] 2019-10-16 16:45
If anyone else is having this issue, look at the ticket I opened with the CKEditor hub;
https://github.com/DNN-Connect/CKEditorProvider/issues/129
