### ISSUE TITLE
Pages showing DNN Error and Site Assets like images use root folder favicon.ico for Browser Fav Icons

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3562] opened 2020-02-13 21:07 UTC
## Description of bug
I have noticed that when selected some pages or images the fav icon the browser detects is the root ico file instead of the portal uploaded ico file.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install DNN
2. Create Site
3. Upload A Favicon in Site Settings
4. Navigate to PERSONA BAR > MANAGE > SITE ASSETS and upload an image to a folder
5. View the image you uploaded.
6.  Notice there is the DNN fav ico instead of your portal fav ico file you uploaded showing in the browser.  Firefox best demonstrates the issue.
7. You can also then edit the link in your browser and add a character to the URL to create an Error page which will also use the root folder favicon.ico file instead of the portal fav icon uploaded in site settings.

## Current behavior
Favicon.ico in DNN Installation Root Folder is being used instead of Site Settings > Fav Icon uploaded when viewing error pages and site assets.

## Expected behavior
Use the uploaded fav icon file set in PERSONA BAR > SITE SETTINGS

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13577556/74478118-8ea20b00-4e61-11ea-8460-0986429f4ce7.png)

## Error information
No errors.

## Additional context
Maybe there is no way around this, then those icons need removed or a way to remove them from within the PERSONA BAR.

## Affected version

* [ ] 10.0.0 alpha build
* [x ] 9.5.0 alpha build
* [ x] 9.4.4 latest supported release

## Affected browser

* [x ] Chrome
* [ x] Firefox
* [ x] Safari
* [ x] Internet Explorer 11
* [x ] Microsoft Edge (Classic)
* [x ] Microsoft Edge Chromium

**Comment by valadas** [comment] 2020-02-14 00:20
Hmm, I am guessing the portal specific icon needs to go through some code that the error pages do not go thru by design and thus the root icon get's served as a static file...

**Comment by sleupold** [comment] 2020-02-14 11:42
I assume, the file is delivered by IIS and not passing the ASP.Net queue.
AFAIK, IIS always uses the favicon.ico in the root of the website.

**Comment by valadas** [comment] 2020-02-14 12:38
Yeah, I am going to close this issue as this is by design, trying to run more code in the error page could create more errors and make debugging hell. If anyone disagrees and has a solution feel free to comment and we can reopen

**Closed by valadas** 2020-02-14 12:38 UTC
Labels: Status: New
