### ISSUE TITLE
Site Settings, Default Pages doesn't load

### ISSUE THREAD

**Issue by Zeakk** [dnnsoftware/Dnn.Platform#2132] opened 2018-06-22 14:32 UTC
## Description 
https://dnntracker.atlassian.net/browse/DNN-9746?jql=text%20~%20%22portalId%3Dundefined%22

I found this reported on Stackoverflow.

http://stackoverflow.com/questions/43745038/dnn-upgrade-7-x-to-9-0-2-sitesettings-site-behavior-default-pages-control

I have the same issue. My site was upgraded from 7.2.2 to 9.1.0 using the recommended upgrade path.

My error is "There was an error retrieving your content. Please check your internet connection" appearing in a red bar at the top of the page, and nothing shown in the "Event Log."

## Affected version

* [x] 9.1.1

## Affected browser

* [x] Chrome

**Comment by valadas** [comment] 2019-07-23 20:16
Hi @Zeakk since this is for an older version, there is no clear way to reproduce and there was also some workarounds posted in the jira link, this issue is not actionable for now and I am closing it to cleanup the issues. My first advice would be to backup and upgrade. If not possible then looking into the browser console, the admin log and the portals/default/_logs folder for any clue that might help find more details. It looks like the original issue was localization related, maybe if you can outline clear steps to reproduce in the current version, we can make this an actionable issue.

**Closed by valadas** 2019-07-23 20:16 UTC
