### ISSUE TITLE
Why is JWT implementation internal? 

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#2138] opened 2018-06-27 10:31 UTC
We have implemented an alternate login to our custom specific DNN solution using electronic certificates which works fine. Now we want to utilize that in an API based on the DNN Service Framework and using JWT tokens so that after a successful authentication with electronic ids, we will call the class and have that issue the necessary token.However, to our surprise we noted that for some reason, the JwtController is marked as internal, meaning that this wont work (AFAIK), ie it can only be accessible using REST calls to the DNN Service Layer.internal class JwtController : ServiceLocator, IJwtController

Whats the reason for this? Is there a thought to it or just a mistake? I can't see any obvious advantages of it, and several disadvantages. The other authentication controllers in the Core seem to all be public. We changed that to "public" locally and just built that DLL and replaced the normal Dnn.AuthServices.Jwt.dll and that seems to work fine, but for obvious reason, having customized version of the core is not good. 

Is there a reason to this or should we just create a PullRequest for it to change?

https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs

**Comment by improwise** [comment] 2019-04-25 13:06
Whats the status here? Just looked in the code and it still seems to be internal which makes it impossible to use for any third party development which seems really unnecessary.

**Comment by improwise** [comment] 2019-04-25 13:14
@Behnam-Emamian @zyhfish 

Since you seem to be the latest contributors to this code, please comment if there is a reason not to change this to public?

**Comment by Behnam-Emamian** [comment] 2019-04-25 14:21
I don't know, In fact that implementation of JWT is not standard and It seems it was used for a mobile app. the password should not be dynamic.

**Comment by zyhfish** [comment] 2019-04-25 14:30
I guess this is just a "by design", as this module designed to communicate only with the WEB API but not let it can be accessed in code level, it needs self-managed of these sense info but not expose them cause out of control.

**Comment by improwise** [comment] 2019-04-25 15:06
The problem is that if you want to use some other kind of mechanism for authentication, like in our case, Electronic IDs you can't issue a JWT token that is recognized by DNN in a standard way. Seems like this would not be a problem if the class was public. We even tried this by changing the source code locally and recompile, but of course that is not a long term solution.

**Comment by valadas** [comment] 2019-07-23 20:33
@dnnsoftware/tag opinions on this, is it required by design or could this be an enhancement?

**Comment by valadas** [comment] 2019-09-18 04:49
In the spirit of cleaning up the backlog and since there was no other discussions since July, i am closing this issue for now. It looks like this is by design and would involve some risk.

**Closed by valadas** 2019-09-18 04:49 UTC
Labels: Pending Verification

**Comment by david-poindexter** [comment] 2019-09-18 14:07
@improwise we use DNN as a backend for mobile apps all the time, but the JWT implementation is intended and documented to be used only via DNN WebAPI.  See https://dnndocs.com/content/features/jwt/index.html for more information.
