### ISSUE TITLE
Import/Export Issue if export directory is renamed

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#3076] opened 2018-12-03 20:52 UTC
-->

## Description of bug
If Export/Import is used to export a portal and then the created directory is renamed, that directory cannot be used to Import the portal.

## Steps to reproduce
List the steps to reproduce the behavior:
1.Settings, Export/Import in the Persona Bar
2. Click on 'Export Data'
3. Fill out the form and export the portal.
4. In the server's file manager, rename the export directory created in App_Data/ExportImport
5.Settings, Export/Import in the Persona Bar
6. Click on 'Import Data'
7. Select the data exported earlier and click "Continue"

## Current result
This appears in a red bar that appears.
"There was an error retrieving your content. Please check your internet connection."

## Expected result
The import should happen correctly.  Renaming the directory -- say to give it a more useful name -- should not affect importing.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Nothing is logged.

## Additional context
When Import is selected, the directory is shown with the original name.  I'd guess that this is because the directory is stored in the database, but not changed.  App_Data/ExportImport is also not included when synchronization is done.  But I'm not sure where this is stored.

Also, it's not clear to me if there is also an interaction with the scheduled task that does the work.  The default installation sets that to run once a day.  Does starting an import also start up the scheduled task?

## Affected version

* [x] 9.2.2
* [] 9.2.1
* [] 9.2
* [] 9.1.1
* [ ] 9.1
* [ ] 9.0

I only checked 9.2.2, and I think that Export/Import may be new to 9.2.2

## Affected browser
N/A

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment] 2019-11-05 12:14
Closing this issue since it is by design and nobody stepped up to indicate they wanted to tackle this, if anyone wants to, feel free to comment or reopen

**Closed by valadas** 2019-11-05 12:14 UTC
