### ISSUE TITLE
Main menu does not work on phone layout

### ISSUE THREAD

**Issue by brianbonk** [dnnsoftware/Dnn.Platform#3804] opened 2020-06-01 19:52 UTC
## Description of bug
Platform 9.6.1 the main menu does not work on phone layouts on iPhones (tested on iPhone 11 latest iOS).

## Steps to reproduce

To test and reproduce please visit www.vfr.dk from an iPhone.
No need to login - the main menu (in Denmark called “burger menu”) - does not work here after update to 9.6.1.
iPhone needs to be in vertical position.

## Current behavior 
The menu does not open when clicked from safari on iPhone.

## Expected behavior
The menu would open when clicked from safari on iPhone.
## Affected version
* [ ] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release

## Affected browser
* [ ] Chrome
* [ ] Firefox
* [X] Safari (iPhone)
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by james7342** [comment] 2020-06-05 09:44
Looks like you've ran into these issues.

https://github.com/dnnsoftware/Dnn.Platform/issues/3732
https://github.com/dnnsoftware/Dnn.Platform/pull/3729

I would take a look at the jQuery versions being used

**Comment by valadas** [comment] 2020-06-05 16:37
Could it be you installed the RC on production. This was resolved during the RC stage if I remember correctly, you should have jQuery 3.5.1

Go to Extensions and select Javascript Libraries in the dropdown.
Look if you have jQuery 3.5.0 or jQuery 3.5.1 listed
If you have jQuery 3.5.0 something went wrong and either the RC was installed instead of the official release or something went wrong with the install.

My first recommendation if that is the case is to restore the backup before the upgrade and run the upgrade again.

If that is totally not possible a second less recommendable way to fix this is to install just the new jQuery version using this package:
[jQuery_03.05.01_Install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4737408/jQuery_03.05.01_Install.zip)

**Comment by valadas** [comment] 2020-06-05 16:38
I am closing this issue because I was not able to reproduce on a clean install/upgrade but feel free to comment if you have other questions or discover something else.

**Closed by valadas** 2020-06-05 16:38 UTC
Labels: Status: New
