### ISSUE TITLE
No Site Assets and Global Assets after upgrade to DNN 9.11.00 (228)

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#5251] opened 2022-09-01 08:51 UTC
## Description of bug
Upgraded from DNN 09.10.2 to 09.11.00 and now the Site/blobal Settings is empty.
Module is on the page but is empty

## Steps to reproduce
List the precise steps to reproduce the bug:
1. extract upgrade package;
2. ran the upgrade wizard (no issues);
3. open website
4. open site Assets page

## Current behavior
no file manager

## Expected behavior
there should be a file manager

## Screenshots
![image](https://user-images.githubusercontent.com/7567981/187873044-4a920054-1e84-4aaa-808e-84528da7714c.png)

## Error information
![image](https://user-images.githubusercontent.com/7567981/187873490-ca826417-78b6-4737-9e9c-e0926375a115.png)

## Affected version
* [ ] 09.11.00 latest supported release

## Affected browser
all

**Comment by vmasanas** [comment] 2022-09-01 09:28
Done a clean install and have the same issue

**Comment by stetard** [comment] 2022-09-01 09:54
I think it's a duplicate of #5250: issue exists for new install and when upgrading too.

**Comment by bdukes** [comment] 2022-09-01 13:07
@valadas @donker it looks like we're missing `html` and `js` files from the Resource Manager package, any idea what might be going on?

![screenshot of 7-Zip showing resources from Resource Manager install zip](https://user-images.githubusercontent.com/59507/187921144-ab968c07-fcb6-41a1-9f6a-9b270ea333fb.png)

**Comment by valadas** [comment] 2022-09-01 14:53
Must be some build issue, I will investigate further tonight. In the meantime you can use this zip to re-install it after the site is started
[DNNCE_ResourceManager_09.11.00_Install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/9470939/DNNCE_ResourceManager_09.11.00_Install.zip)

**Comment by Plumifrons** [comment] 2022-09-01 22:16
Reinstalling DNNCE_ResourceManager_09.11.00_Install.zip didn't help. The module remains empty.

<img width="106" alt="RCM1" src="https://user-images.githubusercontent.com/5980007/188022267-bc9f4e16-745e-4558-9e90-4e625d8a2b9b.png">

**Comment by valadas** [comment] 2022-09-02 01:48
Ok, so here is RC2 which should solve this problem, I'll close this issue but if you still have problems with rc2, feel free to comment and I'll reopon it.

https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc2

**Closed by valadas** 2022-09-02 01:48 UTC
Labels: Status: New

**Comment by wbonekamp** [comment] 2022-09-05 07:33
Upgraded to RC3 but still no Resource Manager... how can I get it back...?

**Comment by valadas** [comment] 2022-09-05 07:51
Let's track this under #5265 I have a good idea of what's happening and will provide a fix shortly for rc4...
