### ISSUE TITLE
Unable to create a portal in 9.2.2

### ISSUE THREAD

**Issue by michael-deacon** [dnnsoftware/Dnn.Platform#2675] opened 2019-04-08 07:44 UTC
## Description of bug
Unable to create a portal under DNN 9.2.2 Manage Sites

## Steps to reproduce
1. Go to Manage -> Sites
2. Click on Add New Site
3. Fill in the Title, and the Site URL,
4. Uncheck Assign Current User as Administrator
5. Fill in the administrator details
6. Click on Create Site

## Current result
Does not show any errors, but the new site is not added to the list

## Expected result
A new portal is created and added to the list.

## Error log
DotNetNuke.Services.Exceptions.Exceptions - System.Net.Mail.SmtpException: Client does not have permission to submit mail to this server. The server response was: 4.7.1 <host@host.me>: Relay access denied
   at System.Net.Mail.RecipientCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at DotNetNuke.Services.Mail.Mail.SendMailInternal(MailMessage mailMessage, String subject, String body, MailPriority priority, MailFormat bodyFormat, Encoding bodyEncoding, IEnumerable`1 attachments, String smtpServer, String smtpAuthentication, String smtpUsername, String smtpPassword, Boolean smtpEnableSSL)

## Additional context
The new site can be seen on the Settings -> Site Settings page in the editing site drop down list, but selecting it does not do anything. There is a JavaScript error 
Uncaught TypeError: Cannot read property 'Code' of undefined
    at t.value (<anonymous>:13:25245)
    at <anonymous>:13:23692
    at <anonymous>:4:25347
    at Object.success (sf.js?cdv=139&t=0.42558049905290396:51)
    at i (jquery.js?cdv=139&t=0.42558049905290396:3)
    at Object.fireWith [as resolveWith] (jquery.js?cdv=139&t=0.42558049905290396:3)
    at A (jquery.js?cdv=139&t=0.42558049905290396:11)
    at XMLHttpRequest.<anonymous> (jquery.js?cdv=139&t=0.42558049905290396:11)

 There is no entry created in the PortalAlias table and it's not possible to browse the new site.

## Affected version

* [  ] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [  ] 9.1
* [  ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment] 2019-04-08 07:55
The first part of this problem is probably caused by the mail server relay refusing to send the email on behalf of host@host.me, the host email address can be edited in the HostSettings table in Dnn 9.2.2 or if you upgrade to 9.3.1, it is in the mail server settings UI. The second part may or may not be caused by the first issue if the process did not complete correctly and all the portal data was not properly saved due to it...

I would recommend backing up, then upgrade to 9.3.1, change that host email, delete and try to recreate the portal. Then report back if there is still an issue.

**Comment by valadas** [comment] 2019-07-29 06:52
Closing this issue since there was no further discussion for some months. @michael-deacon if this is still an issue on current versions and after checking the host email as suggested, please open a new issue. Thanks.

**Closed by valadas** 2019-07-29 06:52 UTC
