### ISSUE TITLE
NewtonSoft

### ISSUE THREAD

**Issue by doodlleus** [dnnsoftware/Dnn.Platform#2121] opened 2018-06-14 11:51 UTC
The upgrade package does not include the newtonsoft.json.dll library which causes the upgrade to break if you do not already have v10.0.0.0 installed of the lib. The main install package contains it though

**Comment by mitchelsellers** [comment] 2018-06-14 12:57
Can I confirm that this is an issue with 9.2.0?

**Comment by doodlleus** [comment] 2018-06-14 13:16
That's correct, specifically the upgrade zip

**Comment by ohine** [comment] 2018-06-14 15:03
It appears the install zip contains `Newtonsoft.Json.dll` v10.0.3.21018 in the `/bin` directory and the `Newtonsoft.Json_10.00.03_Install.zip` in the `/Install/Module` folder. 

The upgrade zip only contains `Newtonsoft.Json_10.00.03_Install.zip` in the `/Install/Module` folder. 

I won't be able to test this right now, as I don't have that much time at the moment. I'm guessing however that the installer/upgrader won't function on the older version of Newtonsoft.Json.dll from the previous version they are attempting to upgrade. 

Also, in PR #1837 the 09.02.00.SqlDataProvider file https://github.com/dnnsoftware/Dnn.Platform/blob/482c35cf6552b8fb2090ac7c25fa9100d64fe06a/Website/Providers/DataProviders/SqlDataProvider/09.02.00.SqlDataProvider#L107-L118 the platform is updating the assembly version of `Newtonsoft.Json.dll`. I believe if this is updated before the `/Install/Module/Newtonsoft.Json_10.00.03_Install.zip`, there is a chance it'll skip copying the assembly because the DB version is the same. Unless the installer is using the repair flag on the api. Again, I wasn't able to test these theory's, but hopefully it'll help someone else from @dnnsoftware/tag dig a bit deeper to see what the root cause and proper solution might be. 

It looks like we need to either back out the changes to the web.config and assembly tables and handle all of that with the extension package for newtonsoft. Or remove the extension package and just include the binary in the bin directory directly and bump the assembly in the platform. It's weird right now we have a mix of both.

Any idea why this was done this way? @ashishpd @zyhfish @tpluscode

**Comment by bdukes** [comment] 2018-06-14 15:09
We need to assembly to be installed via installer, rather than included in the `bin/`, because a difference in version can cause the site to break due to a mismatch with binding redirects.  The installer will update the binding redirect at the same time as updating the file in the `bin/`.

I think you're right, @ohine, that updating the `Assemblies` row in the database would prevent the assembly file from getting copied to the `bin/`.

**Comment by bdukes** [comment] 2018-06-21 14:34
The simple solution is to set the version to 10.0.2 via the 9.2.1 SQL script, if it's already 10.0.3, but that's going to require some good documentation to avoid confusing folks looking back on it.

That said, I don't have any other solutions that I like better.  Maybe we could run some code in `Upgrade.cs` which does a repair install of the package, but there are timing issues we may have to contend with there.

**Comment by bdukes** [comment] 2018-08-06 15:16
@ohine We're on the wrong trail here.  The change you highlight was removed during testing (1829d1810e6ca6476302669060717c3c9b1f2d86) and is not part of the 9.2.0 package  

I don't see this issue doing an upgrade from a plain 9.1.1 site to 9.2.0, and looking at the errors on https://www.dnnsoftware.com/forums/forumid/200/threadid/542050/scope/posts it looks like Newtonsoft is just one part of it.  I've tracked down the issue that caused them to install it this way: [DNN-10226](https://dnntracker.atlassian.net/browse/DNN-10226), but I'm not sure how this was handled with earlier Newtonsoft upgrades.

I know DnnSharp includes their own version of Newtonsoft, using the [`<codebase>` element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/codebase-element), and I'm wondering if there's something that doesn't work if that's in the config (which would explain why it's not an issue we're hearing more about).

**Comment by ohine** [comment] 2018-08-09 01:59
@bdukes Thanks for taking the time to dig into this one a bit more. It sounds like we need to do some testing with DnnSharp next and work on reproducing the issue to see what we can do. I can get this into my schedule for the 9.3 release, I highly doubt I'd have the time for 9.2.2. If anyone else from @dnnsoftware/tag has a few extra cycles, it would be helpful to try and get this resolved in 9.2.2 if at all possible.

**Comment by schotman** [comment] 2018-08-20 11:58
In my case: Upgrading from 9.1.1 tot 9.2.1 with the latest and greatest from DNNSharp results in an error installing the NewtonSoft 1.0.3. module. I had to manually copy the new dll to the bin\NewtonSoft.Json-8.0.0.0 directory and change the directive in the web.config. 

When installing ActionForm (5.0.155, latest at this time) it will add the following to the web.config:       <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <codeBase version="8.0.0.0" href="bin/NewtonSoft.Json-8.0.0.0/Newtonsoft.Json.dll" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="dotnetnuke.log4net" publicKeyToken="53eb1fac7b60111f" />
        <codeBase version="3.0.0.0" href="bin\dnnsharp\DotNetNuke.Log4Net.dll" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="SharpZipLib" publicKeyToken="1b03e6acf1164f73" />
        <codeBase version="0.81.0.1407" href="bin\ICSharpCode.SharpZipLib.dll" />
      </dependentAssembly>

when upgrading DNN911 to 921 it results in a incompatibility

**Comment by dimarobert** [comment] 2018-08-27 14:00
@bdukes @ohine 
I debugged through the upgrade process of the Newtonsoft library. Here is what I found:
The DNN manifest file has two components (in this order):
1. Assembly component 
2. Config component

The installer executes the Assembly component installer that copies the newtonsoft.json.dll version 10.0.3 in bin folder and then calls [`AddOrUpdateBindingRedirect()`](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs#L194) which updates the `web.config` with the binding redirect to 10.0.3.
Then, the Config installer is executed which updates the `web.config` with the assembly binding once more.

The issue with DnnSharp's `<codebase>` assembly binding (and maybe other vendors) is in that second step of the install process. The [`path`](https://github.com/dnnsoftware/Dnn.Platform/blob/1829d1810e6ca6476302669060717c3c9b1f2d86/DNN%20Platform/Components/Newtonsoft/DotNetNuke.Newtonsoft.Json.dnn#L33) attribute set in the Newtonsoft package to update the binding redirect is not specific enough and doesn't take into consideration that there could be other `dependentAssembly` elements in `web.config` for newtonsoft. It targets the first `ab:dependentAssembly` element with `@name='Newtonsoft.Json'`.

In a clean DNN pre 9.2.0 the `<assemblyBinding>` element contains only one `dependentAssembly`:
``` XML
<dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
</dependentAssembly>
```

When installing any DnnSharp module the `assemblyBinding` changes to:
``` XML
<dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
</dependentAssembly>
...
<dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
    <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
</dependentAssembly>
```

After the AssemblyInstaller is executed the `web.config` changes to (note the order of the elements):
``` XML
<dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
    <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
</dependentAssembly>
...
<dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
    <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />
</dependentAssembly>
```

Now it is ConfigInstaller turn to update the `web.config`. It [searches](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Installer/XmlMerge.cs#L250) for the dependentAssembly with path `/configuration/runtime/ab:assemblyBinding/ab:dependentAssembly[ab:assemblyIdentity/@name='Newtonsoft.Json']` which matches the first one (DnnSharp's one). Then it [searches](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Installer/XmlMerge.cs#L531) for the target node with `/configuration/runtime/ab:assemblyBinding/ab:dependentAssembly[ab:assemblyIdentity/@name='Newtonsoft.Json']/ab:bindingRedirect` which matches the `bindingRedirect` of the second `dependentAssembly` (the one added earlier by AssemblyInstaller). Next it tries to [remove](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Installer/XmlMerge.cs#L561) the `bindingRedirect` of the second dependentAssembly from the first dependentAssembly. This throws a `System.ArgumentException` with message `The node to be removed is not a child of this node.`

### Solution

There are two solutions:
1. Strengthen the path's XPath like this: `/configuration/runtime/ab:assemblyBinding/ab:dependentAssembly[ab:assemblyIdentity/@name='Newtonsoft.Json' and ab:bindingRedirect]`. This will prevent mismatching rootNode / targetNode elements between codabase and bindingRedirect bindings. There could be other bindingRedirect bindings that could interfere with this.
2. Add an additional Config component before the existing one that removes all the bindingRedirects for older newtonsoft assemblies **but not the codabase bindings**. Then, the existing Config component will insert an bindingRedirect only if there is no bindingRedirect for version 10. There could be unforeseen issues with this approach.

I am willing to submit a pull request with what you think would be the best solution.
If you think that a better approach is to fix this in our modules, we (DnnSharp) are open to discussion if you think that we are the only vendor that does this.

Please let me know what your thoughts are on the matter.

**Comment by bdukes** [comment] 2018-08-27 14:09
Thanks for digging into this more @dimarobert!  I definitely think DNN should be able to handle the `codebase` redirect that y'all use.

Regarding your proposed fixes, would it work to just _remove_ the Config component from the Newtonsoft package, since the platform is already adding the redirect correctly?  Is there any reason it needs to be in both places?

If there's a reason to target the redirect via XmlMerge, I think strengthening the XPath is the right solution.

**Comment by dimarobert** [comment] 2018-08-27 15:11
@bdukes For the upgrade scenario, it should be just fine if we remove the Config component. I will have to do a clean install of DNN  9.2.1 to see if there could be issues there.

From an initial check I see that there is a newtonsoft.json.dll in bin and the bindingRedirect in the  `web.config` from the install package is diffrent from the one in the upgrade:
``` XML 
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
</dependentAssembly>
```

Also there is a Newtonsoft module zip in the `/Install/Modules` folder. If that is installed as part of the setup process then the web.config should be updated with the `oldVersion="0.0.0.0-32767.32767.32767.32767"` part.

**Comment by schotman** [comment] 2018-08-27 15:14
@bdukes 

Some remarks:
- when updating a dnn9.1.1 installation with DNNSharp AF installed, the installation of the newtonsoft installer package (in /install/modules) results in an error. 
As a result the dll is not copied into the bin. However the assembly binding section in the web.config is changed to:         <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />

There now are two rebinding rules as mentioned by @dimarobert:

`      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
      </dependentAssembly>
      
      
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />
      </dependentAssembly>`

Removing the following assemblybinding: 
`      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />
      </dependentAssembly>`

should result in the use of the first, however the site still crashes. I assume DNN requires Newtonsoft.Json version 10. 

Thus we got at least two issues:

- when installing a module results in an error, web.config changes are not rolled back
- installing Newtonsoft.Json as a seperate/independent module is questionable because DNN relies on it

**Comment by bdukes** [comment] 2018-08-27 15:26
@dimarobert the thought behind the version range used is that any component which is expecting to use _Newtonsoft.Json_ (or any other strong-named assembly) should be able to use the installed version (i.e. the version of the file in the `bin` folder).  

The alternative would be that .NET just refuses to run the code, because _Newtonsoft.Json_ 10 is in the `bin` folder but the component was compiled against version 11.

**Comment by dimarobert** [comment] 2018-08-27 17:48
@bdukes Both the [Newtonsoft upgrade step](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Upgrade/Upgrade.cs#L5972) and the [InstallExtensionsStep](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Upgrade/Internals/Steps/InstallExtensionsStep.cs#L68) in the clean install calls the `Upgrade.InstallPackage()` method which does a [RepairInstall](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Upgrade/Upgrade.cs#L4833) of the package and the `web.config` ends up being the same at the end.

``` XML
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
  <!--Upgraded by DotNetNuke.Newtonsoft.Json version 10.0.3 - Date: 8/27/2018 8:33:54 PM-->
  <!--<bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />-->
  <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />
</dependentAssembly>
```
In both cases the bindingRedirect is updated twice. So I think that removing the Config component could be a solution.

Can you think of any other scenario for the Newtonsoft.Json zip installation?

**Comment by bdukes** [comment] 2018-08-27 17:51
Nothing comes to mind, I think that's the right path forward.

**Comment by dimarobert** [comment] 2018-08-29 07:04
@bdukes I've come up with another situation. If the web.config is initially in this state (in opposite order):
``` XML
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
  <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
</dependentAssembly>
```

After the installation of the modified Newtonsoft.Json package (without the Config component) the web.config looks like this:
``` XML
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
</dependentAssembly>
<!--Upgraded by DotNetNuke.Newtonsoft.Json version 10.0.3 - Date: 8/28/2018 11:55:01 PM-->
<!--<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1"><assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" /><codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" /></dependentAssembly>-->
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
  <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
  <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
</dependentAssembly>
```

The upgrade process went without any issue, but do you think that this could be an issue in the future?

**Comment by bdukes** [comment] 2018-08-29 13:47
@dimarobert I don't think that'll cause any major issues, but we should be able to resolve the ambiguity and fix this issue for good.  I've pushed a change to your PR which I believe should do that.

**Closed** 2018-09-14 02:29 UTC
Labels: Bug

**Comment by Tychodewaard** [comment] 2018-10-30 20:08
Kinda lost here...I just upgraded a small site from 804 to 922. I figured this issue would be solved in 922. But unfortunately not: see error below. 
Any suggestions what my next step should be or how to solve this?


[FileLoadException: Could not load file or assembly 'Newtonsoft.Json' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]  [FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0    System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +36    System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +152    System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +77    System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +21    System.Reflection.Assembly.Load(String assemblyString) +28    System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +38  [ConfigurationErrorsException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +738    System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +217    System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +130    System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +170    System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +92    System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +290    System.Web.Compilation.BuildManager.ExecutePreAppStart() +157    System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +549  [HttpException (0x80004005): Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10074636    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
--

**Comment by Tychodewaard** [comment] 2018-10-30 20:10
In the web.config the lines with newtonsoft are:
	Line 376:         <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
	Line 377:         <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
	Line 377:         <codeBase version="8.0.0.0" href="bin\NewtonSoft.Json-8.0.0.0\Newtonsoft.Json.dll" />
	Line 481:       
	Line 482:       
	Line 484:         <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
	Line 491:       
	Line 492:       
	Line 492:       
	Line 492:       
	Line 494:         <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />

**Comment by sleupold** [comment] 2018-10-30 20:11
did you clear local browser cache?

**Comment by Tychodewaard** [comment] 2018-10-30 20:13
No need, uptimerobot also sees the website is down. You can check http://www.bydaans.nl/ yourself

**Comment by bdukes** [comment] 2018-10-30 20:15
Your web.config should only have one `dependentAssembly` for `Newtonsoft.Json` that has a `bindingRedirect` inside it (rather than a `codeBase`), and the `newVersion` attribute in that should match the version in the `bin/`, probably it should be this:

```
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
  <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0.0" />
</dependentAssembly>
```

**Comment by Tychodewaard** [comment] 2018-10-30 20:31
I deleted some and kept:
      
      
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.0" />
      </dependentAssembly>
This did not change the error.

As it says in the comments, DNN upgraded to 10..3, I changed the web.config to:
      
      
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="10.0.3" />
      </dependentAssembly>

This created another error but that is probably related to a module, so...I think I can move on...
