### ISSUE TITLE
Users get validated without using the link in the Email, and remains logged into the portal after their registration without valid authorization

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2256] opened 2018-08-20 13:23 UTC
## Description 

We received this report from customer support:

> A customer needs to set up a registration in which users create themselves their username and passwords, and then they get an email with a validation link that allows them to sign into the site.
> 
> Opposite to that, once they fill the form to create a new user, the user auto-logs into the portal and after they receive an email with a validation link, that is useless because it's an 'Obsolete' link.

## Steps to reproduce

- Create a form that allows the user to create himself an account. 
- Set to "Validate by email" the registration, in registration settings. 
- Wait for the email to get your inbox. 
- Open the email from DNN and check the link to validate the account.

## Current result

- The user remains validated in the portal without open the link to validate as well. 
- When the Email gets the inbox, the validation link is expired. 

## Expected result

- The user shouldnt be allowed to log into the portal until he gets validated by clicking on the link that comes in the email. 
- The link should have a time out of 1 or 2 hours. (The time in the settings for the link to expires is 60 minutes. I tried to set it to 600 for testing purposes, nothing changed)

## Affected version

* [x] 9.2.1
* [x] 9.2.0
* [x] 9.1.1

**Comment by mitchelsellers** [comment] 2018-08-20 18:55
I believe the proper behavior here would be for the user to not be logged in post registration, prior to account validation.

**Comment by valadas** [comment] 2018-08-21 03:52
Yes, I totally agree, when the registration mode is verified, the account should first be validated. I _think_ this may be an error introduced with the feature to required a valid profile for login, where users need to have a valid profile and be verified too, so they are auto-logged-in to fill their profile. I _think_

**Comment by tpluscode** [comment] 2018-08-21 11:52
You, @valadas, you say that it's not always been like that?

**Comment by bdukes** [comment] 2018-08-21 13:51
DNN 6.2 introduced the _Unverified Users_ role, which allows users to login to a restricted set of functionality after registering on a site with verified registration.

My [recommendation in 2013](https://stackoverflow.com/a/17087029/2688) was to set the permissions on every page to required the _Registered Users_ role.  I think adding an option which restricts login for unverified users would be useful for many scenarios.

**Comment by Mohtshum** [comment] 2018-08-21 13:52
This issue is present in 
engage 
> 9.1.1
> 8.5
dotnetnuke professional 6.2.4

**Comment by valadas** [comment] 2018-08-23 16:42
@tpluscode I did not have time to properly test, but my comment was mainly that the behaviour may be different depending if the "require valid profile for login" is on or off. I did not use verified registration much but when testing on this issue we need to also consider the valid profile option at the same time.

**Comment by Mohtshum** [comment] 2018-08-27 07:30
@All Currently only application generated pages have "View" permission for "All Users" role including Profile, Messages. While any new page does'nt have any permission for role "All Users" hence no permission for "Registered Users" and "Unverified Users". 
While setting permission for auto-generated pages is one time job for Host user including Profile, Messages and any other page either to restrict or allow. 
I think it is correct behavior and this should be "Function as Design"

**Comment by tpluscode** [comment] 2018-08-31 08:44
Seems we do not have consensus here. I tend to lean towards keeping current behaviour. Restricting access to "Unverified Users" does sound like a viable workaround

**Comment by valadas** [comment] 2019-07-27 13:28
Since there is an "Unverified Users" role and as per @Mohtshum comment, this appears to be by design, I am closing this issue. If I am wrong, please reopen or comment.

**Closed by valadas** 2019-07-27 13:28 UTC
Labels: esw
