### ISSUE TITLE
Current version of webpack-dev-server fails on build.

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3272] opened 2019-11-10 19:47 UTC
i after run `yarn webpack` received error in console. 
Error is:
```
Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- D:\PersianDnn\Dnn.Platform\Dnn.AdminExperience\Extensions\Content\Dnn.PersonaBar.Extensions\WebApps\Roles.Web\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\PersianDnn\Dnn.Platform\Dnn.AdminExperience\Extensions\Content\Dnn.PersonaBar.Extensions\WebApps\Roles.Web\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\PersianDnn\\Dnn.Platform\\Dnn.AdminExperience\\Extensions\\Content\\Dnn.PersonaBar.Extensions\\WebApps\\Roles.Web\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Steps:
![Untitled](https://user-images.githubusercontent.com/9780304/68549685-3990cc00-0410-11ea-9f7b-93dd4e9de7b5.png)

**Comment by valadas** [comment] 2019-11-10 19:51
Did you run yarn install first ?

**Comment by valadas** [comment] 2019-11-10 19:52
Oh, sorry, just saw the screenshot after the comment...

**Comment by valadas** [comment] 2019-11-10 19:57
Ok, can you got back to the root workspace /Dnn.AdminExperience/ and run yarn install then go into the subfolder and try yarn webpack again...

**Comment by mnouraei** [comment] 2019-11-10 20:04
Ok, I will try and announce the result

**Comment by mnouraei** [comment] 2019-11-11 07:23
> Ok, can you got back to the root workspace /Dnn.AdminExperience/ and run yarn install then go into the subfolder and try yarn webpack again...

this doesn't work, but i copy `webpack-cli` from `AdminLogs.Web\node_modules\webpack-cli` into `WebApps\Roles.Web\node_modules` worked

**Comment by valadas** [comment] 2019-11-11 10:23
I was able to reproduce the issue, looks like this is an issue with webpack and we need to update it's version. After upgrading webpack to 4.31.0 I was able to build without this error, however I did not do extensive testing with this upgrade... I am changing the title of the issue for that reason.

**Comment by valadas** [comment] 2020-07-28 23:38
There was a huge build reorganization done since this issue was last visited. I don't think this is a problem anymore with the new build instructions. I am closing this issue for that reason.

**Closed by valadas** 2020-07-28 23:38 UTC
Labels: Type: Build/Release
