### ISSUE TITLE
9.9.0 SQL Console throws 404-Not Found console error

### ISSUE THREAD

**Issue by TopCat6** [dnnsoftware/Dnn.Platform#4538] opened 2021-03-03 22:58 UTC
## Description of bug
Provide a clear and concise description of the bug.
SQL Console does not display data entry field and produces console error 
## Steps to reproduce
List the precise steps to reproduce the bug:
1. Configure IIS with DNN files located in C:\DotNetNuke\Website
2. Login as Host
3. Go to 'Settings, SQL Console'
4. Notice there is no number 1 displayed and no place to start typing in the SQL code.
5. See error in browser console.

## Current behavior
Explain the current behavior.
Cannot type into SQL Console
## Expected behavior
Provide a clear and concise description of the expected behavior.
Should be able to type into SQL Console
## Screenshots
If applicable, provide screenshots to help explain the bug.

![image](https://user-images.githubusercontent.com/17517455/109882068-2372d480-7c2e-11eb-8d0f-3cc983d05786.png)
![image](https://user-images.githubusercontent.com/17517455/109883837-db08e600-7c30-11eb-9262-0202aa5edfa6.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.
Please see console errors in first image, above. Also see next section.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.
URLs are wrong. This is what is being used:
```
Requested URL	   http://localhost:80/Resources/Shared/components/MonacoEditor/loader.js
Physical Path	   C:\inetpub\wwwroot\Resources\Shared\components\MonacoEditor\loader.js
```

**Should be:**
```
Requested URL	   http://localhost:80/DotNetNuke/Resources/Shared/components/MonacoEditor/loader.js
Physical Path	   C:\DotNetNuke\Website\Resources\Shared\components\MonacoEditor\loader.js
```

Second error produced by this wrong URL:
```
Requested URL	   http://localhost:80/Resources/Shared/components/MonacoEditor/editor/editor.main.js?cdv=1574
Physical Path	   C:\inetpub\wwwroot\Resources\Shared\components\MonacoEditor\editor\editor.main.js
```

**Should be:**
```
Requested URL	   http://localhost:80/DotNetNuke/Resources/Shared/components/MonacoEditor/editor/editor.main.js?cdv=1574
Physical Path	   C:\DotNetNuke\Website\Resources\Shared\components\MonacoEditor\editor\editor.main.js
```

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.09.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by bdukes** [comment] 2021-03-03 23:06
Thanks for this bug report!

This issue is a duplicate of #4411 (the current integration of the Monaco editor does not support DNN when deployed to a folder).

**Comment by TopCat6** [comment] 2021-03-04 01:09
Whoops, I missed that one. Sorry for the duplicate.

**Comment by valadas** [comment] 2021-10-05 00:38
Closing this one in favor of #4411

**Closed by valadas** 2021-10-05 00:38 UTC
Labels: Status: Review
