### ISSUE TITLE
New User Can't Register When Region is Required

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#2164] opened 2018-07-17 00:46 UTC
## Description 
When a new user tries to register, and the Region and Country are set to required in the user account settings > profile settings, once you click on the Register button, it clears the Region field and says "Region is required".

Example: "United States" is selected for Country. Once "United States" is selected, the region field does not change to a pulldown, but remains a fillable text field. Entering any value such as "Massachusetts" or "MA" and then clicking on the Register button causes the field to be cleared and the "Region is required" error message to appear.

Reference Jira:  https://dnntracker.atlassian.net/browse/DNN-7063

## Steps to reproduce
1. Clean instance of DNN 9.1.1.
2. Configure the user profile to require the address, and specifically, the region when registering.
3. In another browser (or in incognito mode), register a new user account.

## Current result
No matter what country you choose, the region text box and drop-down list is required and never successfully validated regardless of the selected/entered value.  The registration is not allowed to continue.

## Expected result
The selected/entered region is valid and the user account is registered.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment] 2018-07-17 03:38
Could this be related to #2146 and #2140 ?

**Comment by sleupold** [comment] 2018-10-07 10:29
has this been fixed with re-order of fields (country prior region)?

**Comment by valadas** [comment] 2019-07-27 07:28
I was not able to reproduce in 9.4.0 rc, so assuming this is now resolved with the linked issues/PRs and closing this one.

**Closed by valadas** 2019-07-27 07:28 UTC
