### ISSUE TITLE
New site import not backward compatible..

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#2610] opened 2019-03-06 06:52 UTC
## Description of bug
If you use a third party module, that works for import and export in DNN8.  In DNN9 the new code for the import of a site will not take the old module data format.

I can take the same module, do an export of the data into a file from the DNN module menu and then import it into another module and it works.

https://github.com/nbrightproject/NBrightMod

If I use the same module with the new import and export functionality, there is no data placed into the data base.  It is therefore NOT backward compatible with all modules.  The DNN HTML module works, so I guess testing was done on that.  It has been said to me that other modules have been effected, but I have only proof for the one above, which has been in use for 4 or 5 years and the export code was taken from the previous version of this module, so the code in the module has been running without issue for at least 6 years or more. 
  
## Steps to reproduce
List the steps to reproduce the behavior:
1. Export website'
2. Create a new portal
3. Import exported file.

## Current result
The website is created, but no data for the modules.

## Expected result
Full website with data should be created,

## Error log
I have seen 1 error in the log, but I'm unsure if it is related to this, or the localization issue.

The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PortalLanguages_PortalLanguages".

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [] 9.2.1 ?
* [] 9.2 ?
* [] 9.1.1 ?
* [ ] 9.1 ?
* [ ] 9.0 ?

**Comment by valadas** [comment] 2019-07-29 04:48
This is probably because of the portal settings changed between Dnn versions. I don't think by design that there is any backward or forward compatibility in place for import/export between different versions, certainly not between different major releases. I am closing this issue for that reason but if I am wrong and this is in fact supposed to be supported, please link to any statement saying so or reopen.

**Closed by valadas** 2019-07-29 04:48 UTC

**Comment by leedavi** [comment] 2019-07-29 13:46
Well, I suppose rules can be in place to make this not backward compatible for major versions.  But I've never seen the issue from DNN6 to DNN7 to DNN8.

And it does go against the "We must be Backward compatible" mantra.  But I suppose the PB is also not backward compatible.

As a company we have to DNN9 now, unlike at lot of other companies, but I still have unhappy people in our team.  The devil is in the detail, but this isn't even a detail, it's broken!!! It's fine if this is suppose to be like this, but how do you expect people move to DNN9 when it doesn't export or import correctly?

I'm think I can adapt my modules, but that doesn't solve the issue for everyone else.

I'll investigate what changes I need for my modules and report it back.

(P.S. I might sound negative, I'm not, I just need to point out what I think is wrong, we don't live in a perfect world and sometimes saying that helps it get better.  I do appreciate yours and every bodies efforts for DNN.  :-) )

**Comment by mitchelsellers** [comment] 2019-07-29 17:21
Just throwing my two cents in on this one.  

Import Export, as a feature, has really only been supported within a version.  For example you can export from a 9.1.1 site and import that into a 9.1.1 site.  There hasn't been any testing, or real desire to support exporting a 9.1.1 site and restoring it to 8.0.0 or vice versa.

For those that regularly export/import sites the recommendation has been for a long time to re-create the export after an upgrade.  This is due to the plethora of changes that come with each release in Site Settings and other items.  Modules that support import/export of content should still be supported, you just need to create a proper export on the version in question.

**Comment by leedavi** [comment] 2019-07-30 02:00
Sorry, I think I went off on the backward compatibility road and I have explained wrongly.

I can export from DNN8 and import to DNN8.

I can NOT export from DNN9 and import into DNN9.

As for modules continuing to work if import and export is implemented, that is NOT true.  That is my point.  The HTML module works, but my import code that has been working since DNN6 does NOT work in DNN9.  It's working in DNN6, DNN7, DNN8.  (The export does work)

**Comment by mitchelsellers** [comment] 2019-07-30 12:24
Ah yes, there was a breaking change for this in 9. The new export process.

**Comment by sleupold** [comment] 2019-07-30 13:14
IMO there are a few caveats, IMO it should be possible to export a page or module in an old version of DNN and import on latest - in case a site upgrade is not possible and content needs to be migrated to a new DNN instance.

**Comment by sleupold** [comment] 2019-07-30 13:15
@valadas 
I suggest reopening this issue.

**Comment by mitchelsellers** [comment] 2019-07-30 13:24
@sleupold With the changes to the platform, settings, and configuration I don't know how we can move things forward without adding extensively to the technical debt we are trying to end.  Individual Module export/import seems to still work per David's commentary above

**Comment by sleupold** [comment] 2019-07-30 13:35
leedavi wrote:
> I can NOT export from DNN9 and import into DNN9.
> As for modules continuing to work if import and export is implemented, that is NOT true.

**Comment by mitchelsellers** [comment] 2019-07-30 13:41
Export/import changed in 9.x, vendors have to update modules. Just like search updated

**Comment by leedavi** [comment] 2019-07-30 15:02
Why do we need to upgrade modules?  Is the export code now doing something different in DNN9 than is was in DNN8.  Surely the bug is in DNN9, not in the modules import/export functionality, which in my case has been working since DNN6.

**Comment by mitchelsellers** [comment] 2019-07-30 15:06
Starting in 9.1.x and later the process is different and modules have to change tondo it the new way. I’ll try to dig up the documentation references

**Comment by leedavi** [comment] 2019-07-30 15:11
OK, thanks Mitch.

**Comment by mitchelsellers** [comment] 2019-07-30 15:18
I'm having troubles finding the differences, but I know that OpenContent had an issue similar: https://opencontent.readme.io/discuss/5b21426fe156cd0003c9dbc6

**Comment by leedavi** [comment] 2019-07-30 15:25
OK, thank.  I must say I never saw any documented breaking change (but I wasn't looking).  Maybe in future things that break existing modules should be more pronounced in the upgrade documents.

I understand to move forward we must snap a few links, but we should be able to find the breaking change easily,

**Comment by mitchelsellers** [comment] 2019-07-30 15:30
@leedavi Going forward yes, they will ALWAYS be better documented.  This was a transition item that occurred prior to the community assuming the leadership role.
