### ISSUE TITLE
PersonaBar / Sites Error Not work Icon button DNN 9.2.2

### ISSUE THREAD

**Issue by soheilkheiri** [dnnsoftware/Dnn.Platform#2476] opened 2018-11-13 01:10 UTC
## Description of bug
This error is in the PersonaBar / Sites.

When you click on the site configuration options and the layout option, nothing happens. However, in the console section of the browser, there is an error

## Screenshots
![capture-bug](https://user-images.githubusercontent.com/4438819/48383980-7642be00-e6fd-11e8-806f-8af305e808cd.JPG)

#### Error Details:

Uncaught Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (export-bundle.js?cdv=52:2)
    at i (export-bundle.js?cdv=52:70)
    at r (export-bundle.js?cdv=52:183)
    at o (export-bundle.js?cdv=52:37)
    at o (export-bundle.js?cdv=52:37)
    at i (export-bundle.js?cdv=52:37)
    at Object.instantiateChildren (export-bundle.js?cdv=52:183)
    at h._reconcilerInstantiateChildren (export-bundle.js?cdv=52:184)
    at h.mountChildren (export-bundle.js?cdv=52:184)
    at h._createInitialChildren (export-bundle.js?cdv=52:183)

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment] 2019-07-28 06:09
This UI has slightly changed and I was not able to reproduce the settings icon example on 9.4.0 RC, closing this issue, if it still happens on current releases, please open a new issue.

**Closed by valadas** 2019-07-28 06:09 UTC
