### ISSUE TITLE
AdvancedUrlRewriter multi language problem

### ISSUE THREAD

**Issue by evanes68** [dnnsoftware/Dnn.Platform#2315] opened 2018-09-14 06:52 UTC
We have a 9.2.0 DNN install with multiple portals. We have two languages active besides en-us. The issue we had was that when we clicked on a page with name Contact in GB English we would see a Contact page with the content in the Dutch language.
 
It seems one of our programmers setup a new portal in DNN 9.2.0 which led to a default setup using the advanced urlrewriter, see default web.config entry:
 
    <friendlyUrl defaultProvider="DNNFriendlyUrl">
      <providers>
        <clear/>
        <add name="DNNFriendlyUrl" type="DotNetNuke.Services.Url.FriendlyUrl.DNNFriendlyUrlProvider, DotNetNuke.HttpModules" includePageName="true" regexMatch="[^a-zA-Z0-9 _-]" urlFormat="advanced"/>
      </providers>
    </friendlyUrl>
 
 
We also found using a sql profiler that the following query is sent to sql server when using the AdvancedUrlRewriter:
 
`exec sp_executesql N';Exec dbo.GetTabPaths @0, @1',N'@0 nvarchar(4000),@1 nvarchar(4000)',@0=NULL,@1=N''`
 
The trouble with this query is that it returns all tabpaths of all portals but with only the following fields: TabId, PortalId, TabPath. In DNN using c# code the correct tabid is then selected.
When you have Multilanguage enabled it is possible to have two pages in different languages with the same name and tabpath. What would happen is that the first tabid with a certain tabpath and portalid is returned, which in our case happened to be the wrong tabid because the value of culturecode was dismissed.
 
I think you need to expand the gettabpaths to always return the culturecode and you use this when selecting a tabid.
 
When we revert back to the trusty urlFormat=”humanfriendly”  all works well, and we see two queries sent to the database:
 
`exec sp_executesql N';Exec dbo.GetTabPaths @0, @1',N'@0 int,@1 nvarchar(4000)',@0=5,@1=N'en-GB'`
`exec sp_executesql N';Exec dbo.GetTabPaths @0, @1',N'@0 nvarchar(4000),@1 nvarchar(4000)',@0=NULL,@1=N''`
 
the first being the important one where only tabpaths are returned for a certain portalid culturecode combination!

The second query is also performance trouble because it return the whole table. We have DNN setups where this can be over 500000 records... It should be removed all together.

**Comment by sleupold** [comment] 2018-10-07 10:08
please make sure, that you have a primary portal alias for each site.
Besides, tabpath should be different in two languages, unless you are using a neutral page.

It looks like advanced URL rewriter is missing some details here, which needs to be investigated:
- exten getTabPaths to return culture code as well 
- make sure, culture specific rows are returned first
- check advancedURLrewriter biest to handle culture tabpaths properly

**Comment by sleupold** [comment] 2018-10-18 14:02
@evanes68 
So you are using same tabpath, but with different portal aliases per language, right?

**Comment by evanes68** [comment] 2018-10-18 14:07
Sebastián,

Sometimes the alias is different. But I have portal instances with multi language enabled with a single alias. And then identical tab paths with different localised content should also work.

With kind regards.

Evert

Verstuurd vanaf mijn iPhone

**Comment by jsbsantos** [comment] 2019-06-18 17:43
Hello.

Any news on this problem? I'm facing the same kind of issue.

**Comment by valadas** [comment] 2019-07-28 00:55
In the spirit of triaging the issues, this one is not actionable since it does not have a very specific set of steps to reproduce. It looks like the current behaviour requires either a different alias or tabpath for each version of a page for each language which appears to make sense to me. I would suggest either moving this discussion into the forums at https://dnncommunity.org/forums or creating a new issue with very specific setup instructions from a clean dnn install up to the state required to reproduce the issue.

**Closed by valadas** 2019-07-28 00:55 UTC

**Comment by evanes68** [comment] 2019-07-28 04:11
Daniel,

It is not logical to add an alias at page level and it is not logical to expect tabpath to be unique across languages.

There is a very big bug in the advancedurlrewriter. Closing this issue does not solve it.

Please reopen and assign to someone knowledgeable in the multi language area.

With kind regards,

Evert

Verstuurd vanaf mijn iPhone

**Comment by valadas** [comment] 2019-07-28 04:53
@evanes68 I am just trying to clean up issues so they are all actionable and have a milestone assigned, this is in hope of speeding up their resolution. Me and @sleupold have a lot of experience with localization. I have not been able to reproduce this issue on current releases and that is why I closed it. If you can provide very specific setup instructions from a clean install of a current version up to the point of seing the issue happen, this will make the new issue something actionable and will help for someone to pick it up and work on it.

We do not assign issues to anyone, community members pick up issues and work on them and the easier it is to make the problem happen, the most chances you have someone like me picks it up and is able to investigate and provide a pull request to fix it.
