### ISSUE TITLE
Inline editor not working when composite files enabled

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#5092] opened 2022-04-20 15:53 UTC
## Description of bug
I have a fresh install for Dnn 9.10.2, created a skin and added some content.

After enable composite, minify, etc, inline editor for html stopped work.

I dont have any js error or message in console, simply inline editor for html stopped work.

I have checked settings for inline code and is enabled for all site.

This is happening with default skin from DNN too.

## Steps to reproduce
1.- Install Dnn 9.3.2
2.- Enable files composite and add a version.
3.- Enable page edition and inline editor don´t show.

## Current behavior
The inline editor is not showed, so is not posible to edit inline.

## Expected behavior
Icons for inline editor should be showed when over on html module.

## Affected version
-->
* [X] 09.10.02 release candidate

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by cklenk** [comment] 2022-05-02 19:46
Sounds like a duplicate of https://github.com/dnnsoftware/Dnn.Platform/issues/3999

**Comment by valadas** [comment] 2022-05-02 23:25
Yep, closing in favor of existing #3999

**Closed by valadas** 2022-05-02 23:25 UTC
Labels: Status: New
