### ISSUE TITLE
DNN930RC: Admin Log shows blank page

### ISSUE THREAD

**Issue by gcdigital** [dnnsoftware/Dnn.Platform#2549] opened 2019-01-22 01:25 UTC
## Description of bug
Admin Log shows blank page

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install DNN 930 RC with "Blank Template" (not too sure if it affects the result)
2. After installation, click on 'Manage' and Select 'Admin Log' from Persona Bar
3. Admin Log page refreshes layout quickly and shows blank

## Current result
Admin Log page refreshes layout quickly and shows blank

## Expected result
Admin Log page shows what it looks and the log list on the page

## Affected version

* [x] 9.3.0
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

I don't think it's a browser issue although I have tested it on the following browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment] 2019-01-22 01:30
Duplicate of https://github.com/dnnsoftware/Dnn.AdminExperience/issues/329 this was fixed by https://github.com/dnnsoftware/Dnn.React.Common/pull/203 it should be fine on the nightly build and RC1 should be out shortly.

**Closed** 2019-01-22 09:21 UTC
