### ISSUE TITLE
Remove DNN Corp Default Copyright

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#3715] opened 2020-04-30 11:36 UTC
## Description of bug
On a new install of DNN, the Copyright that is configured is DNN Corp.

## Steps to reproduce

1. Create a new blank DNN site

2. Notice the DNN Corp copyright in the footer of the default skin

## Expected behavior

I think the community copyright should be used here.

## Screenshots

![image](https://user-images.githubusercontent.com/39993943/80705830-8b600800-8abd-11ea-9a4f-b45adc0e33ce.png)

## Affected version
* [x ]  9.6.0

Noticed on 9.6 but I assume this is in all of the versions.

**Comment by sleupold** [comment] 2020-04-30 11:56
this need to be fixed in the website template

**Comment by david-poindexter** [comment] 2020-05-06 12:55
I’ll try to take a crack at this one.

**Comment by thabaum** [comment] 2020-05-17 16:29
I believe the issue is in the script that loads the seed data... I was going to work on that a while back.  I think this is the next "cleanup" area.

**Comment by thabaum** [comment] 2020-05-17 16:32
Reason I did not move forward on fixing this was knowing the desired end result.   I think it should be "generic" as can be for all seed data.

**Comment by thabaum** [comment] 2020-05-17 19:04
![image](https://user-images.githubusercontent.com/13577556/82157316-9644c780-9835-11ea-86d6-03c502f304ca.png)

You can see this shows in the theme, the theme is in good shape it is the seed data.   @sleupold you probably the best to know how to dig this up or @valadas and @mitchelsellers would you know off hand which file loads the seed data.

What I recall is a sql script that is part of the upgrade process and during one of the upgrades it fixes an issue and adds DNN Corp into the DB.

**Comment by thabaum** [comment] 2020-05-17 19:14
\DNN Platform\Website\Install\DotNetNuke.install.config.resources

This is part of the initial installation... however one version I recall changes the host title

Maybe in this file this can get set or is set, but then gets changed?

Host Settings > Host Title is the field in the database it is connected to.

I think the UI is missing the ability to utilize and edit this for skins?!

**Comment by thabaum** [comment] 2020-05-17 20:01
Found the file

https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Website/Portals/_default/subhost.aspx

Line 792

**Comment by david-poindexter** [comment] 2020-05-17 20:04
@thabaum Fyi...I already have a PR being prepped for this issue.  Notice I assigned the issue to a little over a week ago.  ;-)

**Comment by thabaum** [comment] 2020-05-17 20:05
ok cool I also found it here.  Can we work with Host Title?  so a another issue I take it needs created... which I will do when I fix it I suppose :)

https://github.com/dnnsoftware/Dnn.Platform/blob/62e0c62531e64a21e9296a5845f7bd94c5082739/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Licensing/App_LocalResources/Licensing.resx#L237

**Comment by thabaum** [comment] 2020-05-17 20:13
https://github.com/dnnsoftware/Dnn.Platform/blob/62e0c62531e64a21e9296a5845f7bd94c5082739/DNN%20Platform/Tests/DotNetNuke.Tests.Web/Api/JwtAuthMessageHandlerTests.cs#L158

https://github.com/dnnsoftware/Dnn.Platform/blob/62e0c62531e64a21e9296a5845f7bd94c5082739/DNN%20Platform/Tests/DotNetNuke.Tests.Web/Api/StandardTabAndModuleInfoProviderTests.cs#L99

https://github.com/dnnsoftware/Dnn.Platform/blob/62e0c62531e64a21e9296a5845f7bd94c5082739/DNN%20Platform/Library/Application/Application.cs#L39

These are some more places that could get changed along with the one above possibly along with the database entry.

Should I make another issue?  I put them here so you can do what you will with those places or leave them I am not worried about it.

**Comment by thabaum** [comment] 2020-05-17 20:14
> 
> 
> @thabaum Fyi...I already have a PR being prepped for this issue. Notice I assigned the issue to a little over a week ago. ;-)

Thank you!

**Closed** 2020-06-08 13:48 UTC
Labels: Area: Platform > Website, Effort: Medium, Priority: Low, Status: Development, Type: Enhancement
