### ISSUE TITLE
Copy Existing Module Function Doen't Work DNN 9.1 or 9.20

### ISSUE THREAD

**Issue by rbeghin** [dnnsoftware/Dnn.Platform#2180] opened 2018-07-23 20:59 UTC
## Description 
As site Administrator: Cannot copy an existing module using built in function.
## Steps to reproduce
Using Copy Existing Module icon: When you attempt to do so the floating "add" icon does not appear. Clicking the "plus sign +" does not appear to do anything. Page refresh does not help. However, if you logon to the same page as SuperUser, it appears that the module is waiting and the floating "add module is there". Upon adding, other users cannot view or edit the module. It appears that the permissions are not copied over correctly. This has been test against different modules with the same problem. Problem was apparent in 9.1 but upgrading to 9.20 did not resolve the issue.
## Current result
Cannot copy any existing modules so that module is visible per page permissions.
## Expected result
Should be able to click Copy Existing Module and select existing module from another page and then drop into place on current page.
## Affected version
9.2.0.366-777

* [x] 9.2
* [ ] 9.1.1
* [x ] 9.1
* [] 9.0

## Affected browser
Problem appears in IE 11 and Firefox. Did not check other browsers.

* [ ] Chrome
* [x] Firefox
* [ ] Safari
* [x] Internet Explorer
* [ ] Edge

**Comment by rbeghin** [comment] 2018-07-23 22:10
Additional info: it appears that this problem has been around for quite awhile. Found another GitHub post for the Blog module. That issue appears to be unresolved since 2017 Copy Module doesn't work on DNN9 #121 https://github.com/DNNCommunity/DNN.Blog/issues/121

**Comment by valadas** [comment] 2018-10-28 07:35
I cannot reproduce this behaviour using Dnn 9.3.0 alpha build 33 using the Dnn controls. The Blog module issue is still present thought, but unrelated to this repository.

**Comment by Tychodewaard** [comment] 2019-02-25 10:43
I can not reproduce either in 9.2.2. Adding an existing module as host does what is expected and so is another user that has been granted admin permissions.

**Comment by mikesmeltzer** [comment] 2019-05-28 13:36
I recommend that we close this issue as it appears to not be a DNN Platform issue (as stated above) but an issue with the Blog module.  

The issue with the module is being tracked in the Blog module repository at:

https://github.com/DNNCommunity/DNN.Blog/issues/98

**Comment by valadas** [comment] 2019-07-27 07:40
Closing this one as per previous comment

**Closed by valadas** 2019-07-27 07:40 UTC
