### ISSUE TITLE
Site Export Gets Stuck on "In Progress"

### ISSUE THREAD

**Issue by JTMaher2** [dnnsoftware/Dnn.Platform#2174] opened 2018-07-19 16:43 UTC
## Description 
The export wizard gets stuck on the "In Progress" state. I inspected the source code for DotNetNuke.SiteExportImport.dll, and found that the "ExportModulePackage(ExportModule exportModule)" function in "PagesExportService.cs" was passing a null desktop module to "PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.PackageID == desktopModule.PackageID)." This was causing an "Object reference not set to an instance of an object exception" to be generated, and no further progress to be made.

For some reason, the "ExportModulePackage(ExportModule exportModule)" is being called for a module that is not present in the "dbo.DesktopModules" table. Therefore, when "DesktopModuleController.GetDesktopModule(desktopModuleId, Null.NullInteger)" is called with this ID, it returns null. Subsequently, the call to "PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.PackageID == desktopModule.PackageID)" generates an exception due to a property being accessed on a null object.

I worked around this issue by building a custom "DotNetNuke.SiteExportImport.dll" with the following code for "ExportModulePackage(ExportModule exportModule)":

    private int ExportModulePackage(ExportModule exportModule)
        {
            if (!_exportedModuleDefinitions.Contains(exportModule.ModuleDefID))
            {
                var packageZipFile = $"{Globals.ApplicationMapPath}{Constants.ExportFolder}{_exportImportJob.Directory.TrimEnd('\\', '/')}\\{Constants.ExportZipPackages}";
                var moduleDefinition = ModuleDefinitionController.GetModuleDefinitionByID(exportModule.ModuleDefID);
                var desktopModuleId = moduleDefinition.DesktopModuleID; // this ID that is not present in dbo.DesktopModules
                var desktopModule = DesktopModuleController.GetDesktopModule(desktopModuleId, Null.NullInteger); // Because the ID is not present in dbo.DesktopModules, this returns null

                // I added this if statement to prevent GetExtensionPackage from throwing an exception
                if (desktopModule != null)
                {
                    var package = PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.PackageID == desktopModule.PackageID);
                    var filePath = InstallerUtil.GetPackageBackupPath(package);

                    if (File.Exists(filePath))
                    {
                        var offset = Path.GetDirectoryName(filePath)?.Length + 1;
                        CompressionUtil.AddFileToArchive(filePath, packageZipFile, offset.GetValueOrDefault(0));

                        Repository.CreateItem(new ExportPackage
                        {
                            PackageName = package.Name,
                            Version = package.Version,
                            PackageType = package.PackageType,
                            PackageFileName = InstallerUtil.GetPackageBackupName(package)
                        }, null);

                        _exportedModuleDefinitions.Add(exportModule.ModuleDefID);
                        return 1;
                    }
                }
            }
            return 0;
        }
## Steps to reproduce
1) Queue a new export for any page on the site.
2) Observe that the export routine never completes.
## Current result
The export wizard gets stuck, and an incomplete set of files get generated in the "App_Data/ExportImport/<DATE_AND_TIME>" folder. The only files that are present are "export.dnndb" and "export_files.zip".
## Expected result
The export wizard should complete the export process. A full set of files should be generated in the "App_Data/ExportImport/<DATE_AND_TIME>" folder. These should include "export.json," "export_db.zip," "export_files.zip," "export_packages.zip," "export_templates.zip," and "export_themes.zip."
## Affected version

* [ ] 9.2 
* [x] 9.1.1 <-- This is the version that my site is running, so I don't know if other version are affected.
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome <-- I only tested this in Chrome, but I would assume that all other browsers are affected.
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by 1silvertiger** [comment] 2019-04-10 16:06
I am having this same issue on 9.2. The files generated are:
- export.dnndb
- export_files.zip
- export_packages.zip
- export_templates.zip
- export_themes.zip
which it generates within a few minutes, then hangs on "In Progress" indefinitely. I haven't inspected it yet.

**Comment by valadas** [comment] 2019-07-27 07:38
I am closing this issue assuming this is with a specific module since I was not able to reproduce on the latest version @JTMaher2 if that only happens on the latest version with some specific setup please include detailed steps to reproduce the issue.

**Closed by valadas** 2019-07-27 07:38 UTC

**Comment by krisgourd** [comment] 2019-09-13 22:05
@valadas This is still an issue in Evoq Basic 9.3.0 Enterprise Edition: Core-based Licensing (64-bit)

Went through the steps in https://dnnsupport.dnnsoftware.com/hc/en-us/articles/360009692674-Importing-or-Exporting-hangs-at-Submitted-Status with no success. 

- The only file generated is the export.dnndb 

- Nothing populates in Export Summary.

Let me know if you need more information.

**Comment by benswindle** [comment] 2021-12-01 18:51
I'm experiencing this issue as well, and I'm on Evoq 9.6.2. When is DNN planning on fixing this issue?

**Comment by bdukes** [comment] 2021-12-01 18:53
DNN Platform is currently on version 9.10.2. You may want to open a support ticket with Evoq to see if they have plans to investigate if this bug will continue to affect Evoq customers if they move to the latest version of DNN Platform (and when you can expect an updated version).

**Comment by benswindle** [comment] 2021-12-01 18:54
Thanks bdukes! I'm in progress of reaching out now.

**Comment by benswindle** [comment] 2021-12-01 20:53
The solution for me was to add the hostname to the server field in the import-export service. See article for details:

https://dnnsupport.dnnsoftware.com/hc/en-us/articles/360014800899-DNN-Import-Export-stuck-In-Progress-or-fails-with-exception-
