### ISSUE TITLE
Default site settings from the 'Languages' tab

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2859] opened 2019-06-21 08:01 UTC
## Description of problem
Some settings are on by default, so, perhaps this is not really necesarry....

## Description of solution
On a clean DNN Install, I can see the:
- Enable language parameters in URLs is set to 'ON'
- Enable browser Language Detection is set to 'ON'

Perhaps this is not necesary by default....
When you only have one language, then why would I allow language parameters in the url?

## Screenshots
![Naamloos3](https://user-images.githubusercontent.com/1827559/59908599-11c3ac00-940e-11e9-9476-c9b76396bc22.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment] 2019-06-21 10:58
turning both options on are still best practice for initial setup, though the first might be superseded by portal aliases.

**Comment by valadas** [comment] 2019-07-29 21:59
Closing this as it is by design and does nothing until you actually add another language.

**Closed by valadas** 2019-07-29 21:59 UTC
