### ISSUE TITLE
Profile edit: "Display name already exists" error if Require Unique Display Name is checked

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#2875] opened 2019-07-01 20:30 UTC
## Description of bug
If you have "Require Unique Display Name" switched on then it gets difficult if not impossible to edit user profiles in some circumstances.
There is something on dnncommunity.org to cause this issue, but I can't reproduce it locally.
Will rty to find out what the circumstances are and report back here.

## Steps to reproduce
List the steps to reproduce the behavior:
1. On a site with multiple users
2. Security > Member accounts > registration settings > [x] Require Unique Display Name
3. .. probably something else (?) ...
3. Now try to edit a user profile
4. You get a "The display name you have entered is already in use, please choose a different one." error

## Additional context
To me this line looks suspicious: https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/Website/DesktopModules/Admin/Security/EditUser.ascx.cs#L472
Why would you pass an index of 2?

## Affected version

* [x] 9.3.2

**Comment by david-poindexter** [comment] 2019-07-01 20:36
@Timo-Breumelhof that is not an index of 2, it represents pageSize.  See https://github.com/dnnsoftware/Dnn.Platform/blob/dca2a33e16dd365395569b9f4e6151a14b1806a5/DNN%20Platform/Library/Security/Membership/MembershipProvider.cs#L182-L186

**Comment by Timo-Breumelhof** [comment] 2019-07-01 20:38
@david ok, right  I mixed them up... thanks

**Comment by hismightiness** [comment] 2019-07-01 22:03
For additional historical context and background only.  

https://dnntracker.atlassian.net/browse/DNN-5874

https://dnntracker.atlassian.net/browse/DNN-4781

A contributing configuration factor may be making the first and last name required.

**Comment by Timo-Breumelhof** [comment] 2019-07-02 07:40
@david-poindexter I now see I looked at the sql, not the code. There the two are in reverse order I think. (If this is the last change):
https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/Website/Providers/DataProviders/SqlDataProvider/07.04.01.SqlDataProvider#L15

**Comment by Timo-Breumelhof** [comment] 2019-07-02 08:18
Hmm, I now see that sometimes it shows you the error but it does save the data.. (on dnncommunity)

**Comment by Timo-Breumelhof** [comment] 2019-07-02 12:54
Ok, Peter just looked at this and found another one

**Comment by donker** [comment] 2019-07-02 16:59
My gut feeling is that there is a caching issue. When you've edited your display name to something that exists then you get an error. So far so good. But that display name is changed in cache and persists so every time you go to edit you get an error.

**Comment by valadas** [comment] 2019-07-29 22:51
I am closing this one in favor of #2878 which more accurately describes the bug and how it will need to be solved, If I am wrong in closing this, feel free to comment or reopen, just trying to avoid duplications. :)

**Closed by valadas** 2019-07-29 22:51 UTC
Labels: bug

**Comment by Timo-Breumelhof** [comment] 2019-07-30 10:58
@valadas Peter is convinced it's the same issue, but I'm not as we did clear the cache a lot. Both me, @david-poindexter and @hismightiness

**Comment by valadas** [comment] 2019-07-31 01:49
@Timo-Breumelhof so do you have any steps to reproduce that would be different than in #2878 or should we reopen this one because it is different and we have a way to make it happen ? I am just trying to avoid duplicates and issues that are intermittent and we cannot troubleshoot accurately.

**Comment by Timo-Breumelhof** [comment] 2019-08-01 08:16
@valadas actually no, I only see it on the dnncommunity website. I did not manage to reproduce it locally. Let's wait if it's fixed there when it's upgraded to 9.4?
