### ISSUE TITLE
Editing Regex Expressions for Url Management Being Saved

### ISSUE THREAD

**Issue by joshgk00** [dnnsoftware/Dnn.Platform#2220] opened 2018-08-10 00:22 UTC
## Description 
When trying to update the Regex expressions in the Persona Bar the changes aren't being saved to the appropriate HostSettings. 
## Steps to reproduce
1. In the Persona bar go to Settings > SEO > Url Management > Expressions
2. In the first field Ignore URL Regular Expression add the following to the end of the string **|\.well-known**
3. Scroll down and click **Save**
4. Refresh the page and when the page reloads, the changes are not visible
5. In the Persona Bar go to Settings > Servers > **Click Clear Cache** button
6. In the Persona bar go to Settings > SEO > Url Management > Expressions
## Current result
The changes are not displayed in the textbox. When running the following SQL query the results do not show the changes

`select * from hostsettings
where SettingName = 'AUM_IgnoreUrlRegex'`

## Expected result
The Ignore URL Regular Expression textbox should have the following value:
**(?<!linkclick\.aspx.+)(?:(?<!\?.+)(\.pdf$|\.gif$|\.png($|\?)|\.css($|\?)|\.js($|\?)|\.jpg$|\.axd($|\?)|\.swf$|\.flv$|\.ico$|\.xml($|\?)|\.txt$))|\.well-known**
## Affected version

* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [ ] 9.0

## Affected browser
All Browsers

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment] 2019-07-27 09:06
I am not able to reproduce in 9.4.0 RC, also, 2 notes:

1. for the regex string you need a \ before the . to escaped the dot or it means any character and not a dot.
2. this is not saved in HostSettings but in PortalSettings

I am closing this issue, if you still have problems with this using the latest release, please open a new issue.

**Closed by valadas** 2019-07-27 09:06 UTC
