### ISSUE TITLE
Unable to change US language for "Register" in dnn:user control

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3200] opened 2019-10-24 22:00 UTC
## Description of bug
I have been trying for months to see where to change "Register" other than in an ascx file which still barely does it for all portals of a DNN Instance...

Challenge of the day is to change the word "Register" 
![image](https://user-images.githubusercontent.com/13577556/67528320-07d8e080-f66e-11e9-8c91-1679d9babab1.png)

and let me know how you did it so every portal you run on a DNN CE instance says "Create Account" instead.  I have been told all these work arounds and it is very time consuming for a single word.

I am convinced this is a bug however I could be wrong but every other word I can change...  

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install DNN and create 3 portals
2. Change Global language pack Register.Text to "Create Account" in all the different places it is located...  Change Login to Sign in as well you can see that will change.  Hard to locate them as they seem to be scattered all over the place trying to edit one section of the website register and login text. 
3. Refresh the page a couple thousand times trying
4. See Register still exists somewhere somehow as the Register.Text although you cannot find it anywhere.

## Current result
![image](https://user-images.githubusercontent.com/13577556/67528548-96e5f880-f66e-11e9-9bc1-d697a3feaca8.png)

## Expected result
Create Account next to Sign In

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13577556/67528571-a1a08d80-f66e-11e9-9a8c-a04fa7865855.png)

## Additional context
When you change the register.text language it should be sent to all modules such as authentication providers to replace even text that says "Register with Facebook" should just change to "Create Account with Facebook".

Otherwise each time you save the resource file it is taking the site down until it reloads... it would be nice to be able to edit multiple files then save them all at once.   And search all the files for any available langauge settings that can be set that contain a certain word as an enhancement.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by sleupold** [comment] 2019-10-25 11:09
The register and login skin objects properly use DNN static localization from resx files, I am using latest version for my German site and it properly displays German words.
Please make sure you are modifying proper resource file, preferable using DnN built in language editor (site setting > languages, last icon in the language list and make sure, you are in Host mode on the top right corner (to prevent your changes being overwritten on upgrades). Get the proper resource file from the dropdown list, he texts you are looking for should be located in Local Resources > Admin > Skins > AppLocalResources > Login.ascx and Register.ascx

**Comment by thabaum** [comment] 2019-10-26 18:17
I have been using it and edited all of them but it maybe possibly something with the skin I am using.  However I removed and set Title="Create Account" and it seems like the primary host portal it worked ok but the other portals all defaulted to REGISTER and LOGIN although even in my portal ascx file it says Title="Create Account" and Title="Sign in"

I will keep troubleshooting as it maybe just my environment but it has been bugging me as I have changed them repeatedly.

It also feels like after I change them, then do an upgrade to a new version of DNN all my language changes go back to defaults.  But I will test that out next release before I report that as a bug.

**Comment by valadas** [comment] 2019-11-18 04:02
> (why have two places to edit the same thing Login/Logout?)

Yeah, there are a couple of duplications in the resource files and well, removing those that live in a specific module control is kind of doable but the global ones are kind of hard to remove because who know what uses them. Starting today, only very generic stuff would go into common resource files, but where we are now, it is hard to remove some of those duplicate keys...

That being said, I could also not reproduce and have multiple localized sites working fine, I am assuming this must be hardcode in the theme or that theme is using the wrong key or some such. Maybe the theme has it's own localization files, or was not built to be localizable, etc. I am closing this issue since we cannot reproduce using the Dnn provided theme.

**Closed by valadas** 2019-11-18 04:02 UTC
