### ISSUE TITLE
Can not move page from under parent page when selecting < None Specified >. DNN 9.2.2

### ISSUE THREAD

**Issue by abukres** [dnnsoftware/Dnn.Platform#2477] opened 2018-11-15 04:17 UTC
Steps to replicate:
1- Add a page or more under Home page
2- Select one of the new pages and select < None Specified > as the parent and save

Expected Result: 
New page is at the same level as the Home page

Current Result:
New page is still under the Home page  

Note: Dragging the page in the treeview does work

**Comment by sleupold** [comment] 2018-11-15 09:09
If I remember correctly, home page was always used as root with top level menu items displayed just beneath, though they are displayed in menu all in a row.

**Comment by Tychodewaard** [comment] 2019-07-17 14:05
@abukres I just tried to replicate the issue on 9.3.2 and it works as expected.
Can you confirm this?

**Comment by valadas** [comment] 2019-07-17 17:46
In order to cleanup issues and because there was changes to the pages module and we cannot reproduce on 9.3.2, I am assuming this is now fixed and I am closing the issue for now. @abukres if you can still reproduce this on 9.3.2 or later, please open a new issue. Thanks.

**Closed by valadas** 2019-07-17 17:46 UTC
