### ISSUE TITLE
Icon for page in menu broken

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#3621] opened 2020-03-10 13:01 UTC
This is a continuation of this issue as the problem remains:

https://github.com/dnnsoftware/Dnn.Platform/issues/3164

For some reason, it seems like icons for pages are not correctly displayed in the menu, instead they show up with broken image icons. It seems like DNN is trying to load the icon with the wrong URL, notice the double part here:

https://upgrade.mysite.com/**Portals/0//Portals/0**/bankid_icon.png?ver=2017-06-21-121921-430

If you modify the value fin Tabs i Database to something like:

~/Icons/bankid_icon.png

It will work so its probably not related to the skin or something like that but that the URL to the image gets corrupted somehow in the code. If you just upload the icon via page settings, only the filename itself is stored in the database so I guess the URL is picked form somewhere else and gets corrupted. This does not happen when you have a full path in TabSettings IconFile column, so workaround seem to be to do just that and the icon will be displayed as it should.

**Comment by valadas** [comment] 2020-03-10 13:49
Like for #3164 I cannot reproduce this issue with a standard setup. Can you add some steps to reproduce this issue from a clean state.

**Comment by improwise** [comment] 2020-03-10 14:29
What we did was just to selecte a page and access page settings for it, then select an image as icon, upon which the filename (only) is saved in the DB but when the image is about to be displayed, it tries to find the image in the wrong location (wrong URL) for some unknown reason. As only the filename is stored in DB; I guess that the URL is somehow generated in code and thats where it goes wrong.

**Comment by bdukes** [comment] 2020-03-10 14:34
What theme are you using?  Do you have access to review the code that the theme is using to create the image URL?

**Comment by improwise** [comment] 2020-03-11 10:59
It's happening on several sites, using either POLO och DNNGO skins (available in DNN Store), not access to the source code unfortunately. But is it the theme that actually generates the URL to the images and not DNN?

**Comment by valadas** [comment] 2020-03-11 17:43
Yes, the theme does have to inject it properly. I will close this issues as we cannot reproduce on platform, but you can keep commenting here if you need help. Just closing since so far it looks like this is not something that needs a fix in this source code.

**Closed by valadas** 2020-03-11 17:43 UTC
Labels: Status: New
