### ISSUE TITLE
Edit Content doesn't load content or allow edits

### ISSUE THREAD

**Issue by brentil** [dnnsoftware/Dnn.Platform#4037] opened 2020-09-02 18:03 UTC
## Description of bug
DNN recently upgraded from 9.1.1 -> 9.3.2 -> 9.4.4 [EDIT and now 9.7.0] (started life in 2013 as a 7.0.2 installation and has been upgraded over the years) and using the built in DNNConnect.CKE 1.0.7 with no other providers installed.  When going to a page and clicking Edit Content the window that comes up shows a blank Edit Content instead of the text you expect to see.  You can't click into the text area to do anything either.  If you click the Source button in the top left you can see all the source for what should be there but once you go back to normal view mode it's still blank.  On a test copy of the website I installed the latest DNNConnect.CKE 1.1.0 but that didn't resolve the issue either.  We've tried a variety of browsers on different machines and also made sure to clear the cache on them and had the same result.  This install has 7 portals in it made over the years since 2013 and it seems the oldest ones have the issue but newer ones made later on do not.

I also found an odd workaround in that if you grab the window expansion in the far bottom right (popup window the items are in and not the edit box) and drag the size to be about an inch larger the content appears and you can start editing it.  

I've requested hours to upgrade to 9.6.2 but have not been approved to do so yet.

## Steps to reproduce
1. Install DNN 7.0.2 and make a portal in it
2. Spend 7 years upgrading to newer versions of DNN ending so far in 9.4.4
3. Click edit button in the bottom left
4. Click the Edit Content on an area with content in it
5. Edit Content comes up with a blank text area and you can't click in it

## Current behavior
Edit Content doesn't have previous content in it and I cannot add new content

## Expected behavior
Edit Content has previous content in it and I can add new content

## Screenshots
![CKE_Empty](https://user-images.githubusercontent.com/309174/92019689-057ef280-ed25-11ea-8fe2-9cfb519109d3.png)

![CKE_Drag](https://user-images.githubusercontent.com/309174/92019704-0b74d380-ed25-11ea-9c27-4e0ba24eaf61.png)

![CKE_Full](https://user-images.githubusercontent.com/309174/92019718-10398780-ed25-11ea-9fcb-d1eeb4546005.png)

## Error information
There are no errors in the logs, admin logs, and the dev tools console shows no errors

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version
* [X] 09.07.00
* [X] 09.04.04

## Affected browser
* [X] Chrome
* [X] Firefox
* [ ] Safari
* [X] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment] 2020-09-02 19:40
Can you upgrade to the latest version and check if you can still reproduce the issue ?

9.4.4 is now very old and the html editor is also kinda made or tested with specific Dnn versions in mind. I would start by upgrading to the current release https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.7.0 and troubleshoot from there. 

If not possible then this issue is probably more of a help request than an actionable issue for development and belongs either in discussions https://github.com/dnnsoftware/Dnn.Platform/discussions or forums https://dnncommunity.org/forums. Issues here should be actionable items for current development on the latest supported release as explained in the issue template:

```
Please add X in at least one of the boxes as appropriate. In order for an issue to be accepted, a developer needs to be able to reproduce the issue on a currently supported version. If you are looking for a workaround for an issue with an older version, please visit the forums at https://dnncommunity.org/forums
```

**Comment by brentil** [comment] 2020-09-03 00:08
I got permission this afternoon to upgrade to 9.6.2 which I will be doing either tomorrow or Friday and will report back if the issue continues.

**Comment by brentil** [comment] 2020-09-03 14:37
Upgraded to 9.7.0 and the issue still exists.  Cleared browser cache and tried several different browsers.

**Comment by valadas** [comment] 2020-09-04 23:30
Do you have any errors either in the broswer console (F12 in chrome) or in the admin log or in the Portals/_default/logs folder ?

Also, does it happen if you create a new test page and only use the default theme on it ?

**Comment by brentil** [comment] 2020-09-05 13:08
There are no errors in the F12 dev tools or the admin logs.

Someone on the forum suggested it might be the skin the portals are on as well.  I asked the developers and they said the forums having issues all use skins based off Xcillion but that might have been an old Xcillion.  They're working on comparing the skin to the newest copy of Xcillion to see if that resolves it.

**Comment by valadas** [comment] 2020-09-05 19:59
Ok, since this is not something we can currently reproduce, I am going to close this issue, if you do find something reproducible on a standard install, please comment again and I will be happy to reopen the issue. Also you can keep on commenting and followers will still get notified.

**Closed by valadas** 2020-09-05 19:59 UTC
Labels: Status: New

**Comment by brentil** [comment] 2020-09-10 20:53
We tested the portals having issues by swapping them to use the latest Xcillion skin inside of DNN and found the issue still continues on those portals that were previously having issues.
