### ISSUE TITLE
Bug in Personabar Search Users in 9.2.2

### ISSUE THREAD

**Issue by sbourgeo** [dnnsoftware/Dnn.Platform#2520] opened 2018-12-27 16:09 UTC
## Description of bug
The problem is in the following DLL Dnn.PersonaBar.Users.dll V1.6.1.0

When typing characters in the SearchTerm field, The wildcard % character is not added at the end of the string sent to the Store Procedure Personabar_GetUsersBySearchTerm.

I was able to reproduce the problem on a fresh install.

Replacing the DLL with version 1.5.0.0 fixed the issue.

## Steps to reproduce
List the steps to reproduce the behavior:
When clicking Users in Personabar, it returns all the users ordered by Joined date descending. As soon you type a character, the list become empty. Typing the % character at the end will list the names that begin with the typed characters.

Tracing with SQL profiler, I noticed that the wildcard character is sent automaticaly on DNN 9.2.0, but not sent in DNN 9.2.2
## Affected version

* [x] 9.2.2

**Comment by valadas** [comment] 2018-12-29 05:37
I just tested on the 9.3.0.130 alpha and could not reproduce, I see the % at the end of the name in SQL Profiler, so I think somehow this got fixed with something else.

**Comment by chadwixk** [comment] 2019-03-07 22:15
A temp fix for those not ready to upgrade.

Change the stored procedure (`[Personabar_GetUsersBySearchTerm]`)
**From this:**
`IF @SearchTerm = N'' SET @SearchTerm = Null; -- Normalize parameter`

**To This:**
`IF @SearchTerm = N''SET @SearchTerm = Null; -- Normalize parameterELSESET @SearchTerm = @SearchTerm + '%'`
--

**Comment by Tychodewaard** [comment] 2019-07-17 13:40
@valadas does this mean this issue can be closed?

**Comment by valadas** [comment] 2019-07-17 16:52
Yes, closing this since we cannot reproduce in current version and there is also a workaround for older ones.

**Closed by valadas** 2019-07-17 16:52 UTC
