### ISSUE TITLE
dnn.js not included on the page when cookie consent is enabled

### ISSUE THREAD

**Issue by Mitjan11** [dnnsoftware/Dnn.Platform#2695] opened 2019-04-16 14:08 UTC
## Description of bug
The new cookie consent functionality released with DNN 9.3.1 depends on the window.dnn object being available which is created by dnn.js. However, when not using a skinobject that includes dnn.js on the page (or manually registering it), dnn.js is not included on the page and the cookie consent functionality breaks.

Relevant code:
```
$(window).on('load', function () {
    window.cookieconsentoptions = window.cookieconsentoptions || {};
    window.cookieconsentoptions.content = {
        message: window.dnn.getVar('cc_message'),
        dismiss: window.dnn.getVar('cc_dismiss'),
        link: window.dnn.getVar('cc_link')
    }
    if (window.dnn.getVar('cc_morelink') != '') {
        window.cookieconsentoptions.content.href = window.dnn.getVar('cc_morelink')
    }
	if (!window.cookieconsentoptions.palette) {
		window.cookieconsentoptions.palette = {
			"popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
		}
	}
    window.cookieconsent.initialise(window.cookieconsentoptions);
});    
```

Our current short-term (as in, critical fix) workaround involves including the search skinobject on the page in a hidden div. Less than ideal of course.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a simple empty page skin (no skinobjects that register dnn.js)
2. Enable the cookie consent functionality
3. Log out (dnn.js is loaded when logged in, into a SuperUser account anyway)
4. Cookie consent message does not show

## Current result
The cookie consent popup does not show.

## Expected result
The cookie consent popup should show.

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/5977710/56216479-ceda0680-6061-11e9-9eff-f09d232e1ddb.png)

## Error log
See above

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by Tychodewaard** [comment] 2019-05-21 16:41
This is in 9.3.2 as well.

**Comment by Tychodewaard** [comment] 2019-05-21 16:46
@Mitjan11 Do you know of another workaround? Because on of the sites is using SearchBoost, so, the skinobject has already been replaced...
Should I register something like:
`<dnn:DnnJsInclude runat="server" FilePath="js/dnn.js" ForceProvider="DnnFormBottomProvider" Priority="130" PathNameAlias="SkinPath" />` ?

**Comment by valadas** [comment] 2019-07-29 07:38
@Tychodewaard I think you proposed workaround should work, I have not tried it though, but we need to fix this bug and have thecookie consent feature request that file to be included for sure.

**Comment by yog-it** [comment] 2019-12-05 00:40
I had the same issue and your workaround fixes the issue by placing that line in the skin's .ascx file and removing PathNameAlias="SkinPath".

**Comment by valadas** [comment] 2020-07-28 19:37
Can no longer reproduce in 9.6.2 and I remember there was a PR merged about this.

**Comment by trouble2** [comment] 2021-03-29 13:29
![image](https://user-images.githubusercontent.com/1827559/112844024-8cb9fc00-90a3-11eb-9632-42699e7833be.png)
This is DNN 9.9.0

**Comment by valadas** [comment] 2021-03-29 16:10
I reopened the issue but I did not test this out, does it happen to you on a simple clean install just by enabling cookie consent or is there more steps to make it happen ?

**Comment by trouble2** [comment] 2021-03-30 06:50
Yes, this is a clean DNN 9.9.0 with cookie consent enabled.
This site has got it's own skin, so perhaps xcillion by default includes the dnn.js I don't know...

**Comment by valadas** [comment] 2021-03-30 15:41
Ok, thanks, I thought I had seen a PR to specifically fix this, guessed I dreamed about that. The issue is reopened. @donker does that ring a bell about being already fixed in a PR or am I just crazy?

**Comment by Tychodewaard** [comment] 2021-09-02 07:05
@valadas I think you were thinking of https://github.com/dnnsoftware/Dnn.Platform/issues/4762

**Comment by bdukes** [comment] 2021-09-02 13:18
Yes, in 9.10.1

**Closed by bdukes** 2021-09-02 13:18 UTC
Labels: Type: Bug
